### ISSUE TITLE
403 error fetching hindrance

### ISSUE THREAD

**Issue by olivermay** [Informatievlaanderen/GIPOD#100]
Hi @olivermay,

Thanks for explaining. We will be using the secured environment. When I try to fetch such a mobility hindrance, I get a 403 error. Probably something with our authorization call (scope)?

_Originally posted by @NickDaelemans in https://github.com/Informatievlaanderen/GIPOD/issues/92#issuecomment-685482666_

**Comment by olivermay** [comment]
@NickDaelemans, I created a different issue for this. Can you provide us with a correlation-id, so we can look into this?

**Comment by NickDaelemans** [comment]
I already fixed this. In the documentation I found the different scopes. By adding 'gipod_mh_read' I got access. Thanks anyway!
