### ISSUE TITLE
Missing location?

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#101]
Hebben jullie soms een voorbeeld van "location" data in de beta omgeving?

Ik roep volgende op /api/v1/public-domain-occupancies om een lijst te krijgen van gipodIds. Dan haal ik de detail op voor elke gipodId. Als voorbeeld uit die lijst in de beta omgeving "/api/v1/groundworks/3735104", dan zie ik in de detail waarden voor "status", "period", en "category". Da's ok.

Volgens de informatie hier [https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1637090283/Mapping+van+Hinder](https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1637090283/Mapping+van+Hinder) is "location" verhuist naar gevolg. So far so good... als ik dan kijk naar het gevolg in mijn voorbeeld: "/api/v1/mobility-hindrances/10210614" dan zie ik daar geen "location" bij staan of iets dat trekt op de waarden die ik verwacht, zoals "Gemotoriseerd verkeer geen doorgang".

Ik heb een aantal andere voorbeelden aan het bekijken geweest, maar ik vind geen enkel gevolg waar een "location" bij in zit. Kunnen julllie me een paar voorbeelden aanduiden in de beta omgeving waar die "location" ingevuld is.

mvg,
Sven

**Comment by olivermay** [comment]
Dag Sven,

Die info zit op de hinderzone, die moet je nog eens afzonderlijk opvragen. Zie ook deze comment: https://github.com/Informatievlaanderen/GIPOD/issues/92#issuecomment-685729325
