### ISSUE TITLE
Get TrenchSynergyRequest by Groundwork as answer (previous ListSynergieAanvraagBeantwoordByWerkopdracht)    

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#102]
Is there a possibilty to retrieve  a list of trench synergy requests answered with a given groundwork?

**Comment by doomsju** [comment]
This is not possible yet but is on our development backlog. It will be a extra query-sting parameter on the existing search endpoint for trench synergy requests (https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/SearchTrenchSynergyRequests).
Probably we take this up in our next sprint.

**Comment by doomsju** [comment]
Available in release https://github.com/Informatievlaanderen/GIPOD/issues/150
