### ISSUE TITLE
Opvragen gewijzigde GW/SSA/SSYN

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#104]
Hoe kan je alle GW/SSA en SSYN opvragen die de vorige dag gewijzigd werden ?
Krijg je dan ook de verwijderde GW/SSA en SSYN mee ?

**Comment by doomsju** [comment]
Op onze zoek endoints zijn de volgende query-string parameters beschikbaar die je daarvoor kan gebruiken: lastmodified.start, lastmodified.end.
Verwijderde GW/SSYN zullen niet terugkomen in deze resultaten. Om verwijderde resources op te vragen zullen we een ander endpoint voorzien. Dit is in onze planning opgenomen.
