### ISSUE TITLE
wanneer wordt de 0.9 beschikbaar ?

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#105]
Hallo,

Ik zit al even te wachten op een aantal zaken die in de 0.9 versie zitten.  Wanneer wordt dit beschikbaar voor ons ?

Ben bezig met het scenario wanneer wij willen meegaan op een synergieaanvraag van een andere partij.  Maar ik heb geen voorbeelden waarmee ik kan werken omdat we via de kleuren geen SSA kunnen aanmaken via de swagger.  Kan dit worden voorzien in afwachting van de nieuwe versie ?     Momenteel krijg ik de boodschap van geen autorisatie terug.

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
We zijn deze release aan het voorbereiden. Als alles volgens plan verloopt komt dit deze week nog beschikbaar.

**Comment by doomsju** [comment]
https://github.com/Informatievlaanderen/GIPOD/issues/109
