### ISSUE TITLE
Create and use searchzone

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#107]
Can you explain how we can use the searchzone feature? 

When I create a new zone the response I receive is:
`{
  "status": 0,
  "message": null
}`

I would expect to receive a Guid which I could use in the search operations.

**Comment by doomsju** [comment]
Op dit moment kan ik deze nog niet reproduceren. Welke http status code kreeg je terug?
De operatie was zeker geslaagd.
De response body zou er zo moeten uit zien:
{
  "searchZoneReference": "05F73A81-120D-45D1-1B9E-08D8554AED6A"
}

**Comment by jdewilde** [comment]
Ik krijg, zoals in swagger aangegeven, een OkResponseBody terug maar geen searchZoneReference.

**Comment by doomsju** [comment]
Het probleem is dat de response example in onze swagger niet correct is gedefinieerd. Wsch werk jij met gegenereerde code op basis van de OpenAPI definitie. Indien je zou proberen rechtstreeks in swagger zal je zien dat de response correct is.
We gaan de response example aanpassen. Normaal hebben we vandaag nog een nieuwe Beta release. We proberen dat er nog in te krijgen.

**Comment by doomsju** [comment]
Resolved in https://github.com/Informatievlaanderen/GIPOD/issues/109
