### ISSUE TITLE
GIPOD created with 2 Polygons on the MAP is NOK VIA API CreateWorkOrder.

### ISSUE THREAD

**Issue by ebivarghese** [Informatievlaanderen/GIPOD#110]
GIPOD Created with 2 polygons in eJMS, does not reflect the 2 polygons in the GIPOD ID :10211010

Expected:
GIPOD ID should create 2 polygons.

Actual:
GIPOD ID is created with only one polygon.

GIPOD Version : GIPOD II Beta
API : CreateWorkOrder
endPoint URL : /gipodRestService/v1/createsite 

Consumer : eJMS ( Proximus)
Attached request.

**Comment by doomsju** [comment]
Can you attach the request?

**Comment by ebivarghese** [comment]
Request attached, please let me know if you need more details.

**Comment by doomsju** [comment]
Cannot find the attachment.

**Comment by ebivarghese** [comment]
{
	"ownerId": "4e61986f-9507-084f-981f-d2b6fb570d8b",
	"reference": "JMS/476056/1",
	"description": "9880 Aalter - Aard - Plaatsen leidingen - 0m",
	"groundworkZone": "POLYGON((85115.979338262 202816.28280878,85108.40648496531 202801.02731562484,85103.31335096977 202784.77498765118,85100.82534613751 202767.92601111208,85101.00373340472 202750.8952637285,85103.84412028483 202734.10209902286,85109.27656702616 202717.96002044348,85117.16730876068 202702.8664995375,85127.32204923901 202689.19318888214,85139.49074504893 202677.27677076485,85153.373762514 202667.410666948,85168.62925566916 202659.8378136513,85184.88158364283 202654.7446796558,85201.73056018192 202652.25667482353,85218.7613075655 202652.43506209072,85235.55447227116 202655.27544897085,85251.69655085054 202660.70789571217,85266.79007175652 202668.5986374467,85280.46338241188 202678.75337792502,85292.37980052916 202690.92207373495,85302.245904346 202704.80509120002,85309.81875764269 202720.06058435517,85314.91189163823 202736.31291232884,85317.39989647048 202753.16188886794,85317.22150920327 202770.1926362515,85314.38112232316 202786.98580095716,85308.94867558184 202803.12787953654,85301.05793384732 202818.22140044253,85290.90319336898 202831.89471109788,85278.73449755907 202843.81112921517,85264.85148009399 202853.677233032,85249.59598693883 202861.2500863287,85233.34365896517 202866.34322032423,85216.49468242607 202868.8312251565,85199.4639350425 202868.6528378893,85182.67077033683 202865.81245100917,85166.52869175746 202860.38000426785,85151.43517085147 202852.48926253332,85137.76186019611 202842.334522055,85125.84544207883 202830.16582624507,85115.979338262 202816.28280878))POLYGON((84981.923855097 202761.95506034,84969.5349726995 202757.093046395,84958.059204553 202750.3528437194,84947.77912215515 202741.90041847253,84938.9478552522 202731.94389741597,84931.78285894464 202720.72844314194,84926.4605592208 202708.5302173566,84923.11200876356 202695.64958086237,84921.81965999841 202682.40369767818,84922.61533484099 202669.11872540854,84925.47944113599 202656.121784161,84930.341455081 202643.73290176352,84937.0816577566 202632.257133617,84945.53408300347 202621.97705121915,84955.49060406002 202613.1457843162,84966.70605833406 202605.98078800863,84978.9042841194 202600.6584882848,84991.7849206136 202597.30993782755,85005.03080379781 202596.0175890624,85018.31577606747 202596.813263905,85031.31271731498 202599.6773702,85043.70159971248 202604.539384145,85055.17736785898 202611.2795868206,85065.45745025684 202619.73201206746,85074.28871715978 202629.68853312402,85081.45371346734 202640.90398739805,85086.7760131912 202653.1022131834,85090.12456364842 202665.98284967762,85091.41691241358 202679.2287328618,85090.621237571 202692.51370513145,85087.757131276 202705.510646379,85082.89511733099 202717.89952877647,85076.15491465539 202729.37529692298,85067.70248940852 202739.65537932084,85057.74596835197 202748.48664622378,85046.53051407792 202755.65164253136,85034.33228829259 202760.9739422552,85021.45165179839 202764.32249271244,85008.20576861418 202765.6148414776,84994.92079634452 202764.819166635,84981.923855097 202761.95506034))",
	"statusId": "3232baa5-a157-4126-a2be-354ad1e480f7",
	"contactOrganisation": [{
		"organisationId": "4e61986f-9507-084f-981f-d2b6fb570d8b",
		"roleId": "0ebd21d7-350d-4eca-b320-d0f4d6ab84de",
		"website": "https://urlramkumar.com",
		"contactName": "ramkumar",
		"telephone": "+3226892231",
		"email": "ramkumar@proximus.com",
		"address": {
			"countryCode": "BE"
		},
		"isPublic": false
	},
	{
		"organisationId": "4e61986f-9507-084f-981f-d2b6fb570d8b",
		"roleId": "aad5e947-f7bf-4592-a84a-f591555b0b8b",
		"website": "https://testurl.com",
		"contactName": "Ch Sneha",
		"telephone": "03243747277",
		"email": "abc@test.com",
		"address": {
			"countryCode": "BE"
		},
		"isPublic": false
	}],
	"categoryId": "eb21d621-8f96-4bb9-9abd-7a8abdeade39",
	"publicDomainOccupancyTypeId": ["9ca97530-c1cf-45ed-8d80-e34563694d24"],
	"period": {
		"start": "2020-09-10T08:00Z",
		"end": "2020-11-30T17:00Z"
	},
	"isRelocationGroundwork": false,
	"causingGroundwork": [],
	"specificationId": ["bce64878-6cb7-43e7-896c-e01202a05e4c",
	"24222d39-c71a-40c5-9511-f65f6acfe2fb"],
	"estimatedDurationDays": 1
}

**Comment by doomsju** [comment]
You have to provide a wkt of type MULTIPOLYGON in the request.

**Comment by ebivarghese** [comment]
Request to be corrected for multipolygons
