### ISSUE TITLE
Signaling permit not being returned in Get Mobility hindrance API call.

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#111]
From issue: #45 
Signaling permit is still not being returned in Get Mobility hindrance API call.

For ex. in beta Mobility hindrance Gipod id 10207638 has a signaling permit id 10207639:
https://api-gateway.beta.gipod.vlaanderen.be/api/v1/mobility-hindrances/10207638/signaling-permits/10207639

but this is not being returned in Get Mobility hindrance API call.

Pls check & feedback.

**Comment by SilPal** [comment]
Hi Jurgen,
Can you tell us when this bug will be resolved please ?
The API is used in our ongoing integration with GIPOD2 and UAT testing will start soon....

Thanks for a quick reply.

**Comment by doomsju** [comment]
This issue is already resolved.
