### ISSUE TITLE
Issue met GET /api/v1/trench-synergy-requests-to-be-answered voor suborganisaties

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#113]
Hallo,

Ik heb aangelogd als blauw en 2 gelijke SSA's aangemaakt
* 10211288-10211289
* 10211290-10211291

Deze heb ik beantwoord met JA zonder grondwerk en daar heb ik 2 verschillende Fluvius suborganisaties meegegeven.  Voor het eerste door Fluvius site Dilbeek en het tweede Fluvius site Hasselt.

Daarna vraag ik de GET /api/v1/trench-synergy-requests-to-be-answered voor beide suborganisaties maar ik krijg maar 1 resultaat en dit is de eerste SSA (10211288-10211289) van Fluvius site Dilbeek.   Wanneer ik alleen Fluvius site Hasselt meegeef in deze API dan krijg ik 10211290-10211291 niet te zien.    Er is nochtans geen grondwerk meegegeven en de deadline1 is nog niet verstreken.  Ofwel mis ik iets, ofwel klopt er hier iets niet.

Dan heb ik ook nog een tweede vraag.  Wanneer je dezelfde API gebruikt voor meerdere organisaties dan kan je in het resultaat niet zien welke SSA's bij welke suborganisatie horen.  Is dat iets wat jullie nog gaan toevoegen ?   Zoniet, dan heeft het opvragen met meerdere suborganisaties tegelijkertijd voor ons weinig zin.

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Dag Bert,

Vanaf het ogenblik dat er is geantwoord op een ontvangen synergie-aanvraag, "ja, met voorwaarden", "ja, met grondwerken", "nee", dan verdwijnt deze uit de lijst te beantwoorden synergie-aanvragen.
Indien je geen grondwerken hebt toegevoegd in uw initiële antwoord dan zou deze synergie-aanvraag terecht moeten komen in de lijst van synergie-aanvragen waaraan je nog grondwerken moet toevoegen (/api/v1/trench-synergy-requests-with-groundworks-to-be-added).

We zullen de organisatieId wel opnemen in de response van deze endpoints.

Mvg,
Jürgen.

**Comment by hij242** [comment]
Jürgen,

Ok, nu snap ik het.  De SSA voor 10211288-10211289 is terecht gekomen in het interesse gebied van Fluvius Hasselt maar omdat ik erop geantwoord had met Fluvius Dilbeek was die wel zichtbaar in die api.  Het ander voorbeeld niet want die was wel door Fluvius Hasselt beantwoord.

Bedankt om het organisatieId nog op te nemen in de response.

Mvg,
Bert

**Comment by doomsju** [comment]
Resolved in API Beta 0.10.0
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1978598065/Release+notes+API+Beta+0.10.0
