### ISSUE TITLE
Announcement topic

### ISSUE THREAD

**Issue by olivermay** [Informatievlaanderen/GIPOD#114]
This pinned topic will be updated with all announcements regarding the GIPOD beta, staging and production environments.

**Comment by olivermay** [comment]
Announcement Release GIPOD production environment announcement production release for details see issue: #117

**Comment by olivermay** [comment]
Today at 17:00 CET we will release a new version of the beta API, see issue: #132

**Comment by olivermay** [comment]
Today we will release a new version of the UI, there is no towntime expected.

The release adds management of collaboration zone and management of synergies.

**Comment by doomsju** [comment]
A new version of the API on the staging environment will released today.

https://github.com/Informatievlaanderen/GIPOD/issues/133

**Comment by olivermay** [comment]
Today the UI version on beta will be pushed to staging. There is no downtime.

**Comment by doomsju** [comment]
Later today we release a new version of the Beta API. See isue #150.  Also the latest version of the GUI will be deployed on Beta. There is no expected downtime.

 Release will start at at 16:00 CET

**Comment by olivermay** [comment]
Today at 16:00 CET, the last API release from beta ( #150 ) will be installed on the staging environment. There will be limited or no downtime.

Also the latest version of the UI will be installed on the staging environment.

**Comment by doomsju** [comment]
A new version of the Beta API was released. See topic #173

**Comment by doomsju** [comment]
Today we bring the read api's on the GIPOD² environment in sync with the staging environment.

https://private-api.gipod.vlaanderen.be/api-documentation.html

**Comment by doomsju** [comment]
A new version of the Beta API was deployed: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2084700771/Hotfixes+0.12.x

**Comment by olivermay** [comment]
The latest version af the API in beta (0.12) will be deployed to staging later today.

**Comment by olivermay** [comment]
A new version of the Beta API was deployed: #200

**Comment by AIV-Bert** [comment]
Today we will release Beta-0.10.0 of the UI, there is no downtime expected.

**Comment by AIV-Bert** [comment]
Tonight we will release Staging-0.10.0 of the UI, there is no downtime expected.

**Comment by olivermay** [comment]
The detailed schedule of the release can be found in this issue: https://github.com/Informatievlaanderen/GIPOD/issues/223

**Comment by olivermay** [comment]
We start the release preparations today. You can follow the release status in this issue: https://github.com/Informatievlaanderen/GIPOD/issues/236

**Comment by doomsju** [comment]
Today  an API hotfix 1.0.1 is released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2355532566/Hotfixes+1.0.x

**Comment by AIV-Bert** [comment]
Tonight (26/01/2021 19:00) the API hotfix 1.0.2 is released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2355532566/Hotfixes+1.0.x

**Comment by AIV-Bert** [comment]
Today (27/01/2021 at 15:00) the API hotfix 1.0.3 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2355532566/Hotfixes+1.0.x

**Comment by AIV-Bert** [comment]
Today (28/01/2021 at 13:00) the UI hotfix 1.0.1 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
On 29/01/2021 at 13:00 API hotfix 1.0.4 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2355532566/Hotfixes+1.0.x

**Comment by AIV-Bert** [comment]
Today (03/02/2021 at 22:00) the UI hotfix 1.0.2 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
On 04/02/2021 at 12:00 API hotfix 1.0.5 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2355532566/Hotfixes+1.0.x

**Comment by AIV-Bert** [comment]
On 24/02/2021 at 8:00 API version 1.1.0 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2434893048/Release+notes+API+1.1.0

**Comment by AIV-Bert** [comment]
On 1/03/2021 at 15:00 API version 1.1.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2434893048/Release+notes+API+1.1.0

**Comment by AIV-Bert** [comment]
On 1/03/2021 at 19:00 API & UI version 1.1.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2434893048/Release+notes+API+1.1.0
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (12/03/2021 at 12:00) the UI version 1.2.0 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (12/03/2021 at 18:15) the API hotfix 1.1.1 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2434893048/Release+notes+API+1.1.x

**Comment by AIV-Bert** [comment]
Today (16/03/2021 at 17:00) the UI version 1.2.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (18/03/2021 at 18:30) the UI version 1.2.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (24/03/2021 at 01:00) the API hotfix 1.1.2 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2434893048/Release+notes+API+1.1.x

**Comment by AIV-Bert** [comment]
Today (26/03/2021 at 20:30) the API version 1.1.3 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2434893048/Release+notes+API+1.1.x
Today (26/03/2021 at 20:30) the UI hotfix 1.2.1 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (02/04/2021 at 14:00) the UI hotfix 1.2.2 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (12/04/2021 at 14:00) the UI 1.3.0 was released on Beta https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (12/04/2021 at 17:00) the UI 1.3.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (15/04/2021 at 13:00) the UI 1.3.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Yesterday (16/04/2021 at 20:00) the UI hotfix 1.3.1 was released on Staging 
Today  (17/04/2021 at 11:45) the UI hotfix 1.3.1 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Last Friday (16/04/2021 at 20:30) the API version 1.2.0 was released 
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2550563289/Release+notes+API+1.2.x

**Comment by AIV-Bert** [comment]
Today (19/05/2021 at 16:00) the UI 1.4.0 was released on Betahttps://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Yesterday (26/05/2021 at 23:30) the API version 1.3.0 was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
In July we will be removing some deprecated URL's that where used during the development phase. Please check the integrations that only the url's in following issue are used: 
https://github.com/Informatievlaanderen/GIPOD/issues/289

**Comment by AIV-Bert** [comment]
Yesterday (07/06/2021 at 15:00) the UI 1.4.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing
Yesterday (07/06/2021 at 15:00) the API version 1.3.0 was released on Staging 
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Today (16/06/2021 at 11:15) the API version 1.3.0 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

We received a request to alter the synergy-requests deadlines on Staging. 
The new deadlines are: 
- Deadline 1 (Answer request): 1 hour
- Deadline 2 (Add groundworks): 4 hours

**Comment by AIV-Bert** [comment]
Today (17/06/2021 at 10:00) the UI 1.4.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (25/06/2021 at 16:100) the API hotfix 1.3.1 was released on Staging and Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

The UI was impacted by this bug, but with this fix, should once again show all geographic search results correctly.

**Comment by AIV-Bert** [comment]
Today (12/08/2021 at 17:00) the API version 1.4.0 was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Today (19/08/2021 at 10:30) the release of API version 1.4.0 was completed on Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Today (19/08/2021 at 19:15) the release of API version 1.4.1 was completed on Beta & Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by bertzor** [comment]
Today (01/09/2021 at 11:15) the release of API version 1.4.1 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

We are currently processing the old data to comply with the new business rules and to support the new geographic search on the existing endpoints. Once all data is processed, an update will be posted in this topic.

**Comment by AIV-Bert** [comment]
Today (01/09/2021 at 11:15) the release of API version 1.4.1 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

We are currently processing the old data to comply with the new business rules and to support the new geographic search on the existing endpoints. Once all data is processed, an update will be posted in this topic.

**Comment by AIV-Bert** [comment]
Yesterday (02/09/2021 at 15:00) the API hotfix 1.4.2 was released on Beta, Staging and Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

On 02/09/2021 at 20:30, we finished processing old data to comply with the new business rules and to support the new geographic search on the existing endpoints.

**Comment by AIV-Bert** [comment]
Today (03/09/2021 at 16:00) the UI 1.5.0 was released on Beta https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (06/09/2021 at 10:15) the UI 1.5.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (06/09/2021 at 15:15) the UI 1.5.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
Last Friday (1/10/2021) the API 1.4.0 and UI 1.6.0 were released on Beta. 

Shortly this will be released on production, after a slight delay in timing.

The release is focused on the form for signaling permits.

**Comment by SilPal** [comment]
Dag Oliver,

Is het normaal dat de Release Notes niet aangepast werden ?
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

Enig idee wanneer "shortly" is ?

mvg,
Silvie

**Comment by olivermay** [comment]
The planned release was held back because of some issues that surfaced when using production data, we are currently fixing this. 

Once this issue is fixed and retested we can proceed with the release. This should be finished by the end of the week. We'll keep you posted.

The GUI release notes are indeed not published yet, we're wrapping this up.

**Comment by AIV-Bert** [comment]
Yesterday (05/10/2021 at 23:30) the UI 1.6.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing
Yesterday (05/10/2021 at 23:30) the API version 1.5.0 was released on Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Yesterday (06/10/2021 at 22:30) the UI 1.6.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing
Yesterday (06/10/2021 at 22:30) the API version 1.5.0 was released on Production 
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Today (04/11/2021 at 18:30) the API hotfix 1.5.1 was released on Beta and Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Today (05/11/2021 at 18:30) the API hotfix 1.5.1 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Last Thursday (25/11/2021 at 20:30) the API version 1.6.0 was released on Beta
Today (29/11/2021 at 15:45) the API version 1.6.0 was released on Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
Today (30/11/2021 after 17:00) new certificates will be installed on the production environment. The impact on the GIPOD services is minimal, but a short downtime in API availability or the authentication system is possible.

**Comment by AIV-Bert** [comment]
Today (06/12/2021 at 11:00) the API version 1.6.0 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by bertzor** [comment]
Today (14/12/2021 at 16:00) the API version 1.6.1 was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by bertzor** [comment]
Today (15/12/2021 at 15:55) the API version 1.6.1 was released on Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by bertzor** [comment]
Today (16/12/2021 at 11:30) the API version 1.6.1 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by AIV-Bert** [comment]
Today (14/12/2021 at 16:00) the API version 1.6.1 was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Today (15/12/2021 at 16:00) the API version 1.6.1 was released on Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Today (16/12/2021 at 11:30) the API version 1.6.1 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
Last friday (28/01/2022) a bugfix release was released on Beta.
This release didn't add any functionality, but provided some bugfixes on the 1.7.0 release: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
Today (03/03/2022) the API 1.7.0 was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

As a result of this release there are new notifications added in the GUI
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
> Today (03/03/2022) the API 1.7.0 was released on Beta https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API
> 
> As a result of this release there are new notifications available in the GUI https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

Update: Due to data migrations that are part of the release there might be some service degradation for up to 24 hours after the release. These inconveniences however will be mostly limited to the newly rolled-out features such as new notifications.

**Comment by olivermay** [comment]
Today (04/03/2022) the API 1.7.0 was released on Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

As a result of this release there are new notifications available in the GUI
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

Due to data migrations that are part of the release there might be some service degradation for up to 24 hours after the release. These inconveniences however will be mostly limited to the newly rolled-out features such as new notifications.

**Comment by olivermay** [comment]
Today (08/02/2022) we started preparations for the API 1.7.0 production release. 

The first part of this process are data migrations to prepare the release, these migrations should have no effect on the availability of GIPOD, however slight delays are possible.

Once the data migrations are ready, we will start rolling out the new release later this week, there is no substantial downtime planned.

**Comment by AIV-Bert** [comment]
Today (25/03/2022) at 14:30 the API 1.7.1 was released on Beta https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Today (25/03/2022) at 14:30 the UI 1.8.0 was released on Beta https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by AIV-Bert** [comment]
Today (25/03/2022) at 20:00 the API 1.7.1 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Today (25/03/2022) at 20:00 the UI 1.8.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
Today (28/03/2022) at 15:00 the API 1.7.1 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Today (28/03/2022) at 15:00 the UI 1.8.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by bertzor** [comment]
Yesterday (29/06/2022 at 12:30) the API version 1.8.0 was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Yesterday (29/06/2022 at 12:30) the UI 1.9.1 was released on Beta https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

Today (30/06/2022) at 15:30 the API 1.8.0 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Today (30/06/2022) at 15:30 the UI 1.9.1 was released on Staging https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
Today (04/07/2022) at 9:00) the API 1.8.0 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Today (04/07/2022) at 9:00) the UI 1.9.1 was released on Production https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by doomsju** [comment]
Today (23/08/2022 at 10u15) the API 1.9.0  was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
Regarding the 1.9.0 API release, please bare in mind that there is a **breaking change**: 

“GET, PATCH /api/v1/request-for-groundworks/{gipodId}”: The element “reasonStatusNoAgreement” has been removed and replaced by element “reasonStatus

version 1.9.0 will be deployed into staging and production shortly.

**Comment by olivermay** [comment]
Today (16/09/2022 at 10:45) the API 1.9.0 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Reminder: please bare in mind that there is a breaking change:
“GET, PATCH /api/v1/request-for-groundworks/{gipodId}”: The element “reasonStatusNoAgreement” has been removed and replaced by element “reasonStatus

**Comment by olivermay** [comment]
Today (23/09/2022 at 13:00) the GUI 1.10.0 was released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
Tuesday 18/10/2022 the GUI 1.10.1 was released on Beta
Today (21/10/2022 at 12:00) the GUI 1.10.1 was released on Staging
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
This friday 26/10/2022 the GUI 1.10.1 will be released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
This friday 28/10/2022 at 8:50 the new GUI 1.10.1 was released on Production
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
This thursday 10/11/2022 between 9:00 and 12:00 the new API 1.10.0 and will be released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

Afterwards, on monday 14/11/2022 the new GUI 1.11.0 will be released on Beta
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by olivermay** [comment]
Today at 9:42 the new API 1.10.0 was released on Beta. After some minor glitches during the update all systems are nominal since 10:25, internal smoke testing continues during the rest of the day.
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
As planned the new GUI 1.11.0 was released on Beta last monday.

**Comment by olivermay** [comment]
This Friday 18/11/2022 between 9:00 and 12:00 the new API 1.10.0 and GUI 1.11.0 will be released on **Staging**.
Next Tuesday 22/11/2022 between 9:00 and 12:00 the new API 1.10.0 and GUI 1.11.0 will be released on **Production**.

**Comment by olivermay** [comment]
Due to possible data downtime the production release is postponed to this evening, 22/11/22 at 20:00.

**Comment by olivermay** [comment]
The API 1.10.0 and GUI 1.11.0 have been successfully released to production. 

For the history to become visible in the GUI (and API) we need to process all event history, this will take some time, ETA: november 25th.

**Comment by olivermay** [comment]
Hi all, we are experiencing issues on the production system, the oslo read api is no longer up-to date with changes since early this morning. We are working on fixing this.

**Comment by olivermay** [comment]
The issue has been fixed on production. Root-cause was invalid (duplicate) data on trench synergy contact information, causing a huge delay on the OSLO read API, further analysis will be done to harden the system.

**Comment by olivermay** [comment]
Thursday 9/02/2023 the new API 1.11.0 was released on **Staging.**

Next Thursday 16/02/2023 at 16:00 this version will be released on **Production.**

Release notes: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
The new API 1.11.0 was released on Production. 

Release notes: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
Yesterday 13/03/2023 the new API 1.11.1 was released on **Staging.**
Next Monday 20/03/2023 at 16:00 the new API 1.11.1 will be released on **Production.**

Release notes: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API

**Comment by olivermay** [comment]
Due to an issue at Geosecure, it is currently not possible to log in again in the GIPOD application. This issue is being investigated and we hope for a resolution soon.

More information can be found on https://www.vlaanderen.be/digitaal-vlaanderen/status/incidenten-geschiedenis/419jp0m6sm3l

**Comment by olivermay** [comment]
On Tuesday April 11th there will be a database migration on the Beta environment, therefore we expect some downtime between 15:00 and 17:00 CET.

**Comment by olivermay** [comment]
The migration has been executed successfully, we continue with smoke tests, but no further downtime is expected.

**Comment by olivermay** [comment]
On 17/08/2023 version 1.13.0 was released on beta. This release includes the API's for general permits. More information in the release notes: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/5493720619/Release+notes+API#1.13.0
