### ISSUE TITLE
To retrive only the newly added and modified GO-SSA-SSYN.

### ISSUE THREAD

**Issue by ebivarghese** [Informatievlaanderen/GIPOD#115]
could you please help us understand which input parameters to be used to retrive only newly added and modified GO-SSA-SSYN between two given dates for the below operations.

/api/v1/public-domain-occupancies
/api/v1/trench-synergies
/api/v1/trench-synergy-requests 

in this operation we are currently using "start and end" input parameters, instead should we be using "lastmodifiedstart" and "lastmodifiedend" input parameters ?
Start and end input parameters currenlty fetches all of the overlapping GIPOD ids.

Please feedback.

**Comment by doomsju** [comment]
You have to use parameters "lastmodified.start" & "lastmodified.end" to achieve this.

The start & end parameters are uses to search for entities that will occur during the specified period.

**Comment by ebivarghese** [comment]
Thank you, we will adapt the same.
