### ISSUE TITLE
Time is not in sync between GIPOD and eJMS application

### ISSUE THREAD

**Issue by SnehalataCh** [Informatievlaanderen/GIPOD#116]
Time is not in sync between GIPOD and eJMS application after creating GIPOD WO in eJMS.

Created GIPOD WO(10211348) with- start":"2020-09-21T08:00Z","end":"2021-09-18T17:00Z

Expected:
Time in GIPOD should be -start":"2020-09-21T08:00Z","end":"2021-09-18T17:00Z

Actual:
Time in GIPOD is -start":"2020-09-21T10:00Z","end":"2021-09-18T19:00Z

GIPOD Version : GIPOD II Beta
API : CreateWorkOrder
endPoint URL : /gipodRestService/v1/createsite
Consumer : eJMS ( Proximus)

Request :

{"ownerId":"0b381ccd-d127-067e-993b-a9e962cf2660","reference":"JMS/476363/2","description":"1650 Beersel - Acacialaan - Plaatsen leidingen - 0m","groundworkZone":"POLYGON((148435.06338924 159769.36964313,148435.21310336268 159769.45983195555,148435.34686561537 159769.57233085573,148435.4613823275 159769.7043697342,148435.55383371757 159769.85269735556,148435.6219433255 159770.0136614015,148435.66403406672 159770.18329840302,148435.6790695275 159770.35743133415,148435.66667948486 159770.5317724642,148435.6271690228 159770.70202893595,148435.56151102003 159770.86400847,148435.47132219447 159771.01372259267,148435.3588232943 159771.14748484536,148435.22678441583 159771.2620015575,148435.07845679446 159771.35445294756,148434.91749274853 159771.4225625555,148434.747855747 159771.46465329672,148434.57372281587 159771.4796887575,148434.39938168583 159771.46729871485,148434.22912521407 159771.4277882528,148434.06714568002 159771.36213025002,148433.91743155735 159771.27194142446,148433.78366930466 159771.15944252428,148433.6691525925 159771.02740364583,148433.57670120246 159770.87907602446,148433.50859159452 159770.71811197852,148433.4665008533 159770.548474977,148433.4514653925 159770.37434204586,148433.46385543517 159770.20000091582,148433.50336589722 159770.02974444407,148433.5690239 159769.86776491,148433.65921272556 159769.71805078734,148433.77171162574 159769.58428853465,148433.9037505042 159769.4697718225,148434.05207812556 159769.37732043245,148434.2130421715 159769.30921082452,148434.38267917302 159769.2671200833,148434.55681210416 159769.2520846225,148434.7311532342 159769.26447466516,148434.90140970595 159769.30398512722,148435.06338924 159769.36964313))","statusId":"b96e6ec6-58f1-4a51-ab92-f0ce462476a7","contactOrganisation":[{"organisationId":"0b381ccd-d127-067e-993b-a9e962cf2660","roleId":"0ebd21d7-350d-4eca-b320-d0f4d6ab84de","website":"https://urlramkumar.com","contactName":"ramkumar","telephone":"+3226892231","email":"ramkumar@proximus.com","address":{"countryCode":"BE"},"isPublic":false},{"organisationId":"0b381ccd-d127-067e-993b-a9e962cf2660","roleId":"aad5e947-f7bf-4592-a84a-f591555b0b8b","website":"https://testurl.com","contactName":"Ch Sneha","telephone":"0324563741","email":"snehalata.cholla.ext@proximus.com","address":{"countryCode":"BE"},"isPublic":false}],"categoryId":"bb0b471a-7f4d-4eaa-b788-adae1aaf30f8","publicDomainOccupancyTypeId":["9ca97530-c1cf-45ed-8d80-e34563694d24"],"period":{"start":"2020-09-21T08:00Z","end":"2021-09-18T17:00Z"},"isRelocationGroundwork":false,"causingGroundwork":[],"specificationId":["bce64878-6cb7-43e7-896c-e01202a05e4c","24222d39-c71a-40c5-9511-f65f6acfe2fb"],"estimatedDurationDays":1}

**Comment by doomsju** [comment]
The api response of detail of this groundwork contains the correct period information.
https://api-gateway.beta.gipod.vlaanderen.be/api/v1/groundworks/10211348
  
"period": {
    "@type": "PeriodWithDuration",
    "start": "2020-09-21T08:00:00Z",
    "end": "2021-09-18T17:00:00Z",
    "duration": null
  }

Can you check the internals of the eJMS application?

**Comment by SnehalataCh** [comment]
Api response shows the correct period information but in GIPOD UI- period information is different.
GIPOD WO ID- 10211697

"period": {
    "@type": "PeriodWithDuration",
    "start": "2020-09-22T08:00:00Z",
    "end": "2021-09-18T17:00:00Z",
    "duration": null
  },

Please find the screenshot of GIPOD UI.

![GIPOD UI](https://user-images.githubusercontent.com/71489677/93854742-94dd4d00-fcb6-11ea-88a9-7c5507281a44.PNG)

**Comment by doomsju** [comment]
The GIPOD-ui displays the period in the local time in Belgium.

**Comment by SnehalataCh** [comment]
Thanks for the update.
