### ISSUE TITLE
JWTCredentialsGrant niet toegestaan maar opzet is hier wel op gebasseerd

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#118]
Enkel grant type 'client_credentials' is toegestaan (https://tools.ietf.org/html/rfc6749#section-4.4) maar authenticatie opzet neigt eerder naar een grant type 'JWTCredentialsGrant' (https://tools.ietf.org/html/rfc7523#section-2.1).
Waarom is die laatste niet toegestaan?

Alvast bedankt,
Tom

**Comment by vmateiaiv** [comment]
Beste @TomCap1432,

Wij ondersteunen client_credentials met client_assertion_type="urn:ietf:params:oauth:client-assertion-type:jwt-bearer". Dus dat is precies JWTCredentialsGrant. 

Heb ik uw vraag beantwoord of is er nog iets die niet duidelijk is?

Mvg,
Voicu Matei
AIV

**Comment by vmateiaiv** [comment]
Beste @TomCap1432,

Wiz zijn idd voor de moment niet in lijn met de standard. De grant_type zou anders moeten zijn volgens de RFC: 
"The value of the "grant_type" is "urn:ietf:params:oauth:grant-
   type:jwt-bearer"."

Maar de implementatie is anders wel compatiebel.

Mvg,
Voicu Matei
AIV

**Comment by TomCap1432** [comment]
Dag Voicu,

Via standaard tools die we gebruiken om de integratie op te zetten, is het enkel mogelijk om grant_type 'urn:ietf:params:oauth:grant-type:jwt-bearer' door te sturen.
Gaat dit nog veranderen dat dit toegestaan gaat worden of moeten we reeds gaan voor een custom implementatie?

Alvast bedankt,
Tom

**Comment by AIV-Bert** [comment]
Dag @TomCap1432,

We hebben dit doorgegeven aan het team die de authenticatie flows beheert. Ze konden niet garanderen dat de aanpassing nog voor de productie launch in november hun processen zou kunnen doorlopen.

Het is echter iets dat ze zeker willen bekijken. Daarom had ik ook graag meer info over de tools die je gebruikt. Dit kan handig zijn om de aanpassingen te testen wanneer deze ontwikkeld zijn. Zo zijn we meteen zeker dat er geen andere issues zijn met de tool die je gebruikt dan het "grant_type".

Met vriendelijke groeten,

Bert

**Comment by TomCap1432** [comment]
Dag Bart,

Voor de integratie maken wij gebruik van standaard SAP PI (Proces Integration), hierin is de mogelijkheid om 'JSON Web Token Credentials Grant' op te zetten waarbij het niet nodig is om met externe libraries het JWT-signature aan te maken. Dit wordt automatisch gegenereerd door SAP PI zelf.

Een voorbeeld call heb ik hier niet, maar deze verschilt normaal niet met wat er nu voor GIPOD beschikbaar is. Enkel het grant_type is verschillend voor de rest is deze opgezet zoals de standaard:
https://tools.ietf.org/html/rfc7523#section-2.1 

Wanneer zouden jullie weten dat dit niet meer voor november haalbaar zou zijn?
We beginnen alvast met plan b op te zetten indien het toch niet voor november zou lukken.

Alvast bedankt,
Tom

**Comment by AIV-Bert** [comment]
Dag Tom,

Inzetten op je plan B is inderdaad de beste optie. November is niet meer haalbaar voor het authenticatie team.

Testen met SAP wordt moeilijk voor ons, maar als je zeker bent dat het enkel het 'grant_type' is, weten wij genoeg met de info die je ons gaf.

Bedankt voor dit te melden.

Met vriendelijke groeten,

B.

**Comment by TomCap1432** [comment]
Dag Bert,

Grant_type zal inderdaad enkel verschillen.

Bedankt voor de snelle opvolging!
Tom

**Comment by AIV-Bert** [comment]
Dag Tom,

We hebben dit verder bekeken. We gebruiken de JWT enkel voor client authenticatie. In dit geval gebruik je **jwt-bearer** (urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer) als _client-assertion-type_ maar verandert er niets aan het _grant-type_. (zie https://tools.ietf.org/html/rfc7523#section-2.2)

Jullie proberen momenteel om een JWT te gebruiken als bearer token ipv client authenticatie. (Zie https://tools.ietf.org/html/rfc7523#section-2.1) Dit ondersteunen we niet.

Hopelijk kan je hier mee verder in jullie tools. Onze implementatie volgt dus de standaard en zal niet aangepast worden.

Met vriendelijke groeten, 

Bert
