### ISSUE TITLE
Lijsten met verwijderde items

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#119]
Wanneer zal het mogelijk zijn om de lijsten met verwijderde items op te halen? GW, W, E, TS, MH, ...

**Comment by doomsju** [comment]
Is momenteel in ontwikkeling en in de volgende Beta beschikbaar. Ik kan wel nog geen vaste datum doorgeven.

**Comment by doomsju** [comment]
Beschikbaar in release https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1978598065/Release+notes+API+Beta+0.10.0. 
Verwijderde entities zijn opvraagbaar via endpoint GET api/v1/entities.
