### ISSUE TITLE
Gipod² en ontwikkelen/testen/valideren

### ISSUE THREAD

**Issue by MariekeFluvius** [Informatievlaanderen/GIPOD#12]
Is er enkel een bèta-omgeving voor Gipod² beschikbaar voor ons? We hebben meerdere omgevingen en het zou ergens wel handig zijn om deze naar verschillende omgevingen te koppelen. Anders komen al onze werken op dezelfde bèta-site terecht. Niet onoverkomelijk natuurlijk -want zo werkt het nu ook- maar wel minder overzichtelijk voor ons :)

En nog een vraag voor de zekerheid: is het in de toekomst nog mogelijk (en niet onwenselijk) om met suborganisaties te werken?

**Comment by olivermay** [comment]
Hi Marieke, for now we only have the beta environment and production (read only). We might create a staging environment when starting the GUI testing and trainings later, but nothing has been decided yet.

As for the sub organisation, the team confirms that this is implemented, and will be available in the next beta release.

cheers, 

Oliver
