### ISSUE TITLE
Hindrance consequences types with the same value

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#120]
**Describe the bug**
The API call to get the list of hindrance consequence types ({{baseUrl}}/api/v1/taxonomies/mobility-hindrance/consequencetypes) contains to concepts with the same value but different labels, namely Breedtebeperking and Hoogtebeperking both have the same value 'ade5f476-d234-44be-a5ee-3d9274d12230'.

**Expected behavior**
All concepts should have unique values/id's

**Comment by doomsju** [comment]
Resolved in API Beta 0.10.0
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1978598065/Release+notes+API+Beta+0.10.0
