### ISSUE TITLE
URL for mobility hindrance and signaling permit

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#121]
Will mobility hindrance and signaling permit objects also have a 'fixed' url like we have for intakes (new.beta.gipod/innames/[id])?

**Comment by AIV-Bert** [comment]
Hi @berdienderoo 

Mobilityhindrance and signaling permit will have a 'fixed url'. The exact url is still under review.

Kind regards,

Bert

**Comment by olivermay** [comment]
Here are the url's: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1997668568/URL+s+gui

**Comment by berdienderoo** [comment]
As discussed in the 'question time', the URL for the mobility hindrance is missing on this page.
