### ISSUE TITLE
Problemen met grondwerken aanmaken/bekijken op staging omgeving

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#122]
Hallo,

Er zijn wat problemen met de UI op de staging omgeving voor het aanmaken en bekijken van grondwerken.  

Ik krijg telkens een boodschap na aanmaak van een nieuw grondwerk : "er ging iets mis bij het laden"
Ik krijg  een boodschap bij het openen van een bestaand grondwerk, enkel bij de meest recente : "we kunnen de gegevens voor 8519305 niet terugvinden"

Heb geprobeerd met Fluvius Hasselt login en met algemene Fluvius login.

Kijken jullie eens na ?

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Is opgelost. We onderzoeken het verder.

**Comment by hij242** [comment]
Bedankt en fijn weekend !
