### ISSUE TITLE
Ontbrekend "consequence" op zone gerefereerd door GrondwerkZone

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#123]
TL;DR: Bug of feature request... er ontbreekt logisch gezien een "consequence" op de zone (direct) gerefereerd door GrondwerkZone.

Voor de hinderpremie ben ik alleen geinteresseerd in het uitlezen van gegevens, niet in het opladen in GIPOD.

Voor een eerste fase wil ik ongeveer een zelfde extract halen uit GIPOD2 als nu uit de huidige GIPOD. Ik ben geinteresseerd in GrondwerkZones met duur van meer dan 30 dagen, eerste categorie, status concreet gepland/in uitvoering, locaties: alles op de weg.

In de huidige GIPOD vragen we een lijst van (laatste) veranderingen in werkopdrachten en we krijgen een blok informatie (met status, duur, categorie en locatie) terug per veranderde opdracht, elk met 1 gipodid.

In GIPOD2 zitten HinderZones extra in, maar die heb ik in eerste fase eigenlijk niet nodig. Dus ik vraag alle laatste veranderingen in "public domain occupancies" op, ik kan duration ervan berekenen (start en stop zijn ingevuld, duration blijkbaar niet) en selecteren op de status en category ervan. Nu, voor "locations" (of wat dat vervangt), zou ik over "hasConsequence" moeten gaan naar MobileHindrance, en daar "consequence" nemen op de MobileHindranceZone ervan.
Dan heb ik wel de "consequence" van de MobileHindranceZone, maar eigenlijk niet de "consequence" van de GrondwerkZone. Ik kan me inbeelden dat er een verschillend gevolg/consequence is van een inname als van de bijbehorende hinderzone: de inname zelf is bv helemaal afgesloten terwijl de rest van de straat hinder heeft maar niet afgesloten is.

Het zou logischer zijn om ook een consequence te hangen aan de zone direct gerefereerd in de GrondwerkZone (en bij uitbreiding bij alle public domain occupancies). Het zou ook het aantal REST calls verminderen.

---

Het linken over MobileHindrances geeft nog wat andere problemen... wat als er meerdere MobileHindrances zijn per PublicDomainOccupancy, en/of meerdere zones voor een 1 HinderZone. Welke consequence is van toepassing voor zo'n Public Occupancy.
Als ik alle veranderingen wil capteren moet ik waarschijnlijk ook nog de lijst opvragen van veranderde MobileHindrances, en dan gaan kijken naar de PublicDomainOccupancies waar ze een gevolg van zijn. omdat MobileHindrances kunnen veranderen zonder dat de PublicDomainOccupancy ervan verandert: iemand die bv enkel de consequence van een MobileHindrance aanpast.

**Comment by sboden** [comment]
Nog wat aanvullend informatie. 

De reden voor de "locatie" in de huidige GIPOD wat dan gemapped zou worden op gevolgen in GIPOD2, is "art. 3, 3° van het GIPOD-decreet van 4 april 2014" op [https://codex.vlaanderen.be/Portals/Codex/documenten/1024277.html](https://codex.vlaanderen.be/Portals/Codex/documenten/1024277.html), wat dan ook gebruikt wordt in huidige hinderpremie.

Een alternatieve oplossing zou zijn om een extra zoek parameter, bijvoorbeeld "consequenceid", te definieren op "/api/v1/public-domain-occupancies", die dan public domain occupancies zou moet geven die een mobile hindrance/hinderzone hebben als consequence die voldoet aan consequenceid (op een zone ervan). De complexiteit van die functionaliteit is ongeveer de complexiteit die nu in hinderpremie moet komen, kwestie om een idee te geven van waar de "pijn" zit.

Dan komen ook zo van die vervelende extra vragen naar boven:
- Wat gebeurt er met public domain occupancies zonder mobile hindrance, die zouden nooit geselecteerd worden omdat er geen consequence is: als er een publieke inname is voor grondwerken vermoed ik dat er op de plaats zelf toch wel "ernstige hinder" is. In de beta omgeving bv [https://api-gateway.beta.gipod.vlaanderen.be/api/v1/groundworks/10212573 ](https://api-gateway.beta.gipod.vlaanderen.be/api/v1/groundworks/10212573) als grondwerk zonder hinderzone.
- Wat gebeurt er indien alle gevolgen op de hinderzones van een reeds geselecteerde inname, zo worden veranderd dat het gevolg nadien niet meer voldoet niet meer voldoet aan de selectie. Als ik de veranderingen opvraag via /api/v1/public-domain-occupancies, zouden die dan verschijnen (omdat de verandering gebeurd is op mobile hindrance, en niet op public domain occupancy).

Het achterliggend probleem is dat het GIPOD2 model flexibeler is dan de huidige GIPOD (vermoed ik), maar dat bepaalde elementen in GIPOD2 zo opgesplitst zijn in entiteiten dat het het moeilijker maakt om er bepaalde informatie uit te halen. Van de huidige GIPOD vragen we gewoon de veranderde werkopdrachten op, en alle informatie om "art. 3, 3°" te selecteren is beschikbaar op zo'n werkopdracht (duur, categorie, status, locatie). Als je het GIPOD decreet naar de letter leest voldoet GIPOD2 eigenlijk niet aan het huidige GIPOD decreet.

Nadien in een volgende fase is het probleem omgedraaid. Als er wordt beslist om hinder uit te betalen op hinderzones ipv van op innames: op hinderzone heb ik duur en "gevolg", maar ik heb daar geen categorie en status. Maar dat hangt er dan ook vanaf hoe het nieuwe GIPOD decreet er gaat uitzien.

**Comment by AIV-Bert** [comment]
Issue verder afgehandeld via rechtstreeks overleg.
