### ISSUE TITLE
End Time is not correct in GIPOD UI after creating GIPOD WO in eJMS.

### ISSUE THREAD

**Issue by SnehalataCh** [Informatievlaanderen/GIPOD#125]
Issue with end Time in GIPOD after creating GIPOD WO in eJMS.

Created GIPOD WO(10212296) with- start time":"2020-09-29T08:27:00Z","end time":"2020-12-24T13:43:00Z"

Expected:
End Time in GIPOD should be -:"2020-12-24T15:43:00" (after converting the period in API to Belgium local time)

Actual:
End Time in GIPOD is -:"2020-12-24T14:43:00"

GIPOD Version : GIPOD II Beta
API : CreateWorkOrder
endPoint URL : /gipodRestService/v1/createsite
Consumer : eJMS ( Proximus)

Api response shows the correct period information (which is in sync with eJMS application) but in GIPOD UI- period information is different.
GIPOD WO(10212296)

 "period": {
    "@type": "PeriodWithDuration",
    "start": "2020-09-29T08:27:00Z",
    "end": "2020-12-24T13:43:00Z",
    "duration": null
  },

GIPOD should display the end time as 2020-12-24T15:43:00 (after converting the period to Belgium local time)

Note: Facing this issue only with end time. No issues with start time. 

![GIPOD UI](https://user-images.githubusercontent.com/71489677/94530708-c5376500-023b-11eb-9330-ed31c8485f4b.PNG)

**Comment by bertzor** [comment]
Hi @SnehalataCh,

The Belgum local time uses daylight saving times. The offset between UTC time is different during summer and winter. This is the correct and expected behavior.

> CET alternates between UTC+1 (standard time) and UTC+2 (when daylight saving time (DST) is observed). All countries in the CET time zone observe DST (UTC+2) from 02:00 am on the last Sunday of March until 03:00 am on the last Sunday of October.

Kind regards,

Bert

**Comment by doomsju** [comment]
This endtime is in correct in local wintertime"

**Comment by AIV-Bert** [comment]
Hi @SnehalataCh,

The Belgum local time uses daylight saving times. The offset between UTC time is different during summer and winter. This is the correct and expected behavior.

> CET alternates between UTC+1 (standard time) and UTC+2 (when daylight saving time (DST) is observed). All countries in the CET time zone observe DST (UTC+2) from 02:00 am on the last Sunday of March until 03:00 am on the last Sunday of October.

Kind regards,
Bert

**Comment by SnehalataCh** [comment]
Hi Bert,

Thanks for the info. Currently(on 29th Sept 2020), Belgium local time is UTC+02:00 as Belgium is in day light saving time (DST).

Api response shows the correct period information below (which is in sync with eJMS application).
GIPOD WO(10212296)

"period": {
"@type": "PeriodWithDuration",
"start": "2020-09-29T08:27:00Z",
"end": "2020-12-24T13:43:00Z",
"duration": null
},

Below should be the local time of Belgium when the above period is converted to Belgium local time (UTC+02:00).
Expected Belgium time- Start : "2020-09-29T10:27:00"    (UTC+02:00)
                                        End  :  "2020-12-24T15:43:00"   (UTC+02:00)

Actual time displayed in GIPOD UI: Start : "2020-09-29T10:27:00"    (UTC+02:00)
                                                        End  :  "2020-12-24T14:43:00"   (UTC+01:00)

In GIPOD UI- Start date/time is displayed correctly UTC+02:00. But the end date date/time is UTC+01:00.

Could you please confirm if this is expected behavior as conversion from UTC to CET is different for start and end time in GIPOD UI.
