### ISSUE TITLE
Ophalen SSA

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#126]
Hoe kunnen we de details van een sleufsynergieaanvraag ophalen enkel en alleen via het gipod van de ssa?
of
Hoe kunnen we het grondwerk gipodid ophalen op basis van een sleufsynergieaanvraag gipodid, zonder de waarde van het id uit de call /api/v1/resources te moeten gaan halen?

**Comment by AIV-Bert** [comment]
Dag @jdewilde,

Als je enkel de ID van de SSA hebt, kan je de ID van het grondwerk niet ophalen zonder een extra call naar **/api/v1/resources**.
Ook om bijvoorbeeld het detail van de SSA op te vragen moet je altijd zowel de ID van het grondwerk en als van de SSA hebben.

Gebruiken jullie het endpoint **/api/v1/resources** al? Er komt immers een verbeterde versie van dit endpoint bij de volgende beta release, deze week. Het kan dus interessant zijn om nog enkele dagen te wachten op het nieuwe endpoint. **/api/v1/entities** zal extra filters en mogelijkheden ondersteunen zoals meerdere id's opzoeken, filteren op type ... Vanaf dan raden we ook af om **/api/v1/resources** nog verder te gebruiken.

Met vriendelijke groeten,

Bert

**Comment by langens-jonathan** [comment]
Hey @AIV-Bert 

I suspect this only is true for SSAs?

To be more precise for specific resources of which the Id and type are known we can keep using the /api/v1/resource endpoints (for instance for groundwork 1, we make a GET call to /api/v1/groundworks/1).

This is correct?
Thanks
Jonathan

**Comment by doomsju** [comment]
That's correct.

**Comment by AIV-Bert** [comment]
Only when your own system doesn't keep track of the launching groundwork of the SSA, you need to find the required info in the '/api/v1/entities' endpoints to build the request for the SSA detail. 

In your example the GipodId of the entity is indeed enough to make the call, so there is little use in calling the '/api/v1/entities' first.
