### ISSUE TITLE
Updating GW start & end date with same date value comes up with an error.

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#127]
Hello,
Updating GW start & end date with same date value (but different time) comes up with an error response. More details below.

Pls check & feedback.

Request;
curl -X PATCH "https://api-gateway.beta.gipod.vlaanderen.be/api/v1/groundworks/10212277" -H "accept: application/json" -H "Authorization: Bearer 0ssJhCXcFNDxWv4grq7lhQ==" -H "Content-Type: application/json" -d "{\"items\":[{\"key\":\"Period\",\"value\":{\"start\":\"2020-10-01T08:00Z\",\"end\":\"2020-10-01T17:00Z\"}}]}"

Response:
{
  "type": "https://httpstatuses.com/400",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "detail": "Please refer to the errors property for additional details.",
  "errors": [
    {
      "type": "urn:be.vlaanderen.gipod.errors:InvalidGroundworkPeriodAndEstimatedDurationCombinationException",
      "title": "Groundwork period GroundworkPeriod: {\"Start\":\"2020-10-01T08:00:00Z\",\"End\":\"2020-10-01T17:00:00Z\",\"Duration\":null} is invalid in combination with estimated duration estimatedDuration: {\"Days\":1}.\n ",
      "detail": "Groundwork period GroundworkPeriod: {\"Start\":\"2020-10-01T08:00:00Z\",\"End\":\"2020-10-01T17:00:00Z\",\"Duration\":null} is invalid in combination with estimated duration estimatedDuration: {\"Days\":1}.\n "
    }
  ]
}

Response headers:
api-supported-versions: 1.0 
 content-type: application/problem+json 
 date: Tue29 Sep 2020 09:46:30 GMT 
 request-context: appId=cid-v1:ecee8c3f-c3ee-4da1-9ab9-7d2e92a6cb24 
 server: Kestrel 
 transfer-encoding: chunked 
 x-correlation-id: 822574a2-0934-499c-8051-6e3463006504

**Comment by rajeevchugh71** [comment]
Thanks a lot Bert for your response!

The thing is the estimated duration (mandatory) is an integer so it cannot have a value of 0.5 (for example). 
As this is one of our valid use cases, could you pls propose a solution?

Also, could you pls confirm 1 day for Gipod platform is 24H?

br,

**Comment by AIV-Bert** [comment]
After further investigation, you should be able to make your request (occure between 8:00 and 17:00 on 1st october 2020, with estimated duration 1 day) without a validation error. You can expect a bugfix in the next release.

The estimated duration mainly is used when the period indicated, is larger than the actual time needed for the groundwork. In your case the groundwork period is very accurate already. You could leave the estimated duration blank in this case. Estimated duration is an optional field. You can use this as a workaround for now.

**Comment by doomsju** [comment]
Available in release https://github.com/Informatievlaanderen/GIPOD/issues/150
