### ISSUE TITLE
Best way to get doc API changes pushed?

### ISSUE THREAD

**Issue by hixfield** [Informatievlaanderen/GIPOD#128]
**Context:**
We have been working on a GIPOD2 integration for approx 2 months.
Now and then we notice some "small" things changing, last time it was on the get project detail call where the geo region was now included in the response suddenly. This helped us because it ment one web service call less for us :)

**Question**
What would be the best way, that we can be notified of any changes (before hand)?
Do you have a mailing list? Perhaps RSS feed?

**Comment by olivermay** [comment]
All notifications about releases with release notes are done trough this repository, it acts as a mailinglist when you watch the repository. The changelog is included in the release announcements.

Two options:
1. Watch the Informatievlaanderen/GIPOD repository (warning, you will get notified of every issue)
![image](https://user-images.githubusercontent.com/4815604/94568031-53c3da80-026c-11eb-919e-580691517dc3.png)

2. Follow the announcement topic #114 (you will only get notified when we post announcements in that topic)
![image](https://user-images.githubusercontent.com/4815604/94568422-bf0dac80-026c-11eb-815b-0d0bb37d4d02.png)
