### ISSUE TITLE
Beschikbaar stellen Postman voorbeelden

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#13]
In de technische werkgroep van 16/01 werd aangegeven dat de Postman voorbeelden die werden getoond ook zouden worden gepubliceerd. Kunnen we deze al ergens terugvinden?

**Comment by olivermay** [comment]
Hi Berdien, 

we have postman examples, but indeed they still need to be added to the github repository. The team will be looking at that in the next couple of weeks.

cheers, 

Oliver

**Comment by berdienderoo** [comment]
Any news on this?

**Comment by hixfield** [comment]
Also interested for the postman examples. Any timing available?

**Comment by olivermay** [comment]
Hi Berdien and Geert, 

We had some discussion about this with the team, there are several options: 
1. Publishing the postman examples from the demo's is fairly easy, but there is no guarantee that they will keep working over time. Also the examples from the January TWG are outdated by now.
2. Another option is that we publish our postman integration tests, this is some work, but contains the most examples, but not documented. 
3. Finally we could provide a simple demo and example of the logging-in process and some simple requests. 
Note that there is also the swagger documentation that covers most, and is a lot like postman.

Therefore I would like to ask you the main goal of these postman examples? Is it getting started (security, some simple request),, examples of all requests, some specific use cases, ... something else. 

thanks for letting us know!

Oliver

**Comment by hixfield** [comment]
My motivation is to quickly get an insight in the API. So option (3) would probably cover my needs. But I think this could be a real valuable asset also for advanced users. Using e.g. folders in postman different use cases could be grouped going from basic auth to simple query to more advanced...

PS: I work a lot with postman and in my workflow I include a link to the confluence page in the postman call description. This works very nice.

**Comment by olivermay** [comment]
We created a small scenario on how to obtain a token to start playing with the swagger API, it's here on the confluence page: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1661796428/Using+Swagger+with+authentication

If you need examples of some requests, please ask!
