### ISSUE TITLE
Query on PublicDomianOccupency API. 

### ISSUE THREAD

**Issue by ebivarghese** [Informatievlaanderen/GIPOD#130]
in the API PublicDomianOccupency we are trying to filter out or fetch only the Ground Works Gipod ID.

API Name : /api/v1/public-domain-occupancies

There are many option for input parameter, can you please help us understand as which input parameter to be passed and what value to be used to fetch only the Ground works.

Currently we are only sending the Last modified Start and  Last modified end date.

**Comment by doomsju** [comment]
To fetch only groundworks you have to use query string parameter "typeid with value 718225ee-78e8-4b6f-bc63-7748cfd0a4d2.

This possible values for this parameter are available via the taxonomies api: api/v1/taxonomies/public-domain-occupancy/types
groundwork = api/v1/taxonomies/public-domain-occupancy/types/718225ee-78e8-4b6f-bc63-7748cfd0a4d2
