### ISSUE TITLE
Querry on trench-synergy-requests 

### ISSUE THREAD

**Issue by ebivarghese** [Informatievlaanderen/GIPOD#131]
**Current usage :**
We are consuming this API /api/v1/trench-synergy-requests to get the list of synergy request  GIPOD IDs 
later that we are using /api/v1/groundworks/{gipodId}/trench-synergy-requests/{trenchSynergyRequestId} to get the details of those GIPOD ids.

Query:
i have observed a particular element "lastModifiedOn" is present only in the Find API ( /api/v1/trench-synergy-requests ) 
is it possible to add "lastModifiedOn" in the above mentioned API ( /api/v1/groundworks/{gipodId}/trench-synergy-requests/{trenchSynergyRequestId}) ?

Note: 
Same Details is present in below 2 API:

1. /api/v1/groundworks/{gipodId}
2.  /api/v1/trench-synergies/{gipodId}

**Comment by doomsju** [comment]
We will add this to the response.

**Comment by doomsju** [comment]
Resolved in release #173
