### ISSUE TITLE
GET GW immediately followed by PATCH request comes up old values 

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#134]
Hello,

We have a use case to read (GET GW) the period start & end values from Gipod after they have been updated (PATCH GW). We notice that, if the GET GW is done after 1 second PATCH GW, Gipod platform (beta) returns values prior to the PATCH request.

We tried this several times today on this GW: https://new.beta.gipod.vlaanderen.be/innames/3684153 and the result is always the same.

Is this normal? Pls check & feedback.

Thanks & br.

**Comment by doomsju** [comment]
The read side of our API is "eventually consistent". This means that after a creation or update there can be some delay on the currrent state of the resource. In your particular case all results were available after 1600ms. We think to reduce this in staging/production.

We have a mechanism you can use to check if you get the latest state of a resource.
In the response of a POST/PUT/PATCH method a response header "ETAG" is available. The value of the ETAG is an indication of the latest version of the resource. If you do a get method on a resource you can add the value of the ETAG response header in the Request Header "If-Match". If the server cannot response with the expected (latest) version a HttpStatus Code 412 (Precondition Failed) will be returned. In this case you can retry until you get a HttpStatus 200 OK.

So you have to possibilities:
- increase the time before you get the details
- use the mechanism described with  headers ETAG, If-match

Hope this can help!

-

**Comment by rajeevchugh71** [comment]
Thanks for your response, we will check & feedback.

**Comment by rajeevchugh71** [comment]
@doomsju, In fact, we would still like to know if the changes done to solve #139 are also done to solve this issue (related to GW).

**Comment by doomsju** [comment]
No because the read-side, GET operations, is eventually consistent. Issue #139 is an issue on the write-side (POST, PUT, PATCH operations).
