### ISSUE TITLE
Questions concerning Signaling permit

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#135]
Could you tell us :
in which attribute we can find the approved period for the signaling permit ?
with API GET /api/v1/mobility-hindrances/{gipodId}/signaling-permits/{signalingPermitId}, 
 "period": {
    "@type": "string",
    "start": "2020-10-05T15:16:13.767Z",
    "end": "2020-10-05T15:16:13.767Z") ?

what are the different statuses we can expect to receive for a signalling permit ?

what is the relationship between a MobilityHindrance and a SignallingPermit : can there be only 1 SP for every MH or can there be more than 1 SP for every MH ? (see picture in attached)
![relationship MH - SP](https://user-images.githubusercontent.com/70695400/95096772-fe387380-072c-11eb-8b43-3f94c70b7af4.jpg)

Thanks

**Comment by doomsju** [comment]
The approved period is the period of the signaling permit.

**Comment by SilPal** [comment]
Can you also answer the other questions please ?
what are the different statuses we can expect to receive for a signalling permit ?
what is the relationship between a MobilityHindrance and a SignallingPermit : can there be only 1 SP for every MH or can there be more than 1 SP for every MH ? (see picture in attached)

**Comment by doomsju** [comment]
- Statuses for signaling permits are available via endpoint: /api/v1/taxonomies/statuses/bb5747d8-210b-4f98-853c-5a363c9ef203.

Available statuses: In Aanvraag, Vergund, Geweigerd

- A zero to many relationship is defined between mobility hindrance and signaling permit
