### ISSUE TITLE
Searchzone met Multipolygon

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#136]
Wanneer ik een searchzone wens aan te maken met een multipolygon wkt, dan krijg ik steeds badrequest terug.
Voorbeeld WKT in bijlage
[multipolygon.txt](https://github.com/Informatievlaanderen/GIPOD/files/5339999/multipolygon.txt)

**Comment by doomsju** [comment]
Er komt een hotfix hiervoor.

**Comment by doomsju** [comment]
A hotfix is deployed on Beta:
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2008023398/Hotfixes+0.10.x
