### ISSUE TITLE
Endpoint Remove Synergy

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#137]
Beste,

Er is al eens gevraagd geweest wanneer de endpoint voor een remove synergy ging gereleased worden.
Ik dacht dat er aangegeven was dat dit in de huidige versie aanwezig zou zijn, maar ik vind deze nergens terug?
Kan het zijn dat deze nog gereleased moet worden? Of dienen we op een andere manier een synergie te verwijderen?

groet,

**Comment by doomsju** [comment]
Dag Jan, 
We hebben dit verder bekeken en het verwijderen van een sleufsynergie zal niet mogelijk zijn. Indien een sleufsynergie niet zal doorgaan dan zal de status op "Niet-uitgevoerd" moeten worden gezet. Deze status zal binnenkort worden toegevoegd in de API. Dit was initieel zo opgenomen in het BC document.

**Comment by doomsju** [comment]
Available in release https://github.com/Informatievlaanderen/GIPOD/issues/150
