### ISSUE TITLE
negative answer trench synergy request after deadline1

### ISSUE THREAD

**Issue by ial565** [Informatievlaanderen/GIPOD#138]
Issue met /api/v1/groundworks/10212574/trench-synergy-requests/10212685

Na verstrijken van deadline1 wou ik nog een negatief antwoord sturen via 'Answer trench synergy request'.
Het gaat om Fluvius Site Brugge-Middenkust, 1 van de receivingOrganisation.
Ik kreeg foutmelding 'Organisation is not a participating organisation in the trench synergy request'. Vreemd.

Via de website kon ik wel de interesse beeindigen.
Is dit een bug? Of probeerde ik verkeerde handelingen?

**Comment by AIV-Bert** [comment]
Dag @ial565,

Gaf je de juiste Organisatie mee in de API, dus  Fluvius Site Brugge-Middenkust en **niet** je hoofdorganisatie?
Kan je dit nog reproduceren?

Alvast onze excuses voor het late antwoord.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Closed due to inactivity.
