### ISSUE TITLE
Returned GIPOD ID is not immediately usable for creating mobility hindrance

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#139]
**Describe the bug**
We create a work or event object in GIPOD² and immediately afterwards we want to create a mobility hindrance to this work/event.
Probably this is because of latency.

**Expected behavior**
If the ID of the newly created work/event is returned, then it should be immediately usable in the creation request of a mobility hindrance object.

**Comment by doomsju** [comment]
We noticed this issue and will solve this later.
You can solve this already by introducing a delay or retry mechanism. In normal circumstances it should work after max 2 sec. In most cases it's less than 1 sec.

**Comment by berdienderoo** [comment]
As discussed during the 'question time', this is an important and urgent issue for us. As it is also requested by anther party, I hope that this can have a higher priority.

**Comment by doomsju** [comment]
Hi Berdien, Will be resolved in the next release of the Beta API.

**Comment by berdienderoo** [comment]
@doomsju , thanks a lot!

**Comment by doomsju** [comment]
Resolved in Available in release https://github.com/Informatievlaanderen/GIPOD/issues/150

**Comment by langens-jonathan** [comment]
@doomsju Does this mean that this behavior will then also be resolved for ground works? Thanks for your prompt response!

**Comment by rajeevchugh71** [comment]
@doomsju, @langens-jonathan See #134 which details issue in ground works .
