### ISSUE TITLE
Difference between documentation and responses of API RegisterGroundwork

### ISSUE THREAD

**Issue by JeremyFluvius** [Informatievlaanderen/GIPOD#14]
We see a difference between documentation and responses of API RegisterGroundwork.
See below for 2 examples of responses we got.

{
  "Code": 400,
  "description": "The request is invalid",
  "errors": [
    {
      "field": "specificationTypeId[0]",
      "message": "Error converting value \"57438692-f1e3--a1c8-725f42b85f56\" to type 'System.Guid'. Path 'specificationTypeId[0]', line 1, position 966."
    }
  ]
}

{
  "code": 400,
  "message": "Validation failed",
  "errors": [
    {
      "field": "Period.Start",
      "message": "'Start' must be less than '08/22/2020 22:00:00'.",
      "code": "InvalidPeriod"
    }
  ]
}

**Comment by doomsju** [comment]
The first response indicates something is wrong in the structure or content of the request body. In this case an invalid value provided in an field.

The second response indicates that a business rule is violated. In this case an invalid period.

We will improve the error responses and documentation.
