### ISSUE TITLE
Gipod² Beta ids <> Gipod1 productie ids

### ISSUE THREAD

**Issue by svanrintel** [Informatievlaanderen/GIPOD#140]
We merken dat de GIPOD ID's in GIPOD² Beta niet overeenkomen met de ID's uit Gipod1 productie.
Is dit enkel het geval in de beta omgeving? Heeft Staging dit probleem niet aangezien deze in sync staat met Gipod1 productie?

Is er een mogelijkheid de ID's in beta toch te updaten met relevante ID's uit gipod1?

**Comment by vmateiaiv** [comment]
Hi @svanrintel,

Wat u merkt is normaal. De data van onze BETA omgeving is niet gelijk met de data van STAGING en PROD.
STAGING is wel gelijk met PROD.

Mvg,

Voicu Matei
AIV

**Comment by svanrintel** [comment]
Bedankt voor de verduidelijking.
