### ISSUE TITLE
pointOnSurface property in /groundworks/#id call

### ISSUE THREAD

**Issue by svanrintel** [Informatievlaanderen/GIPOD#141]
We gebruiken de `/public-domain-occupancies` endpoint om een lijst op te halen van groundworks. Met deze lijst vullen we een queue op die later in de achtergrond wordt verwerkt.

Tijdens het verwerken van een item in de queue doen we een request naar de `/groundworks/#id ` endpoint om de details op te halen en deze te verwerken.
Echter hebben we op dit moment nog het veld `pointOnSurface` uit de `/public-domain-occupancies` endpoint nodig. Dit veld is niet beschikbaar in `/groundworks/#id ` terwijl deze ook bij de details van een groundwork hoort. Momenteel zijn we genoodzaakt opnieuw een request te doen naar `/public-domain-occupancies`.

Is het mogelijk dit veld in de data set toe te voegen?

**Comment by svanrintel** [comment]
@doomsju Wanneer zou dit toegevoegd kunnen worden?

**Comment by doomsju** [comment]
Dit komt mee in de volgende Beta release.

**Comment by doomsju** [comment]
Resolved in release #173
