### ISSUE TITLE
Cancel of an executed GW

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#142]
**Describe the bug**
When we cancel an executed GW with API, GIPOD doesn't throw an error. example : GW 10212829

**Expected behavior**
When trying to cancel an executed GW, GIPOD should throw an error.

**Additional context**

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by doomsju** [comment]
Ask discussed on the GIPOD question hour there is no check on the status when deleting a GW.
