### ISSUE TITLE
How can I find newly created TSR

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#145]
The parameters lastmodified.start and lastmodified.end, do they also take into account creation date of the entities?

The result of the operations /api/v1/trench-synergy-requests and /api/v1/entities does not have the same amount of members when I use the same values for lastmodified.start and lastmodified.end parameters. Is this an expected behaviour?

**Comment by olivermay** [comment]
Can you provide the specific parameters where you find the difference? Is this on beta?

**Comment by jdewilde** [comment]
Yes, I did some test on beta.

Filter on date 2020-10-13 08:06 until 2020-10-13 12:00
![image](https://user-images.githubusercontent.com/4618566/95847224-c0e76d80-0d4c-11eb-97ce-56cd627fd79d.png)

​/api​/v1​/trench-synergy-requests: 10 results
/api/v1/entities: 9 results

Can you also respond to my question about the lastmodified filter property, does it also searches on newly created items (for all search calls)?

**Comment by doomsju** [comment]
The lastmodified filter searches also on newly created items. After creation lastmodifiedon = createdon.
We will investigate further the changes in the result count.

**Comment by jdewilde** [comment]
I've noticed that the check on last modified date is done on UTC time, is this the expected behaviour?

**Comment by doomsju** [comment]
Yes, Api is expecting datetimes in UTC

**Comment by doomsju** [comment]
Resolved in release #173
