### ISSUE TITLE
not possible to remove "samenwerkingszone"

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#146]
**Describe the bug**
Organisation Proximus has a "samenwerkingszone" that needs to be removed. When removing GIPOD UI throws an error 
"One or more validation errors occurred.
The specified condition was not met for 'Zone'. (Zone)"
and the zone can not be removed.

**Expected behavior**
It has to be possible to remove an existing "samenwerkingszone" 

**Additional context**

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by AIV-Bert** [comment]
Hi @SilPal 

Removing a collaborationzone is not planned for release 1 of the Gipod API.

As the UI is just an integrator, we can't support the removal of collaborationzone either.

As a work around you can make a small zone outside of Flanders. 
Example: **POLYGON((14300 222000,14200 221000,14500 223000,14300 222000))**

Kind regards,

Bert
