### ISSUE TITLE
Create GW for organisation Green doesn't work in UI

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#147]
**Describe the bug**
When creating a new GW for organisation Green, I get an error message on the last (contact) tab 
![2020-10-13 13_36_15-Start](https://user-images.githubusercontent.com/70695400/95855838-58eb5400-0d59-11eb-8c5c-6a27a45903db.jpg)

The drawn GW zone :
![image](https://user-images.githubusercontent.com/70695400/95859978-b1255480-0d5f-11eb-8fdd-e8c627050afe.png)

I can't go back to a previous screen and the GW isn't created. No red zone visible on the contact screen.
Can you check please ?

I think it has something to do with the **form** of the drawn polygon. I retried with a simple polygone and this worked.

**Comment by AIV-Bert** [comment]
Hi @SilPal,

This is correct behavior. The shape of your polygon is not allowed. The sides shouldnot cross each other.

Kind regards,

Bert
