### ISSUE TITLE
Veiligheidscoördinatoren verwijderen bij overdracht piloot

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#148]
Hallo,

Enkele vragenuurtjes geleden was er gesproken over de veiligheidscoördinatoren op de synergie.   Er was overeengekomen dat,bij overdracht van piloot, de veiligheidscoördinatoren er afgehaald gingen worden.   Momenteel lijkt dit nog niet te werken.  Voor wanneer is die aanpassing voorzien ?

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Dit is opgenomen in de backlog.

**Comment by doomsju** [comment]
Dit is ontwikkeld en komt mee in de volgende Beta release.

**Comment by doomsju** [comment]
Resolved in release #173
