### ISSUE TITLE
Gipod API endpoint in PROD

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#149]
Hello, 

Like we have Gipod API endpoint in BETA: https://api-gateway.beta.gipod.vlaanderen.be/, could you pls let us know the endpoint in PROD?

So that we can prepare for the connection setup between Proximus apps to Gipod PROD.

Thanks & br.

**Comment by AIV-Bert** [comment]
Hi @rajeevchugh71,

The most up-to-date endpoints for the different environments are:

- Beta: https://private-api.gipod.beta-vlaanderen.be/
- Staging: https://private-api.gipod.staging-vlaanderen.be/
- production: https://private-api.gipod.vlaanderen.be/

Kind regards,

Bert

**Comment by rajeevchugh71** [comment]
Thanks a lot Bert !
