### ISSUE TITLE
Userbeheer Gipod²

### ISSUE THREAD

**Issue by MariekeFluvius** [Informatievlaanderen/GIPOD#15]
Beste, nog enkele vragen over suborganisaties en certificaten...

- Kunnen we ervoor zorgen dat een grondwerk, geregistreerd door een hoofdorganisatie (bv. Fluvius), in het portaal toch terechtkomt in een suborganisatie (bv. Fluvius A)? En doen we dat dan door bv. bij de registerGroundwork een concrete ContactOrganisation (/RoleID?) mee te geven? bv.
   "contactOrganisation": [
   { 
   "organisationId": "FluviusA",
   "roleId":   ….

- Als iemand naar het portaal gaat: krijgt die dan alle werken en meldingen van enkel zijn suborganisatie te zien? Blijft dat systeem van claims gelden?
bv: User = GipodRaadpleger + GipodFluviusA --> kan enkel alle werken, sleuven en instellingen bekijken binnen interessezone Fluvius A.

- Is het nog steeds zo dat iemand die naar het portaal gaat, eerst wordt gecheckt op de Geosecure en dan terug wordt doorverwezen naar de juiste app met zijn betrokken "rol"?

- Momenteel hebben we 1 testuser op Beta Gipod² met self-signed certificaat dat geldig is t.e.m. 2039. Zal dat voor productie-users ook zo werken?

Hartelijk dank!
Marieke

**Comment by doomsju** [comment]
Dag Marieke,

Vandaag hebben we een nieuwe versie van de API gereleased: https://github.com/Informatievlaanderen/GIPOD/issues/16

Bij registreren van een grondwerk dient men nu verplicht een "OwnerId" mee te geven. Dit is de id van een organisatie binnen de organisatiestructuur van de geautoriseerde gebruiker. Ben je bijvoorbeeld ingelogd als hoofdorganisatie Fluvius dan kan je hier de Id meegeven van hoofdorganisatie of de id van een suborganisatie. De ids van een organisatie kan je vinden via dit endpoint "GET api/v1/organisations".

Momenteel zijn we bezig met de ontwikkeling van het portaal. Het is de bedoeling dat je daar default een zicht zou krijgen relevante zaken voor je eigen organisatie. Maar dit moet wel nog verder uitgewerkt. Inloggen op het portaal is nog steeds via GeoSecure.

met vriendelijke groeten,
GIPOD-team.
