### ISSUE TITLE
OAuth admin site of GIPOD II Staging env

### ISSUE THREAD

**Issue by SnehalataCh** [Informatievlaanderen/GIPOD#153]
Dear,

We need to test GIPOD staging APIs from our side.
We received the swagger document link for staging env.

But can you please provide us the link of OAuth admin site of GIPOD Staging env, where we need to upload client certificate to obtain the JWT token.

Ex: for Beta env we have OAuth admin site as: https://beta.oauth.vlaanderen.be/admin/

**Comment by AIV-Bert** [comment]
Hi @SnehalataCh,

The link of OAuth admin site for **Staging** AND **Production** is:
https://oauth.vlaanderen.be/admin/

Kind regards,

Bert
