### ISSUE TITLE
Can `null`s be removed from arrays of strings?

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#154]
When querying for Work/Groundworks that were originally created in Gipod1 and now synced in Gipod2 (staging), we get anoying null values in string arrays:

```
GET /api/v1/groundworks/7313681

...
"url": [
    null
],
...

See x-correlation-id: 79dc834d-8960-4977-9186-0613b36e2e73 
```

Similar for a Work: GET /api/v1/works/8742829 -> x-correlation-id: a3a647d4-ccac-48fb-979d-eeed890816cd

Is there an option on your side to filter these nulls out ?

**Comment by AIV-Bert** [comment]
Hi @ireactsam,

We will filter out these values. You can expect a bugfix in the 0.12.0 release.

Kind regards,

Bert
