### ISSUE TITLE
OrganisationId or OrganisationName must be a non null value

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#155]
**Describe the bug**
When making a call to add an contact organisation to a ground work in GIPOD. The API consistently returns a HTTP 400 Error if the payload contains null for the OrganisationId and the OrganisationName. When reading the documentation: https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/AddGroundworkContactOrganisation both strings appear nullable and the organisationname can only be non null if the organisation is null. It is however impossible to create a contactorganisation with only the role and the email address.

**Expected behavior**
A POST call to ../groundworkid/contactorganisations without a OrganisationId or an OrganisationName is accepted.

**Comment by AIV-Bert** [comment]
Hi @langens-jonathan,

When creating any ContatOrganisation either the OrganisationName or the OrganisationId should be provided. If both are null or both are supplied you will receive a HTTP 400 error.

Extract of the documentation:
> The name of a organisation. The organisation name can be passed instead of the organisation id if the organisation is unknown in gipod.

We prefer you pass the OrganisationId, but when it the organisationid is not an option, you can provide the organisationName as a fallback.

Hope answers your question.

Kind regards,

Bert

**Comment by rajeevchugh71** [comment]
Hi Bert,

Requesting you to provide an answer on this promptly as we need this info for our design/development in Proximus.

Thanks for your understanding & br.

**Comment by AIV-Bert** [comment]
Hi @langens-jonathan,
Hi @rajeevchugh71,

I can no longer reproduce this issue. When creating a ContactOrganisation either the OrganisationId or the OrganisationName should be filled in. But not both. When both are null you should get an error.

**OrganisationId is supplied (prefered)**
```
{
  "contactOrganisation": {
    "organisationId": "some _GUID_ or _UUID_",    
    "roleId": "a55eb0a5-84fb-49f8-83c5-de669e4ae48e",
    "isPublic": false,
    ...
  }
}
```

**OrganisationName is supplied**
```
{
  "contactOrganisation": {
    "organisationName": "some _String_",    
    "roleId": "a55eb0a5-84fb-49f8-83c5-de669e4ae48e",
    "isPublic": false,
    ...
  }
}
```

Kind regards,

Bert
