### ISSUE TITLE
is the GIPOD2 beta release finished ?

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#156]
I can't login to GIPOD2 beta. Is the release still ongoing ?

Thanks & best regards,
Silvie

**Comment by doomsju** [comment]
Release is finished. Normally there was no downtime.  Url of the web application: https://new.beta.gipod.vlaanderen.be/

**Comment by SilPal** [comment]
I already cleared my cookies. closed browser, but I still can't login. 3 dots at the upper right side of the screen instead of my name
![2020-10-15 20_37_11-Start](https://user-images.githubusercontent.com/70695400/96172262-70c40300-0f26-11eb-9fbd-4b9137a2c111.jpg)

**Comment by SilPal** [comment]
closed this issue but should still be open

**Comment by ireactsam** [comment]
I have the same issue, the UI is different, but just stays empty
![image](https://user-images.githubusercontent.com/29482028/96249323-52551a80-0fad-11eb-8c44-8461f139a698.png)

**Comment by ireactsam** [comment]
oh... now it works

**Comment by AIV-Bert** [comment]
@ireactsam ty for the follow up.
@SilPal can you confirm your issue is resolved?
