### ISSUE TITLE
Bij aanmaken nieuwe inname op GUI : toevoegen contact dossierbeheerder

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#157]
Bij het aanmaken van een nieuwe inname kom ik de stap contact niet verder :
zie opgeladen image

**Expected behavior**
Ik weet niet wat ik mogelijks verkeerd doe, de foutmelding is niet duidelijk.

![nieuweinname_contact_foutmeldingonduidelijk_16102020](https://user-images.githubusercontent.com/47108018/96220558-38a1dc00-0f89-11eb-96cc-a38d49a3f889.jpg)

**Additional context**

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by doomsju** [comment]
Dag Jan, Er komt hier vandaag een hotfix voor.

**Comment by doomsju** [comment]
Dit zou ondertussen in orde moeten zijn. Kan je even nakijken?
