### ISSUE TITLE
Gipod Beta : GUI aanmaken nieuwe synergieaanvraag button werkt niet

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#158]
Ik wil een nieuwe synergieaanvraag aanmaken en lanceren maar dit lukt niet. Als ik op de button druk dan doet deze niks.
In de status van de GUI ontwikkelingen zou dit op 'beta' staan?

Zie image
![AanmakenNieuweSynergieaanvraag](https://user-images.githubusercontent.com/47108018/96221720-5112f600-0f8b-11eb-9996-2e8f5b60ebd0.jpg)

Daarnaast merk ik dat als een grondwerk aan gemaakt is er vanuit dit grondwerk dan geen synergieaanvraag kan gelanceerd worden? Is dit correct?

**Expected behavior**
Als ik op de button nieuwe synergieaanvraag duw kan ik een nieuwe synergieaanvraag maken.

Daarnaast denk ik dat het handig is om vanuit een grondwerk dadelijk ook een synergieaanvraag zou moeten kunnen gelanceerd worden.

**Additional context**

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by AIV-Bert** [comment]
Dag @JanDegroote,

Het klopt dat de knop 'Nieuwe synergieaanvraag" niet werkt. We gaan deze knop verwijderen. 

Momenteel moet een synergyaanvraag steeds vanuit een grondwerk gestart worden. In het detail van een grondwerk kan je kiezen om "samenwerking te zoeken". Daar maak je een synergyaanvraag aan.
![image](https://user-images.githubusercontent.com/55388892/96222611-e2369c80-0f8c-11eb-8521-ef4378ba39e5.png)

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
> Daarnaast merk ik dat als een grondwerk aan gemaakt is er vanuit dit grondwerk dan geen synergieaanvraag kan gelanceerd worden? Is dit correct?

Kan je meer info geven hierover? Ik kan dit niet reproduceren.

**Comment by AIV-Bert** [comment]
Button will be removed in GUI Beta release 0.9.0

Issue afgesloten wegens geen verdere reactie.
