### ISSUE TITLE
Gemeente/municipality is missing compared to current GIPOD

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#161]
"Gemeente" is available in the current GIPOD werkopdracht and it's also available as selection criteria on the main screen of the GUI. 

GIPOD2 doesn't seem to have it anymore (missing in both interface and GUI). For people at municipality level it's probably nice to be able to filter only on their area of responsibility.

**Comment by AIV-Bert** [comment]
Hi @sboden,

You will be able to filter the different searches on municipality in the GUI. This will be added in one of the upcomming UI releases.

Kind regards,

Bert

**Comment by sboden** [comment]
Would it be possible to also add it to the interface? The current GIPOD(1) interface has a "NIS code", which is translated to municipality on our side. 

Use case: in hinderpremie besides informing the impacted enterprises, representatives of the municipality are informed about the hindrances.

**Comment by AIV-Bert** [comment]
For the current release this won't be available in the /groundworks API call.

If you want to search and filter on a specific City/Postalcode, the search endpoints support filtering on Niscode.

If you want to reverse geocode the zone, you can use this API: https://loc.geopunt.be
