### ISSUE TITLE
Error regarding mobility hindrance consequence on creation of mobility hindrance object

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#163]
We perform a post call to register a new mobility hindrance object with one zone and one consequence.

The call returns a 400 error regarding the mobility hindrance consequence: "The specified condition wat not met for 'Mobility Hindrance Consequences'.". 
Can you help us to see what's wrong?

We used the following endpoint: POST https://api-gateway.beta.gipod.vlaanderen.be/api/v1/mobility-hindrances
With the following body: {"ownerId":"0201f2a2-39e6-0a88-b5a3-c912f52a9a93","reference":null,"description":null,"statusId":null,"contactOrganisation":[{"public":false,"@id":null,"@type":null,"preferredName":null,"organisationId":"0201f2a2-39e6-0a88-b5a3-c912f52a9a93","organisationName":null,"roleId":"aad5e947-f7bf-4592-a84a-f591555b0b8b","website":null,"contactName":null,"telephone":null,"fax":null,"email":"helpdesk@geosparc.com","isPublic":false}],"publicDomainOccupancyTypeId":null,"period":[{"@type":null,"start":"2020-11-02T22:00Z","end":"2020-11-06T21:59Z"}],"timeSchedule":null,"isConsequenceOfId":[10213768],"mobilityHindranceZone":[{"zoneType":"0fb72ef7-6ac9-4a70-b295-a30ea215d250","wkt":"POLYGON ((104482.8648775313 194128.27879615035, 104488.37576833386 194128.23066594265, 104488.39758627486 194130.728963417, 104482.88669811696 194130.77709360234, 104482.8648775313 194128.27879615035))","mobilityHindranceConsequence":["ccb7b02b-94e0-4900-9188-a80e9f47637e"]}]}

**Comment by vmateiaiv** [comment]
Hi @berdienderoo,

The id you are using for consequence type is a valid one, but it belongs to an item which has children (in the tree structure of the 
 mobility hindrance consequence type taxonomy).

![image](https://user-images.githubusercontent.com/55380575/96432056-a7d73480-1204-11eb-97e7-401431ef6161.png)

At the moment we only allow mobilityHindranceConsequence type ids of elements without children. If you would like to specify "+ 3,5 ton verboden" and "+ 7,5 ton verboden" as mobilityHindranceConsequences, you would have to specify a list of mobilityHindranceConsequence type ids, namely 

```
"mobilityHindranceZone": [
        {
            "zoneType": "0fb72ef7-6ac9-4a70-b295-a30ea215d250",
            "wkt": "POLYGON ((104482.8648775313 194128.27879615035, 104488.37576833386 194128.23066594265, 104488.39758627486 194130.728963417, 104482.88669811696 194130.77709360234, 104482.8648775313 194128.27879615035))",
            "mobilityHindranceConsequence":  ["d0dbf2dd-b9bf-4d7a-b0ca-806f1ba4795a", "5f0e22e9-0554-4e56-82bd-69440a01827c"]
        }
    ]
```

Kind regards,
Voicu Matei
AIV

**Comment by vmateiaiv** [comment]
Dear @berdienderoo,

The validation message will be improved in the following release, so that it's clear what is expected.

Kind regards,
Voicu Matei
