### ISSUE TITLE
2 verschillende niet aaneensluitende interessegebieden bij 1 sub organisatie

### ISSUE THREAD

**Issue by JeremyFluvius** [Informatievlaanderen/GIPOD#164]
Het interesse gebied voor Fluvius site Hasselt bestaat uit het grondgebied rond Hasselt en dat van Voeren. Het gaat om twee aparte polygonen (zie printscreen ![Regio Hasselt Gipod Productie](https://user-images.githubusercontent.com/62639988/96471429-a0795080-122f-11eb-8cee-a9a6dcaa86ba.png)

De WKT uit GIPOD productie werd geëxporteerd. Beide polygonen worden gescheiden door POLYGON((*),(*)).
[WKT Regio Hasselt Gipod Productie.txt](https://github.com/Informatievlaanderen/GIPOD/files/5402938/WKT.Regio.Hasselt.Gipod.Productie.txt)

Deze WKT werd gebruikt om via swagger de interessezone in te teken in GIPOD² staging.
![Regio Hasselt Gipod² staging](https://user-images.githubusercontent.com/62639988/96471431-a111e700-122f-11eb-9f51-0e21738613f5.png)

De polygoon rond het grondgebied Voeren is hierbij niet zichtbaar, en dus ook niet aangemaakt. 
Ondanks een identieke WKT file werd gebuikt, is het resultaat tussen GIPOD productie en GIPOD² staging niet identiek.
Kan dit bekeken worden aub.

**Comment by doomsju** [comment]
GeometryCollection is niet gesupporteerd. Enkel Polygon of MultiPolygon zijn gesupporteerd.

**Comment by AIV-Bert** [comment]
Hier een voorbeeld hoe de zone te definiëren.

[WKT.Regio.Hasselt.Gipod.MULTIPOLYGON.txt](https://github.com/Informatievlaanderen/GIPOD/files/5403097/WKT.Regio.Hasselt.Gipod.MULTIPOLYGON.txt)

**Comment by doomsju** [comment]
We zullen nog bekijken hoe we dit via de validatie van de zon in de API nog kunnen verbeteren.
