### ISSUE TITLE
GET /api/v1/trench-synergy-requests-to-be-answered geeft resultaten van alle suborganisaties

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#166]
Hallo,

Bij het uitvoeren van bovenstaande API voor één of meerdere suborganisaties (vb Fluvius Hasselt en Fluvius Dilbeek) krijgen we teveel resultaten, namelijk voor alle suborganisaties die onder de hooforganisatie van Fluvius valt.

Verwacht resultaat is dat enkel de SSA aanvragen worden teruggeven die onder de suborganisaties vallen die meegegeven werden aan de API.

Kunnen jullie dit fixen ?

Mvg,
Bert De Groote

**Comment by AIV-Bert** [comment]
Dag @hij242,

Ik kan dit niet reproduceren. HEt resultaat van de volledige organisatie is het default gedrag wanneer je geen id's meegeeft.

Ik vermoed dat er ergens een fout in de request zit, waardoor de API terugvalt op het default gedrag. Kan je een voorbeeld geven van jouw request?

Met vriendelijke groeten,

Bert

**Comment by hij242** [comment]
Bert,

Heb dit nog eens nagekeken en blijkbaar zit het probleem op onze SAP PO want vanuit de swagger krijg ik wel het juiste resultaat.  Excuses.

Mvg,
Bert De Groote
