### ISSUE TITLE
Remove GW from SSYN in UI

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#167]
**Describe the bug**
logged in as Bijdrager Blauw, I removed a Fluvius GW 10213571 from SSYN 10213601. This GW was in a total other part of the country and thus preventing me from seeing the SSYN zone on the map.
After removal of the Fluvius GW, I transferred the pilot to Proximus 2.2.
Refreshing the SSYN screen in UI keeps on showing the Fluvius GW (see attached)
![2020-10-21 16_08_20-Start](https://user-images.githubusercontent.com/70695400/96732225-62f3ff00-13b8-11eb-907b-66be007cf1e2.png)

**Expected behavior**
Fluvius GW no longer visible on SSYN map. 2 other GW visible.

**Comment by AIV-Bert** [comment]
Hi @SilPal

The green zone on the map is the SSYN zone. Removing a groundwork will not automatic update the SSYN zone.
"Blauw" should update the SSYN zone.

Expected behavior --> Current behavior
Fluvius GW no longer visible on SSYN map. 2 other GW visible.

Kind regards,
Bert
