### ISSUE TITLE
Urgent Question: Pent test: GIPODII : Need confirmation if Pen test was done on GIPODII

### ISSUE THREAD

**Issue by ShashiMis** [Informatievlaanderen/GIPOD#168]
Dears,

This is not a bug but I need a confirmation if PEN test has already been done for GIPODII.
If yes can you provide the results.

IF not We need an approval if Pen test team can do a Pen test on GIPODII ?
If Yes Pen test team needs authentication to access the API and URL for Pen testing GIPODII

Regards,
Shashi

**Comment by doomsju** [comment]
This will be taken up by our internal security team probably in november.

**Comment by ShashiMis** [comment]
Hello,

Can you pls confirm me the dates as I need to inform the Proximus Pen test team to align on the results accordingly?

Best Regards,
Shashi Mishra
-----------------------------------------------------------------------------------------------------------------------
Bye bye Quality Center. Welcome Xray/JIRA!  More info on Move from QCT 2 JIRA- XRAY<https://wap.proximus.com/docs/DOC-80362>
Looking for (test) automation?  Contact our Automation Center of Excellence Team<https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team>
-----------------------------------------------------------------------------------------------------------------------
Key Dates to Mark:
Test Data Management / IPTS (Nov 25th)<https://wap.proximus.com/events/8053>
Test Automation (Dec 9th)<https://wap.proximus.com/events/8078>
UTAF Test Automation Framework (Dec 16th) <https://wap.proximus.com/events/8087>

Test Manager | ITS-DES Test Management & Execution
M +32 (0)465 57 53 64

Planned Leave:
Bld du Roi Albert II 27, B-1030 Brussels
www.proximus.be<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212204895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FhkkORa%2BRcQVY%2FXbMgwSQ3pOzRPQHdCeMh3FofFy%2Bwg%3D&reserved=0>

Testing on WAP: https://wap.proximus.com/groups/testing-at-proximus

Test Automation on WAP: https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team

[Proximus]<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aYLexFJexMlKilMiIrH6nSm8u1aH%2BkEcDpaJAEQwrPQ%3D&reserved=0>

Connect with us on:

[Proximus Facebook]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FproximusBe&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YxOqS34K4J6TCitO56nFxrLUBdWibumcl8aKIKVMT8Q%3D&reserved=0>   [Proximus Twitter] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3i0d1BfRaTNDtIvanACH62LZA3%2B5K1EhoPvI0LqvYQM%3D&reserved=0>    [Proximus YouTube] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JzLPE14DJic%2FovQWXAeTNhvYIjOYqbUTAVYESyLDxsU%3D&reserved=0>    [Proximus LinkedIn] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212234874%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sB%2BbcBazFDH%2FEbuZBiall0vYj0Eo%2BQIv37WyCrHIVUI%3D&reserved=0>

**Comment by ShashiMis** [comment]
Dears,

We are nearing to end of the release and we are in middle of November.
Can you pls let me know if Pen test already started or not?

Also pls let me know the scope of your Pen test. Is it limited to GUI or you shall Pen test the APIs as well?

Best Regards,
Shashi Mishra
-----------------------------------------------------------------------------------------------------------------------
Bye bye Quality Center. Welcome Xray/JIRA!  More info on Move from QCT 2 JIRA- XRAY<https://wap.proximus.com/docs/DOC-80362>
Looking for (test) automation?  Contact our Automation Center of Excellence Team<https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team>
-----------------------------------------------------------------------------------------------------------------------
Key Dates to Mark:
Test Data Management / IPTS (Nov 25th)<https://wap.proximus.com/events/8053>
Test Automation (Dec 9th)<https://wap.proximus.com/events/8078>
UTAF Test Automation Framework (Dec 16th) <https://wap.proximus.com/events/8087>

Test Manager | ITS-DES Test Management & Execution
M +32 (0)465 57 53 64

Planned Leave:
Bld du Roi Albert II 27, B-1030 Brussels
www.proximus.be<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212204895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FhkkORa%2BRcQVY%2FXbMgwSQ3pOzRPQHdCeMh3FofFy%2Bwg%3D&reserved=0>

Testing on WAP: https://wap.proximus.com/groups/testing-at-proximus

Test Automation on WAP: https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team

[Proximus]<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aYLexFJexMlKilMiIrH6nSm8u1aH%2BkEcDpaJAEQwrPQ%3D&reserved=0>

Connect with us on:

[Proximus Facebook]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FproximusBe&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YxOqS34K4J6TCitO56nFxrLUBdWibumcl8aKIKVMT8Q%3D&reserved=0>   [Proximus Twitter] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3i0d1BfRaTNDtIvanACH62LZA3%2B5K1EhoPvI0LqvYQM%3D&reserved=0>    [Proximus YouTube] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JzLPE14DJic%2FovQWXAeTNhvYIjOYqbUTAVYESyLDxsU%3D&reserved=0>    [Proximus LinkedIn] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212234874%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sB%2BbcBazFDH%2FEbuZBiall0vYj0Eo%2BQIv37WyCrHIVUI%3D&reserved=0>



Sensitivity: Internal Use Only
From: MISHRA Shashi (ITS/DES)
Sent: 30 October 2020 11:45
To: Informatievlaanderen/GIPOD <reply@reply.github.com>; Informatievlaanderen/GIPOD <GIPOD@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Informatievlaanderen/GIPOD] Urgent Question: Pent test: GIPODII : Need confirmation if Pen test was done on GIPODII (#168)

Hello,

Can you pls confirm me the dates as I need to inform the Proximus Pen test team to align on the results accordingly?

Best Regards,
Shashi Mishra
-----------------------------------------------------------------------------------------------------------------------
Bye bye Quality Center. Welcome Xray/JIRA!  More info on Move from QCT 2 JIRA- XRAY<https://wap.proximus.com/docs/DOC-80362>
Looking for (test) automation?  Contact our Automation Center of Excellence Team<https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team>
-----------------------------------------------------------------------------------------------------------------------
Key Dates to Mark:
Test Data Management / IPTS (Nov 25th)<https://wap.proximus.com/events/8053>
Test Automation (Dec 9th)<https://wap.proximus.com/events/8078>
UTAF Test Automation Framework (Dec 16th) <https://wap.proximus.com/events/8087>

Test Manager | ITS-DES Test Management & Execution
M +32 (0)465 57 53 64

Planned Leave:
Bld du Roi Albert II 27, B-1030 Brussels
www.proximus.be<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212204895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FhkkORa%2BRcQVY%2FXbMgwSQ3pOzRPQHdCeMh3FofFy%2Bwg%3D&reserved=0>

Testing on WAP: https://wap.proximus.com/groups/testing-at-proximus

Test Automation on WAP: https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team

[Proximus]<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aYLexFJexMlKilMiIrH6nSm8u1aH%2BkEcDpaJAEQwrPQ%3D&reserved=0>

Connect with us on:

[Proximus Facebook]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FproximusBe&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YxOqS34K4J6TCitO56nFxrLUBdWibumcl8aKIKVMT8Q%3D&reserved=0>   [Proximus Twitter] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3i0d1BfRaTNDtIvanACH62LZA3%2B5K1EhoPvI0LqvYQM%3D&reserved=0>    [Proximus YouTube] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JzLPE14DJic%2FovQWXAeTNhvYIjOYqbUTAVYESyLDxsU%3D&reserved=0>    [Proximus LinkedIn] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212234874%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sB%2BbcBazFDH%2FEbuZBiall0vYj0Eo%2BQIv37WyCrHIVUI%3D&reserved=0>

**Comment by doomsju** [comment]
Pen testing is on UI and API. 
This is in progress and results will be available end of november.

**Comment by ShashiMis** [comment]
Hello,

As we have the release on 26/11. Will it be possible to send the final results by 18/11?

Best Regards,
Shashi Mishra
-----------------------------------------------------------------------------------------------------------------------
Bye bye Quality Center. Welcome Xray/JIRA!  More info on Move from QCT 2 JIRA- XRAY<https://wap.proximus.com/docs/DOC-80362>
Looking for (test) automation?  Contact our Automation Center of Excellence Team<https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team>
-----------------------------------------------------------------------------------------------------------------------
Key Dates to Mark:
Test Data Management / IPTS (Nov 25th)<https://wap.proximus.com/events/8053>
Test Automation (Dec 9th)<https://wap.proximus.com/events/8078>
UTAF Test Automation Framework (Dec 16th) <https://wap.proximus.com/events/8087>

Test Manager | ITS-DES Test Management & Execution
M +32 (0)465 57 53 64

Planned Leave:
Bld du Roi Albert II 27, B-1030 Brussels
www.proximus.be<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212204895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FhkkORa%2BRcQVY%2FXbMgwSQ3pOzRPQHdCeMh3FofFy%2Bwg%3D&reserved=0>

Testing on WAP: https://wap.proximus.com/groups/testing-at-proximus

Test Automation on WAP: https://wap.proximus.com/groups/testing-at-proximus/blog/2019/09/16/automation-center-of-excellence-team

[Proximus]<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.proximus.be%2F&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aYLexFJexMlKilMiIrH6nSm8u1aH%2BkEcDpaJAEQwrPQ%3D&reserved=0>

Connect with us on:

[Proximus Facebook]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FproximusBe&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212214888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YxOqS34K4J6TCitO56nFxrLUBdWibumcl8aKIKVMT8Q%3D&reserved=0>   [Proximus Twitter] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3i0d1BfRaTNDtIvanACH62LZA3%2B5K1EhoPvI0LqvYQM%3D&reserved=0>    [Proximus YouTube] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212224881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JzLPE14DJic%2FovQWXAeTNhvYIjOYqbUTAVYESyLDxsU%3D&reserved=0>    [Proximus LinkedIn] <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fproximus&data=04%7C01%7Cshashi.mishra.ext%40proximus.com%7C38bdc3b26237421a13ba08d87660fc6c%7Ce7ab81b21e844bf79dcbb6fec01ed138%7C0%7C0%7C637389506212234874%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sB%2BbcBazFDH%2FEbuZBiall0vYj0Eo%2BQIv37WyCrHIVUI%3D&reserved=0>

**Comment by doomsju** [comment]
The tests are busy and a report should be written. We cannot send final results for the moment.

**Comment by AIV-Bert** [comment]
The results will be sent to your email.
