### ISSUE TITLE
Creating a work throws error on description

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#169]
**Describe the bug**
When creating a work (post /works) and not posting a description, we get the following error:
status":400,"detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:NullOrEmptyValue","title":"'Description' must not be empty.","detail":"Description"}]}

The description is not required, so strange that this error occurs.

Can you help us?

**Comment by AIV-Bert** [comment]
Hi @berdienderoo,

I cannot reproduce this.
I imagine you are trying to create an _event_ without description. If this is not the case, could you provide your request body and the correlationId of your request?

Kind regards,

Bert

**Comment by berdienderoo** [comment]
@AIV-Bert , sorry for the confusion. We indeed register an event. I wasn't aware that the description was required for events. I thought it wasn't as is the case for work objects.
