### ISSUE TITLE
Urgent issue - Synergierequest didn't transfer into synergie after second deadline

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#170]
**Describe the bug**
Synergierequest didn't transfer into synergie after second deadline

**Expected behavior**
after second deadline synergy is created automatically

https://new.beta.gipod.vlaanderen.be/synergieaanvraag/10213958
https://new.beta.gipod.vlaanderen.be/synergieaanvraag/10213960
https://new.beta.gipod.vlaanderen.be/synergieaanvraag/10213964

**Comment by TomasVerheyen** [comment]
https://new.beta.gipod.vlaanderen.be/synergieaanvraag/10213964

**Comment by doomsju** [comment]
@TomasVerheyen This is resolved. We looking further in this issue to prevent this in the future.
