### ISSUE TITLE
GRB status taxonomy not found

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#171]
I get a HTTP 404 on the following resource https://api-gateway.beta.gipod.vlaanderen.be/api/v1/taxonomies/grb-statuses

It is referenced in the documentation here:
https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/RegisterGroundwork

**Comment by doomsju** [comment]
The url is: https://api-gateway.beta.gipod.vlaanderen.be/api/v1/taxonomies/public-domain-occupancy/grbimpact

We will check the documentation.

**Comment by AIV-Bert** [comment]
We will fix the documentation in the next release.
