### ISSUE TITLE
Added contacts only visible after refresh

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#172]
**Describe the bug**
When I add contacts to a SYN, they are not visible after clicking on Save button.
When I refresh the screen, they are.
after clicking save 
![2020-10-23 15_24_40-Start](https://user-images.githubusercontent.com/70695400/97009301-3967de80-1544-11eb-852e-c2c29ed1cf26.jpg)
After refresh
![2020-10-23 15_25_07-Start](https://user-images.githubusercontent.com/70695400/97009296-3836b180-1544-11eb-9cbd-beeee3af84f5.jpg)

**Expected behavior**
Contacts are immediately visible after clicking Save button.

**Comment by AIV-Bert** [comment]
Hi @SilPal,

This is issue will be resolved in the next UI release.

Kind regards,

Bert
