### ISSUE TITLE
Grondwerk en contact organisatie aanmaak niet synchroon

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#175]
**Describe the bug**
Wanneer we een grondwerk aanmaken, lezen we ook meteen erna ook het grondwerk om de juiste data in ons systeem te plaatsen. Gezien de service van grondwerk aanmaak synchroon is, verwachten we dat dit mogelijk moet zijn.
Maar wanneer we het grondwerk lezen, zijn er 3 mogelijke scenario's:
1) Grondwerk is aangemaakt en we kunnen data succesvol lezen
2) Grondwerk is aangemaakt (krijgen 201 terug) maar wanneer we het lezen krijgen we een 404 not found voor het grondwerk
3) Grondwerk is aangemaakt (krijgen 201 terug) maar wanneer we het lezen is de contact organisatie collectie leeg, doordat achterliggend de contact organisatie nog niet aangemaakt is verwacht ik want wanneer we de GET-call paar minuten later nog eens uitvoeren, krijgen we wel een contactorganisatie terug.

**Expected behavior**
Wanneer we het grondwerk aanmaken verwachten we dat dit aangemaakt is en ook de contact organisatie aangemaakt is alvorens we onze 201-response terug krijgen van onze grondwerk creatie call.

**Additional context**

**Correlation id and request**
Register groundwork (Auth policies: gipod_pdo_write)

**Comment by doomsju** [comment]
De write api's werkt synchroon (POST, PUT, PATCH endpoints). Dwz dat indien je een status code 201, 200 terug krijgt je er zeker kan van zijn dat uw operatie gelukt is en verwerkt.

De lees kant (GET endpoints) is "eventually consistent". Dwz dat er een kleine vertraging kan zijn vooraleer je de recentste toestand terug krijgt in de response.

We hebben een mechanisme waarmee je kan checken of je de laatste toestand krijgt van een bepaalde entiteit. In de response van een POST/PUT/PATCH is een response header ETAG beschikbaar. Deze ETAG bevat een indicatie van de laatste versie van de resource. Bij een GET endpoint is het mogelijk de waarde van de ETAG mee te geven in de request header "If-Match". Indien de resource server nog niet kan antwoorden met de minimaal verwachte versie zal een status code 412 (Precondition Failed) worden teruggegeven. Dan kan je een retry doen tot je status code 200 OK krijgt.

De vertraging houden we zo minimaal mogelijk. Ons objectief is hier max 2 sec. In de meeste gevallen worden verwerkt binnen de +/- 1 sec. Indien het minuten zou duren vooraleer je de laatste toestand kan opvragen werkt het GIPOD-systeem niet zoals verwacht.

Er zijn dus 2 mogelijkheden:

- Bij voorkeur ETAG mechanisme gebruiken dan ben je zeker van het resultaat
- Inbouwen van een kleine delay (minder garantie)

Hopelijk kan dit helpen. We zullen onze algemene API documentatie verbeteren waarin we dit beschrijven.
