### ISSUE TITLE
Incorrect Timezone?

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#176]
For some reason a 'Z' is added to the end of the datetime strings when using the API. I think this Z should not be there.

A question related to the bug is:
What is the assumed timezone the timestrings obtained through the API are expressed in?

An example of the timestrings currently obtained through the API:
    "period": {
        "@type": "PeriodWithDuration",
        "start": "2020-12-15T23:00:00Z",
        "end": "2020-12-30T23:00:00Z",
        "duration": null
    },

**Comment by doomsju** [comment]
In The API we expect all datetime information in UTC. Z is the zone designator for the zero UTC offset. 
https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)
