### ISSUE TITLE
Vraag ivm referentie nummer bij ophalen synergie

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#177]
Hallo,

Wij gebruiken de API GET /api/v1/trench-synergies/{gipodId} voor het inlezen van de synergie in ons backend systeem.  In de tabel Groundworks krijgen we dan alle grondwerken binnen die in de synergie zitten.

Het enige veldje wat we daar ontbreken is het referentie nummer van het grondwerk.  Wij halen dit binnen in ons backend systeem omdat dit makkelijk is voor business voor de communicatie met de andere partijen.

Is het eventueel mogelijk om langs jullie kant ook het referentie nummer mee te geven in deze tabel van grondwerken ?  Dat zou ons allesinds een deel ontwikkeling en extra calls uitsparen.

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Dag Bert,
Zoals afgesproken is de API bevroren en doen we geen contract wijzigingen meer tot na release 1. Mogelijks kan dat bij sommige integratoren een fout in hun huidige implementatie veroorzaken. In principe dus nog enkel bugs en stabiliteitsverbeteringen die geen impact kunnen hebben op bestaande integraties.

**Comment by doomsju** [comment]
@hij242 In GIPOD² is de referentie ook geen verplicht veld meer bij een grondwerk. Dus mogelijks ontbreekt het soms.
