### ISSUE TITLE
Missing API call to delete a signaling permit

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#179]
I don't see an API call to delete a signaling permit.
we would like to use this to fix errors or delete wrongly created signaling permits

**Comment by olivermay** [comment]
We didn't plan on deleting signaling permit requests by design. However I do understand the requirement, I'll suggest that we add a specific status for signaling permits where the request is canceled. Would that cover your case? 

I'll check with the business and come back to you later.

**Comment by berdienderoo** [comment]
Hi @olivermay , this would indeed cover our use cases.
Would it be possible to have it in (one of ) the following beta-releases?

**Comment by berdienderoo** [comment]
And related to this, what status should we set the mobility hindrance object to if the signaling permit is cancelled? E.g. one creates a mobility hindrance object and a signaling permit linked to that. This was an error. If we have the new status for signaling permit, we can set that, but what should the status for the mobility hindrane be: onbekend? or gevalideerd?

**Comment by olivermay** [comment]
This was discussed during the business workgroup. There will be an extra status available for a canceled the signaling permit.

As a result of this there will also be a new status on the mobility hindrance to set this as canceled.

**Comment by berdienderoo** [comment]
That's great news. Any idea when this will be available in beta?

**Comment by berdienderoo** [comment]
Any update on this? Will this be release before the end of the week as said during the last question hour?

**Comment by olivermay** [comment]
This functionality is now available on beta, see #200
