### ISSUE TITLE
Bbox format

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#18]
The request to search for intakes can take a bounding box as parameter. The bounding box should be given as a string. Can you give an example of such a bounding box? Is a WKT poygon required?

**Comment by doomsju** [comment]
Hi Berdien,
The format of the bounding is 2 WKT point separated by a pipe. 
Example: POINT(49492.00 206963.00)|POINT(139500.72 166888.00)

This is missing in the documentation and will be added for the next release.

**Comment by berdienderoo** [comment]
Thanks for the quick response
