### ISSUE TITLE
Referential Integrity upon deleting MobileHindrance

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#180]
I'm seeing something in the beta environment of which I'm not sure it's a bug or a feature.

I read the public domain occupancies, and from the detail of those I read the corresponding mobile hindrances. One public domain occupancy is referring to a mobile hindrance that is deleted. Specific case I find is this: "https://api-gateway.beta.gipod.vlaanderen.be//api/v1/mobility-hindrances/10214938", which returns:

```
{
    "type": "https://httpstatuses.com/410",
    "title": "The requested resource is gone.",
    "status": 410,
    "detail": "MobilityHindrance was deleted on 10/30/2020 11:23:23 by Geosparc with reason delete reason"
}
```

Shouldn't the public domain occupancy not be updated to remove the mobile hindrance as consequence once it's deleted?

**Comment by doomsju** [comment]
We will check what we do for tis case.

**Comment by AIV-Bert** [comment]
Follow up and discussion in issue #258
