### ISSUE TITLE
Datetime conversion

### ISSUE THREAD

**Issue by darkoatemakina** [Informatievlaanderen/GIPOD#183]
Jonathan was onto something in #176 I believe.
There is inconsistency between storing the datetime strings in old GIPOD and new one. The problem might be in the conversion of old data that was already in database.

Here is the example of one project:
Old GIPOD
"StartTijdstip": "2020-07-13T00:00:00",
"EindTijdstip": "2020-12-02T00:00:00"
New GIPOD
"start": "2020-07-12T22:00:00Z",
"end": "2020-12-01T23:00:00Z",

We were taking the old ones as local time (UTC+1) and now we take new ones as UTC but we have the difference when displaying the dates as +-1h matters when time is around midnight and can result in +-1 day.

When converting "2020-07-12T22:00:00Z" to UTC+1, this is still July 12 (23:00) but the old value, which is correct one, is July 13 (00:00).

**Comment by AIV-Bert** [comment]
Hi @darkoatemakina,

The Belgum local time uses daylight saving times. The offset between UTC time is different during summer and winter. This is the correct and expected behavior.

> CET alternates between UTC+1 (standard time) and UTC+2 (when daylight saving time (DST) is observed). All countries in the CET time zone observe DST (UTC+2) from 02:00 am on the last Sunday of March until 03:00 am on the last Sunday of October.

> When converting "2020-07-12T22:00:00Z" to UTC+1, this is still July 12 (23:00) but the old value, which is correct one, is July 13 (00:00).

Your conversion should take daylight saving time into account.

Kind regards,
Bert
