### ISSUE TITLE
Problemen op staging ?

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#184]
We zijn momenteel testen aan het uitvoering op staging maar in de GUI krijgen we problemen bij het opslaan van een nieuw grondwerk.  

We krijgen de boodschap "Fout  Er ging iets mis bij het laden" als sinds deze morgen bij het aanmaken van een grondwerk.

Is er iets mis en gaat dit lang duren ?

Mvg,
Bert De Groote

**Comment by AIV-Bert** [comment]
Dag @hij242,

We hebben de problemen kunnen herleiden naar een issue tijdens de deploy van de nieuwe versie op staging.
ZIjn de problemen nu van de baan?

Met vriendelijke groeten,

Bert

**Comment by hij242** [comment]
Hallo Bert,

Sorry voor late reactie maar ik had een paar dagen verlof.  Heb nu getest en het probleem is inderdaad van de baan.

Mvg,
Bert De Groote
