### ISSUE TITLE
End date in the UI is shown in UTC-0

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#185]
For the groundwork with id: 10213932, we get via the API the following period in the response:
"period": {
 "@type": "PeriodWithDuration",
 "start": "2021-01-03T23:00:00Z",
 "end": "2021-01-08T23:00:00Z",
 "duration": null
 },

And in the UI the start date is correctly converted to local time, but the end date seems to be shown in UTC-0 as can be seen in the screenshot:
![Screenshot 2020-11-04 at 14 10 58](https://user-images.githubusercontent.com/1756405/98120283-0f9ca900-1eae-11eb-836b-afd226cfbd31.png)

I think the expected behavior is for the end date also to be shown in local time in the UI.

**Comment by AIV-Bert** [comment]
Hi @langens-jonathan,

The UI is correct and works on local time. The period runs from 4/1/2021 (local time) until 8/1/2021 (local time) and including 8/1/2021 (local time).

You expect to see 9/1/2021 in the UI. That is a wrong assumption. The period end on "2021-01-08T23:00:00Z", local time the is "2021-01-09T00:00:00". The period ends at midnight. The day 9/1/2021 is not a part of this period.

Kind regards,
Bert

**Comment by langens-jonathan** [comment]
Hey @AIV-Bert 

But should that logic than not also be applied to the start date? Because there  the UI does convert 2021-01-03T23:00:00Z to 2021-01-04?

Thank you 
Jonathan

**Comment by AIV-Bert** [comment]
The API describes a period
starting from a certain moment in time (including that specific moment) 
ending at a certain moment in time (exluding that specific moment)

Interval notation: [start, end[
X is part of the period when Start ≤ X < End

2021-01-03T23:00:00Z --> inside period
2021-01-08T22:59:59Z --> inside period
2021-01-08T23:00:00Z --> outside period

The UI converts this into a more readable format.
Ui states: From Monday 4/1/21 up to and including Friday 8/1/21
