### ISSUE TITLE
Foutmelding bij aanmaak inname in beta en staging

### ISSUE THREAD

**Issue by JeremyFluvius** [Informatievlaanderen/GIPOD#187]
Probleem doet zich voor in zowel Beta als Staging.

Bij het manueel aanmaken van een inname in GIPOD² krijgen we volgende foutmelding:
_One or more validation errors occurred.
'Specification Ids' must not be empty. (SpecificationIds)_

Nochtans zijn alle verplichte velden ingevuld.
Wat doen we verkeerd? 

![image](https://user-images.githubusercontent.com/62639988/98535320-2ebc8180-2286-11eb-885f-9aab18dc2424.png)

**Comment by AIV-Bert** [comment]
Beste @JeremyFluvius,

Sinds kort is er in de API een nieuwe validatie regel toegevoegd. Een specificatie is verplicht bij grondwerken van Categorie 1. 
Dit moet later nog in de UI toegevoegd worden. De foutmelding is correct. De aanduiding van de verplichte velden ontbreekt nog in de UI.

Met vriendelijke groeten,

Bert
