### ISSUE TITLE
rol toezichter : problemen met organisationid

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#188]
**Describe the bug**
Bij Wijziging in GUI (beta en staging) van de rol dossierbeheerder naar toezichter en dan bewaren krijgt men een foutmelding rond organisationid

![image](https://user-images.githubusercontent.com/47108018/98661936-68a18c80-2347-11eb-8e69-71e05524e170.png)

Verwacht gedrag : geen foutmelding rol toezichter kan gebruikt worden bij aanmaak van een grondwerk op de gui

**Comment by AIV-Bert** [comment]
Dag @JanDegroote,

Er is minstens 1 dossierbeheerder nodig. De foutmelding is echter onduidelijk.

Met vriendelijke groeten,

Bert
