### ISSUE TITLE
Via de api om een grondwerk aan te passen worden datumvelden zonder uur opgeladen met 01:00 of 02:00 (voor het winteruur)

### ISSUE THREAD

**Issue by user1862** [Informatievlaanderen/GIPOD#189]
**Describe the bug**
De planningsdatum van tot wordt via de api aangeleverd als - bvb - 2101-01-01 en verwerkt in  Gipod als 01/01/2021 01:00

**Expected behavior**
Ik zou verwachten dat er gewoon 01/01/2021 zou staan.

**Additional context**
Verschilt ook met de zomertijd. Dan was het verschil 2 uur.

Bedankt.

Mvg,

Luc.

**Comment by AIV-Bert** [comment]
Beste  @user1862,

De API werkt met UTC tijd. De UI werkt in CET/CEST (resp. winter/zomer).

In jouw geval geef je 2101-01-01 mee aan de API, de API werkt in CET en als je dit terug in de API opvraagt krijg je 2101-01-01 UTC. In de UI wordt dit correct omgezet naar 01/01/2021 01:00 (CET).

Je integratie met de API zal dus in UTC tijd moeten werken. Het verschil tussen UTC en onze Belgische tijd is anders tijdens de zomer dan tijdens de winter. Hou hier zeker rekening mee.

Met vriendelijke groeten,

Bert
