### ISSUE TITLE
Aanmaak grondwerk op niveau (sub)organisatie

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#19]
Hallo,

Excuses al op voorhand voor deze lange uitleg.

Het oude Fluvius was ingedeeld in 2 hoofdorganisaties (ex-Eandis en ex-Infrax) met daaronder elk een aantal suborganisaties.  De interessezones zijn gekoppeld aan de suborganisaties.
Mijn begrip was dat we voor de creatie van een grondwerk als owner ID de hoofdorganisatie gebruiken en dat we de suborganisatie als beheerder zetten bij de contacten.  

Maar dit schept wel enkele problemen :
* De zoekfunctie van de innames werkt op ownerID en niet op de contactinformatie.    
* Wanneer ik op het grondwerk met owner Fluvius een SSA aanmaak en die SSA opvraag dan krijg ik geen "receivingOrganisation" terug.  Mijn testvoorbeeld : 10000091.  Vermoedelijk heeft dit te maken met het feit dat de interessezones aan onze suborganisaties hangen ?  
 
In het verleden werd steeds de suborganisatie doorgegeven als "ownerID".  Maar hoe we intern georganiseerd zijn zou voor de buitenwereld niets mogen uitmaken.   Maar intern willen we alles per suborganisatie kunnen bekijken/verwerken.  

Nu, wanneer we in het nieuwe GIPOD een grondwerk willen lanceren op een suborganisatie (ownerID), dan krijgen we vanuit het GIPOD de fout 403 terug : "Insufficient permissions to perform the operation.".

Ik zit dus eigenlijk met verschillende vragen die aan elkaar gekoppeld zijn : 
* wat is de juiste manier om om te gaan met hoofd- en suborganisatie.
* indien suborganisatie als ownerid te gebruiken, kunnen jullie dit mogelijk maken
* waarom krijg ik geen "receivingOrganisation" te zien bij opvragen SSA.
* daarna moeten we ook eens bekijken hoe we van 2 hoofdorganisaties naar 1 kunnen overstappen.

Misschien is het makkelijker om even te bellen/skypen.  Laat maar weten mocht dit uw voorkeur zijn.

Met vriendelijke groeten,
Bert De Groote

**Comment by olivermay** [comment]
Dag Bert, 

het lijkt ons eenvoudiger om hier inderdaad eerst even rond te bellen. Ik stuur je een vergaderverzoek.

mvg, 

Oliver

**Comment by doomsju** [comment]
Korte samenvatting van wat werd besproken:

Het is mogelijk als Beheerder van een grondwerk een sub-organisatie binnen uw eigen organisatie structuur te gebruiken.

We bekijken of het mogelijk is om de synergie-interessezones die nu op Beta aanwezig zijn over te zetten als samenwerkingszone in het nieuwe GIPOD-systeem.

**Comment by bertzor** [comment]
> We bekijken of het mogelijk is om de synergie-interessezones die nu op Beta aanwezig zijn over te zetten als samenwerkingszone in het nieuwe GIPOD-systeem.

In afwachting kan je wel gebruik maken van 3 test-organisaties die jullie SSA zullen ontvangen. Deze test-organisaties hebben hun interesse zones ingesteld op 14 mei 2020 omstreeks 16:00.
- Blauw (samenwerkingszone = Vlaanderen)
`POLYGON((77629.333007813 235957.33398438,13629.333007813 200629.33398438,30013.333007813 153269.33398438,50237.333007813 153781.33398438,57917.333007813 159669.33398438,77373.333007813 153269.33398438,112957.33300781 156085.33398438,124989.33300781 148149.33398438,184381.33300781 159413.33398438,210237.33300781 150197.33398438,263485.33300781 155573.33398438,261181.33300781 163253.33398438,245565.33300781 168629.33398438,260413.33300781 207541.33398438,241469.33300781 214197.33398438,230973.33300781 224181.33398438,216637.33300781 222133.33398438,208957.33300781 227509.33398438,205629.33300781 235445.33398438,200765.33300781 244661.33398438,188221.33300781 240821.33398438,179773.33300781 247733.33398438,169277.33300781 239285.33398438,159293.33300781 244917.33398438,129597.33300781 225461.33398438,116797.33300781 217013.33398438,93501.333007813 224437.33398438,87357.333007813 218037.33398438,82493.333007813 221877.33398438,84797.333007813 228021.33398438,77629.333007813 235957.33398438))`
- Groen (samenwerkingszone = Linker helft Vlaanderen)
`POLYGON((19517.333007813 203360,69693.333007813 233824,132157.33300781 222560,160829.33300781 146016,23613.333007813 156000,23869.333007813 156000,19517.333007813 203360))`
- Oranje (samenwerkingszone = Rechter helft Vlaanderen)
`POLYGON((129853.33300781 228960,155709.33300781 147296,240189.33300781 153440,261949.33300781 154976,254525.33300781 220000,194109.33300781 245088,148541.33300781 245344,129853.33300781 228960))`

**Comment by AIV-Bert** [comment]
> We bekijken of het mogelijk is om de synergie-interessezones die nu op Beta aanwezig zijn over te zetten als samenwerkingszone in het nieuwe GIPOD-systeem.

In afwachting kan je wel gebruik maken van 3 test-organisaties die jullie SSA zullen ontvangen. Deze test-organisaties hebben hun interesse zones ingesteld op 14 mei 2020 omstreeks 16:00.
- Blauw (samenwerkingszone = Vlaanderen)
`POLYGON((77629.333007813 235957.33398438,13629.333007813 200629.33398438,30013.333007813 153269.33398438,50237.333007813 153781.33398438,57917.333007813 159669.33398438,77373.333007813 153269.33398438,112957.33300781 156085.33398438,124989.33300781 148149.33398438,184381.33300781 159413.33398438,210237.33300781 150197.33398438,263485.33300781 155573.33398438,261181.33300781 163253.33398438,245565.33300781 168629.33398438,260413.33300781 207541.33398438,241469.33300781 214197.33398438,230973.33300781 224181.33398438,216637.33300781 222133.33398438,208957.33300781 227509.33398438,205629.33300781 235445.33398438,200765.33300781 244661.33398438,188221.33300781 240821.33398438,179773.33300781 247733.33398438,169277.33300781 239285.33398438,159293.33300781 244917.33398438,129597.33300781 225461.33398438,116797.33300781 217013.33398438,93501.333007813 224437.33398438,87357.333007813 218037.33398438,82493.333007813 221877.33398438,84797.333007813 228021.33398438,77629.333007813 235957.33398438))`
- Groen (samenwerkingszone = Linker helft Vlaanderen)
`POLYGON((19517.333007813 203360,69693.333007813 233824,132157.33300781 222560,160829.33300781 146016,23613.333007813 156000,23869.333007813 156000,19517.333007813 203360))`
- Oranje (samenwerkingszone = Rechter helft Vlaanderen)
`POLYGON((129853.33300781 228960,155709.33300781 147296,240189.33300781 153440,261949.33300781 154976,254525.33300781 220000,194109.33300781 245088,148541.33300781 245344,129853.33300781 228960))`

**Comment by olivermay** [comment]
We created a small tutorial on how to copy the collaboration zone from the existing GIPOD application to the new, using swagger. You can find it here: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1661763707/Workaround+instellen+samenwerkingszone+via+Swagger (in dutch)
