### ISSUE TITLE
BUG : notificatie "Periode synergie gewijzigd" niet ontvangen

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#190]
Ik heb als organisatie Blauw de datums van SYN10215271 gewijzigd van 16/11-26/11 naar 23/11-30/11.
Vermits Proximus Area 2.1 deelneemt aan de SYN, verwacht ik een notificatie dat de datums van de SYN gewijzigd werden.

Deze notificatie is echter niet terug te vinden met API GET /api/v1/notifications met organisation id 53cf32f2-19d4-0d00-9b72-97625eac7309
type id van de notificatie : 63cf1f45-4716-4794-92c3-c4c1f401a872

**4 vragen/verwachtingen** 

1. Kunnen jullie me zeggen waarom ik deze notificatie niet gekregen heb ?
2. Wanneer wordt de notificatie uitgestuurd ? Is dat onmiddellijk na de wijziging of pas later ?
3. In de lijst die ik terugkrijg voor bvb. Proximus Area 1.2 vind ik enkel "oude" notificaties met een datum in het verleden (10/2020). Is het normaal dat we deze nog altijd binnenkrijgen ?
4. Ik verwacht in de response ook te zien wat de oude en de nieuwe periode zijn.

**Comment by olivermay** [comment]
Op welke omgeving heb je dit probleem?

**Comment by SilPal** [comment]
op beta omgeving

**Comment by JeremyFluvius** [comment]
Ter aanvulling, bij Fluvius hebben we hetzelfde probleem. 
Sinds 3 nov komen er geen notificaties meer binnen.

Vandaag werken we op staging. Ook in die omgeving komen er geen notificaties binnen.
Via swagger krijgen we een legitieme response, met 0 berichten. Dit ondanks het doorlopen van functionele testen van o.a. SSA's.

**Comment by olivermay** [comment]
We hebben dit kunnen reproduceren, de notificaties zijn inderdaad door een bug stilgevallen op beta en staging. We lossen dit vandaag op.

**Comment by SilPal** [comment]
@olivermay,
is het probleem met de notificaties ondertussen opgelost ?
Alvast bedankt.

**Comment by olivermay** [comment]
Dit zou nu opgelost moeten zijn.
