### ISSUE TITLE
gw is gekoppeld aan een sleufsynergieaanvraag maar dit is niet te zien op de informatie van dit gw

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#191]
Een grondwerk 10585229 werd als antwoord gegeven op sleufsynergieaanvraag 10584993.
Dit is echter niet te zien op de info van grondwerk 10585229
![image](https://user-images.githubusercontent.com/47108018/99553530-8a8db580-29be-11eb-8374-0ba8dc51975a.png)

Bij de ssa 10584993 is wel te zien dat grondwerk 10585229  gekoppeld werd.

**verwacht resultaat** : de info van grondwerk heeft aan dat dit een meegaand grondwerk is met sleufsynergieaanvraag 10584993. 
![image](https://user-images.githubusercontent.com/47108018/99553936-fbcd6880-29be-11eb-87a5-00eb6c7ac6ab.png)

**Comment by olivermay** [comment]
Dit is een gekend probleem, dat is opgelost in de beta release die in de loop van deze week nog wordt uitgerold.
