### ISSUE TITLE
Welke organisatie kunnen we gebruiken op beta om een signalisatievergunning goed te keuren ?

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#192]
Welke organisatie kunnen we gebruiken op beta om een signalisatievergunning goed te keuren ?

**Comment by olivermay** [comment]
Als je het id van de signalisatievergunning doorgeeft, kunnen wij deze alvast goedkeuren.

Gaat het over beta of staging?

**Comment by SilPal** [comment]
bedankt Oliver.
een eerste GW : 10215112 op beta

**Comment by olivermay** [comment]
Ik heb de aanvraag goedgekeurd. 

Bij de aanvraag stond wel Proximus als beheerder, wat niet de bedoeling is. GIPOD zal dit in de toekomst automatisch toewijzen aan het bevoegde lokale bestuur. Dit wordt spoedig opgenomen door het ontwikkelteam.
Ook de hinder zal automatisch de status gevalideerd krijgen bij het goedkeuren van de signalisatievergunning, dit is op dit moment nog niet actief op beta, maar komt er ook aan.
