### ISSUE TITLE
OAuth URL confirmation

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#196]
Hello,
We received Gipod endpoints via #149.

Could you pls confirm if the API & OAUTH URLs be same ? - https://private-api.gipod.vlaanderen.be/ ?

Or, the OAuth URL will be: https://oauth.vlaanderen.be/authorization/ws/oauth/v2/token ?

Thanks a lot for your prompt confirmation & response !

**Comment by rajeevchugh71** [comment]
As our middleware team needs this info to configure the setup, thanks to take it up priority.

**Comment by AIV-Bert** [comment]
API and OAuth are diffenrent:

API:  https://private-api.gipod.vlaanderen.be/
OAuth: : https://oauth.vlaanderen.be/authorization
