### ISSUE TITLE
Sommige gemigreerde synergieen geven een probleem in GUI

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#197]
Hallo,

Bij het opvragen van geconverteerde synergie ID's geven er een aantal problemen, vb bij 7916254, 7201213 7878992, ... krijg ik de boodschap "Fout We kunnen de synergie-gegevens voor xxxx niet terugvinden".  

Je ziet de gegevens wel even staan vooraleer je de foutboodschap krijgt.  Soms merk ik dat er geen zone wordt gevonden maar als je dan nog eens probeert, dan weer wel, maar de foutboodschap blijft.

Bij andere synergie ID's is er dan geen probleem, vb 8096925 of 7621009

Kijken jullie dit eens na ?

Mvg,
Bert De Groote

**Comment by AIV-Bert** [comment]
Dag Bert,

Dit zijn 2 issues. Er is een bug bij de initiële sync van werken waardoor updates die tijdens het synchronisatie-proces niet werden opgepikt. We gaan dit verhelpen.

De foutboodschap in de UI komt doordat de grondwerken niet gevonden worden. We hebben dit reeds verholpen in UI versie 0.9.0. Deze versie is reeds in beta.

Alvast bedankt om dit te melden.
Met vriendelijke groeten,
Bert
