### ISSUE TITLE
Feedback:

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#198]
Beste,

Zou het mogelijk zijn om de indicatie "Publieke contactgegevens" op een contact zichtbaar te maken naast de drop-down ipv. erin ? Anders moet je steeds de contactgegevens openklappen om te zien of het een publiek of niet-publiek contact betreft.
Voorstel in bijgevoegde foto.

![contacten](https://user-images.githubusercontent.com/70695400/100866869-963aab00-3499-11eb-9cba-70c2a7c59c9d.jpg)

Alvast bedankt.

**Comment by AIV-Bert** [comment]
Beste,

Jouw wijziging betekent echter een extra call per contactgegeven om te achterhalen of deze info publiek of niet publiek is. Dit elke keer een detail wordt bekeken. We hebben er voor gekozen om dit niet te doen. Zo blijft de basis info van een inname snel te raadplegen, de extra info kan je toch eenvoudig achterhalen door een klik.

Voorlopig gaan we deze aanpassing niet doorvoeren.

Met vriendelijke groeten,

Bert
