### ISSUE TITLE
TrenchSynergyRequest not updated on Add/Remove Groundwork

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#199]
When an organisation adds or removes a groundwork on a TSR, the TSR is not updated, meaning we do not get the TSR in the 'Search entities' call or in the 'Search TSR' call.

**Comment by doomsju** [comment]
Jeroen,
Is dit bij filtering op basis van lastmodified?

**Comment by jdewilde** [comment]
Jurgen,

Inderdaad dat is zo wanneer we de lastmodified filter toepassen.

Jeroen

**Comment by doomsju** [comment]
Wij fixen dit voor de volgende Beta release.
