### ISSUE TITLE
Validation error op specificationID

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#20]
Hallo,

Wanneer ik in de documentatie lees over het gebruik van het veld specificatie bij een grondwerk dan is het verplicht om bij gebruik van (her)aanleg of herstel/onderhoud een tweede specificatie ID mee te sturen.  Maar het gebruik hiervan is niet verplicht.

Wanneer we de API POST /api/v1/groundworks gebruiken, dan geven we enkel het specificationID van distributienet mee.  Maar hierop krijgen we een validation error terug (zie onderaan).  Idem bij verkaveling of boring.   Het werkt enkel indien we die waarde ook combineren met (her)aanleg of herstel onderhoud.   Dus ofwel zit er een fout in de validatie ofwel in de documentatie.

Kijken jullie dit na ?

Mvg,
Bert De Groote

<StatusDetails>{"type":"https://httpstatuses.com/400","title":"One or more validation errors occurred.","status":"400","detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:ModelState","title":"specificationId","detail":"Error converting value \"bce64878-6cb7-43e7-896c-e01202a05e4c\" to type 'System.Guid[]'. Path 'specificationId', line 1, position 929."}]}</StatusDetails>

**Comment by vmateiaiv** [comment]
Beste Bart,

Als ik de error message bekijk merk ik dat U een Guid meegeeft als ‘specificationId’ ipv een Guid[] array. Probeer eens aub een Guid[] array mee te geven met 1 guid (bce64878-6cb7-43e7-896c-e01202a05e4c) daarin. Dat zou moeten werken.

Zou u aub volgende keer als u een error tegenkomt, de correlationId van de error response bijzetten? Dat vindt u tussen de response headers van elke api response (success of fout).

Mvg,
Voicu Matei
GIPOD team.
