### ISSUE TITLE
Blocking issue: Modify GW - estimated duration error

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#202]
**Describe the bug**
PATCH GW (period update) on Gipod id=10215034 (in beta) comes up with error below:
"detail": "Groundwork period GroundworkPeriod: {\"Start\":\"2020-11-30T00:00:00Z\",\"End\":\"2020-11-30T21:59:00Z\",\"Duration\":null} is invalid in combination with estimated duration estimatedDuration: {\"Days\":14}.\n "

**Expected behavior**
The GW should be modified. 
Don't know where estimatedDuration=14 in the error is being picked up. Gipod GUI https://new.beta.gipod.vlaanderen.be/innames/10215034 displays the estimated duration = 1. Pls check & feedback at the earliest.

**Correlation id and request**
x-correlation-id: 8d05f854-4cfe-47c7-ab73-b95f3dc3546b 

**Request**
{"items":[{"key":"Period","value":{"start":"2020-11-04T00:00Z","end":"2020-11-06T00:00Z","duration":null}},{"key":"EstimatedDurationDays","value":2}]}

**Comment by SilPal** [comment]
@vmateiaiv , could you please have a look at this bug, because it is blocking our UAT testing.
Thanks!

**Comment by doomsju** [comment]
We rollout a hotfix on Beta today

**Comment by doomsju** [comment]
This is issue should be resolved on the Beta environment. 
@rajeevchugh71 Can you validate?

**Comment by rajeevchugh71** [comment]
thanks a lot @doomsju ! We'll test & feedback soon.
