### ISSUE TITLE
te plannen innames in WERF hebben niet altijd een start en eind datum waardoor deze niet als werkopdracht in voorontwerp kunnen aangemaakt worden

### ISSUE THREAD

**Issue by castersjef** [Informatievlaanderen/GIPOD#203]
In WERF is het mogelijk dat een werf een inname heeft die nog geen start en eind datum hebben.
Dit zorgt ervoor dat we deze niet altijd kunnen synchroniseren naar GIPOD.

Dit komt voor wanneer een werf start in de huidige maand maar nog geen start datum heeft voor de inname
OF
Wanneer een werf reeds in uitvoering is en een nieuwe inname wordt toegevoegd waarvan de start en einddatum nog niet gekend is

Het resultaat is dat we in deze gevallen niet kunnen synchroniseren.
In de API "Register groundwork" is het veld "Period" verplicht.

We zouden ervoor kunnen zorgen dat in deze gevallen de inname niet wordt gesynchroniseerd maar dit lijkt me niet ideaal.
Een alternatief zou zijn dat het veld "period" niet verplicht is indien de status van de werkopdracht/inname in voorontwerp is?

Graag jullie feedback hoe we dit het beste aanpakken.

Met vriendelijke groeten,
Jef

**Comment by AIV-Bert** [comment]
Dag Jef,

Hoe pakken jullie dit momenteel aan bij de oude versie van Gipod?

> Dit komt voor wanneer een werf start in de huidige maand maar nog geen start datum heeft voor de inname

Dit is wat onze status 'Niet-Concreet gepland' betekent. De inname is gepland, maar je hebt nog geen exacte datum. Je weet dat de uitvoering voor deze maand is. Je kan dus de periode al ruimer ingeven. Weet je vooraf al hoe lang de inname (ongeveer) zal duren, dan kan je de geschatte duur ingeven. 

_Voorbeeld: je wil vandaag (10/12/2020) iets ingeven en een inname die ongeveer 2 dagen zal duren._ 
`Start 10/12/2020 en einde 31/12/2020.  Geschatte duur 2 dagen.`

Wanneer je dan exact weet wanneer deze wordt uitgevoerd, kan je de inname updaten met de juiste periode. Status updaten naar Concreet gepland, doe je pas als de signalisatievergunning is aangevraagd.

> Wanneer een werf reeds in uitvoering is en een nieuwe inname wordt toegevoegd waarvan de start en einddatum nog niet gekend is

Hier zal je opnieuw een tijdsvenster en geschatte duur moeten meegeven, zoals het voorbeeld hierboven. Wanneer de planning concreet wordt, kan je dan de periode aanpassen.

Met vriendelijke groeten,

Bert
