### ISSUE TITLE
Collaboration zone Suborganisatie

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#204]
Het instellen van een collaboration zone voor een sub organisatie lijkt goe dte gaan maar bij het ophalen van de collaboration zone van de suborganisatie krijg ik steeds de melding 'The Organisation does not exists.'. 
Het lijkt er ook op dat de collaboration zone niet wordt gebruikt om als sub organisatie de SSA te ontvangen.

**Comment by doomsju** [comment]
We hebben dit opgelost. Het zou nu moeten werken met de zone die je hebt gededinieerd.

**Comment by AIV-Bert** [comment]
Closed due to inactivity
