### ISSUE TITLE
Problemen met staging omgeving gipod

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#205]
Grondwerken aanmaken lukt maar om ze dan te zien, herkent gipod staging de gipod id's niet en geeft gipod een foutmelding.

![image](https://user-images.githubusercontent.com/47108018/102048534-9fa00d80-3ddf-11eb-84b4-a3d47bb29c1a.png)

**Comment by AIV-Bert** [comment]
Dag @JanDegroote ,

We hebben dit verholpen. Deze issue zal volgende staging release niet meer kunnen voorkomen.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Dag @JanDegroote,

We gaan dit verhelpen en werken er momenteel aan om dit tijdelijk op te lossen. Deze issue zal in de volgende staging release verholpen worden. Ik geef je straks een update wanneer alles terug werkt.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Dag @JanDegroote,

Je kan terug de nieuw aangemaakte innames opvragen in de UI.
Onze excuses voor het ongemak.

Met vriendelijke groeten,

Bert
