### ISSUE TITLE
GW date update issue

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#206]
**Describe the bug**

While performing tests here in Proximus on 11/12, we noticed that 11/12/20 was not accepted in GW https://new.beta.gipod.vlaanderen.be/innames/10214753 because of error: Groundwork period is invalid for GroundworkStatus: Concreet gepland.\n Periode is niet in de toekomst

However, it was accepted in the update on SYN GW linked to it: https://new.beta.gipod.vlaanderen.be/synergie/10214826

**Expected behavior**

We performed similar tests in the past and didn't get this error before.

Could you pls check this & feedback?

**Comment by bertzor** [comment]
Hi @rajeevchugh71,

Our internal test team made us aware of this bug. We are working on resolving this as we speak.

Thank you for the bug report.

Kind regards,

Bert
