### ISSUE TITLE
Lijst van SSA's + migratie issues

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#207]
Hallo,

In onze database hebben we nog een pak oude gegevens zitten en ik ga die updaten met de status na de migratie.   Daarbij heb ik een probleem omdat ik niet voor alle SSA's een overeenkomstig grondwerk ID heb in onze database.  Het gaat hier over een 600-tal SSA's.    Op welke manier zou ik een lijst kunnen krijgen in Excel met de behorende grondwerk ID's ?  Kan ik dit ergens oplijsten of kunnen jullie me dit bezorgen ?  Van een grondwerk ID kan ik het SSA ID opzoeken maar omgekeerd lukt niet.

Bij enkele steekproeven hierop merkte ik wel enkele verschillen tussen productie en staging.  Een aantal SSA's vind ik bijvoorbeeld niet meer terug op staging maar wel in productie : 197740, 199314, 224209, 230522, 523353.   Ook enkele grondwerken kwam ik al tegen die niet meer op staging bestaan : 542100, 545617.

Mochten jullie me de lijst al kunnen bezorgen (zie bijlage), dan kan ik wel makkelijker zien wat er nog ontbreekt op staging.

Mvg,
Bert De Groote
[SSA ID's zonder grondwerk ID.xlsx](https://github.com/Informatievlaanderen/GIPOD/files/5695070/SSA.ID.s.zonder.grondwerk.ID.xlsx)

**Comment by hij242** [comment]
Kan u hier een antwoordje op geven aub ?

**Comment by vmateiaiv** [comment]
Beste @hij242,

In bijlage een export van alle SSA's met de bijhorende lancering Werkopdracht. Op basis van de SSA Id in de eerste kolom zou u een join/filter kunnen toepassen en op die manier de betrokkene lancerend WO id's detecteren.

Is dat voldoende?

Mvg,
Voicu Matei 
AIV

[Gipod-PROD S+SA.xlsx](https://github.com/Informatievlaanderen/GIPOD/files/5756799/Gipod-PROD.S%2BSA.xlsx)

**Comment by hij242** [comment]
Hallo,

Dat is zeker voldoende om de mapping te kunnen maken, maar ... ik vind de meeste grondwerken terug op staging en new beta maar nergens vind ik de oude synergie aanvragen terug.   

Bijvoorbeeld grondwerk 1835071 met synergie aanvraag 2136668.   Via de zoekfunctie bovenaan rechts zijn geen van beide nummers terug te vinden.  Via de URL "https://new.beta.gipod.vlaanderen.be/innames/1835071" vind ik wel het grondwerk terug maar via de url is de synergie aanvraag niet terug te vinden.  Niet op staging en niet op new beta.  Dit is maar één voorbeeld maar dit geldt zowat voor onze volledige lijst.  Nochtans de synergie aanvraag 2136668 bestaat wel op het productie systeem.  Het is een oude maar die staat daar nog altijd wel in status gelanceerd.  Wij hebben die info ook in ons eigen systeem zitten dus ik wou deze via een job importeren vanuit het nieuwe systeem.  Maar dat lukt uiteraard niet wanneer die gegevens niet worden overgenomen naar het nieuwe GIPOD.   Ik zou daar wel de SSA 2136668 verwachten in status afgesloten met gevolg want er was een synergie uit gemaakt.   Ook de synergie hiervan 2291913 is nergens terug te vinden, niet via zoeken op GIPOD ID, nog via de URL.     Wordt dit nog allemaal in orde gebracht ?

Mvg,
Bert De Groote

**Comment by vmateiaiv** [comment]
Beste @hij242,

Hou zeker rekening met de volgende aspecten:

- De data van oude beta wordt gesyncht naar de neiuwe beta en de data van de oude productie wordt gesyncht naar de nieuwe staging. Dus een id van beta in staging zoeken en omgekeerd zal geen resultaat geven.

- Ook, in de nieuwe staging die de voride dagen gereset en opnieuw (van de oude Gipod prod) gesyncht werd, zijn de SYnergieAanvragen en de Synergien nog niet gesyncht, maar enkel de innames. SSA en SS worden begin volgend jaar gesyncht. Kan dat zijn dat de SA id, die jij niet kan terug vinden, van de oude Gipod prod is?

Prettig endejaar!

Mvg,
Voicu Matei
AIV

**Comment by hij242** [comment]
Het is het tweede geval, ik ben op zoek naar SSA ID's uit productie via de lijst die ik van jou had gekregen.  Ik had een bericht zien passeren dat de migratie gebeurt was dus ging ervan uit dat dit voor alles was.  Wanneer gaat de migratie van de SSA's uitgevoerd worden ?

**Comment by olivermay** [comment]
We plannen deze migratie op woensdag 6/1. We volgen dezelfde timing en stappen als bij de echte in productiestelling (waar de migratie van samenwerking op 20/1 gepland staat).
