### ISSUE TITLE
Delay on beta geoselect 

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#208]
We're testing gipod2/geoselect on the beta environment. We select a gipodid which is both in gipod2 and geoselect.

What we see is that geoselect takes more than 1 minute to reply with data. In the meantime geoselect answers that it's still working on it ("InVerwerking").

Is this long delay on geoselect on the beta environment intentional? And will this be the same on production?

**Comment by AIV-Bert** [comment]
Closed. Issue followed up through email.
