### ISSUE TITLE
Search public domain occupancies: missing groundwork?

### ISSUE THREAD

**Issue by ial565** [Informatievlaanderen/GIPOD#209]
Ik heb een volgend grondwerk:
Get groundwork
GipodId: 10587524 (Groundwork)

Dan zie ik oa in de response
OwnerId: 2ee77faa-2633-0aba-94ab-c2cd5b109d24
LastModifiedOn: 2020-12-17T15:37:06

Vervolgens wil ik de lijst grondwerken van die dag bekijken
Search public domain occupancies
TypeId: 718225ee-78e8-4b6f-bc63-7748cfd0a4d2
LastModifiedStart: 2020-12-17T08:26:57
LastModifiedEnd: 2020-12-18T07:26:57
OwnerId: 2ee77faa-2633-0aba-94ab-c2cd5b109d24

Maar ik krijg een lege lijst als response. Ook zonder de ownerId vind ik dit grondwerk niet terug.
Mis ik iets?

**Comment by AIV-Bert** [comment]
Beste @ial565,

Via deze query krijg ik deze terug.

https://private-api.gipod.staging-vlaanderen.be/api/v1/public-domain-occupancies?typeid=718225ee-78e8-4b6f-bc63-7748cfd0a4d2&ownerid=2ee77faa-2633-0aba-94ab-c2cd5b109d24

Met vriendelijke groeten,

Bert
