### ISSUE TITLE
notification pilootschap werd overgedragen wordt niet uitgestuurd

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#210]
Piloot synergieovergedragen | Nieuwe piloot Syn | Synergie |   | De notificatie wordt uitgestuurd aan alle deelnemers aan de synergie als de piloot wordt overgedragen, en is 7 dagen zichtbaar. | {{piloot}} is nu piloot van deze Syn | 17 | SSpiloot | beta | 0.10
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

Gewenst gedrag

De oorspronkelijke piloot dient deze notificatie ook te verkrijgen, dit is huidig niet het geval.

**Comment by olivermay** [comment]
Jan, we zijn er bij het ontwerpen van deze notificatie vanuit gegaan dat de piloot niet op de hoogte moet gebracht worden, omdat deze zelf het pilootschap overdraagt, en hier dus van op de hoogte is. 

Ik stel voor dat we dit bespreken op volgende BWG, en indien gewenst kunnen we de notificatie aanpassen.

**Comment by JanDegroote** [comment]
Men zou zicht toch kunnen abonneren op een notificatie. 
Dit is vermoed ik een parameter?

**Comment by AIV-Bert** [comment]
Beste @JanDegroote ,

Indien voor jullie deze feature nog steeds gewenst is, kan je dit altijd verder opnemen dia de contactmomenten of via de nieuwe feedback tool.

> Suggesties zoals deze kan je doen via de Feedback knop op https://gipod.vlaanderen.be/
> Dit leidt je naar de pagina waar je kan stemmen op suggesties of zelf nieuwe aanmaken (https://gipod.nolt.io/roadmap/).
> 
> De Github pagina kan je blijven gebruiken voor technische vragen, issues ...

Met vriendelijke groeten,

Bert
