### ISSUE TITLE
Staging GUI - Aanmaken inname geeft foutmelding

### ISSUE THREAD

**Issue by JeremyFluvius** [Informatievlaanderen/GIPOD#211]
Via GIPOD² staging een inname aanmaken geeft volgende foutmelding:
![image](https://user-images.githubusercontent.com/62639988/102779951-5fb7c800-4395-11eb-9040-4392db834443.png)
"Probeer opnieuw" geeft geen oplossing.

Aangemaakte inname komt wel in de lijst van innames terecht.
![image](https://user-images.githubusercontent.com/62639988/102780001-7c540000-4395-11eb-8e4e-bf63b240bedd.png)
Als je ze aanklikt en opent, kan gipod de gegevens voor GIPODid niet terugvinden.
![image](https://user-images.githubusercontent.com/62639988/102780063-968dde00-4395-11eb-9bf3-389629de1dae.png)
De aangemaakte inname kan maw niet worden geopend.

**Comment by AIV-Bert** [comment]
In enkele gevallen is er een probleem met de huidige versie op staging. Dit is opgelost in de volgende versie (staat reeds op beta).
Ik heb voorlopig dit probleem manueel opgelost.

Met vriendelijke groeten,
Bert

**Comment by JeremyFluvius** [comment]
Hallo Bert,
Ik ondervind nog steeds dezelfde problemen (gisteren namiddag en deze ochtend), bij de aanmaak van een GW, openen van een GW, bij het lanceren van een SSA. Testen is zo onmogelijk.

Wanneer zal de volgende versie op staging komen?
We zitten volledig op staging te testen, in beta testen is dus geen optie spijtig genoeg.

Groeten
Jeremy
