### ISSUE TITLE
staging : men kan geen nieuwe inname toevoegen 

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#212]
Men kan een inname ingeven maar bij het uiteindelijk bewaren heeft gipod een foutmelding.

![image](https://user-images.githubusercontent.com/47108018/102871611-e70d4600-443e-11eb-9935-bf319b95c032.png)

Inname zou goed moeten ingegeven kunnen worden in de gui

**Comment by doomsju** [comment]
Zou opgelost moeten zijn
