### ISSUE TITLE
Question: End time of Gipod 2 release

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#218]
Hello,

We understood that Gipod 2 platform release will start at 9H on 21/01. We in Proximus would like to know when the release will end.  

As info above will help us in detailed planning production releases of our applications.

Thanks & br,

**Comment by olivermay** [comment]
That's correct, more information can be found in following issue: https://github.com/Informatievlaanderen/GIPOD/issues/223
