### ISSUE TITLE
Communication during and after launch

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#219]
1.  Is the slack channel that will be used for communication during the launch already active? If not, when do you expect to have the details?
2. Will there be direct communications (telephone,...) options during the launch and days following on this?
3. Will Github be used to keep track of all issues found/logged during and after the launch. This would allow us to check if issues are already known or not and would thus be very helpfull

**Comment by olivermay** [comment]
1. More information about the timeline is available in following issue: https://github.com/Informatievlaanderen/GIPOD/issues/223
2. The main place for launch related issues will be the slack channel, we can start teams sessions or exchange phone numbers there if needed. 
3. We will indeed track issues in GitHub.
