### ISSUE TITLE
Eindtijdstip van AIV voor release GIPOD²  

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#220]
Beste, 

Op 21 januari 2021 vanaf 9 u start de release voor GIPOD² wanneer kunnen we het eindtijdstip van deze release verwachten?
Door de DRY RUN oefening van deze week, zou hierop nu een beter zicht gekregen zijn? 
Kan hierbij een eindtijdstip naar voor geschoven worden? Hieruit willen we gaan bepalen wanneer wij van onze kant taken kunnen stoppen en opstarten. Idealiter zou jullie release tegen de middag klaar zijn, zodat wij de namiddag hebben om onze updates door te voeren.

Daarnaast wensen we ook te weten wanneer op 20 januari 2021 de overdracht van ss een ssa's gaat starten? We gaan hierbij vanuit dat dit pas vanaf 8 u s'morgens is?

Bedankt alvast voor de antwoorden,

**Comment by olivermay** [comment]
De tijdlijn en communicatiekanalen tijdens de release staan aangekondigd in volgend issue: https://github.com/Informatievlaanderen/GIPOD/issues/223

De migratie van de samenwerkingen wordt op 20 januari niet vroeger dan 9:00 gestart.
