### ISSUE TITLE
API trench-synergy-requests-with-groundworks-to-be-added

### ISSUE THREAD

**Issue by JeremyFluvius** [Informatievlaanderen/GIPOD#221]
Staging:
Kan de werking van api/v1/trench-synergy-requests-with-groundworks-to-be-added worden nagekeken aub.

Voor SSA 9195144 werd door Fluvius ja geantwoord zonder grondwerk toe te voegen.
Via bovengenoemde API halen we de SSA's binnen, deze lijst blijft op dit moment leeg. Hier zou minimaal SSA 9195144 moeten zichtbaar worden.

**Comment by doomsju** [comment]
Er is hier inderdaad een probleem met synergie-aanvragen die werden geïmporteerd vanuit het oude GIPOD-systeem. We bekijken dit probleem verder.

**Comment by doomsju** [comment]
Zou nu ook in orde moeten zijn voor synergie-aanvragen die werden geïmporteerd vanuit het oude systeem.
