### ISSUE TITLE
scheme OccurenceLd case of start/end

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#224]
In the swagger.json for OccurenceLd, start and end are defined in all lower case:
```
      "OccurrenceLd": {
        "type": "object",
        "properties": {
          "start": {
            "type": "string",
            "format": "date-time"
          },
          "end": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
```

but in the response of these calls, Capital case is used for Start/End

- GET ​/api​/v1​/groundworks​/{gipodId}​/occurrences
- GET ​/api​/v1​/works​/{gipodId}​/occurrences

e.g.

```
  "member": [
    {
      "Start": "2021-01-07T23:00:00Z",
      "End": "2021-01-31T23:00:00Z"
    }
  ],
  ```

See

- x-correlation-id: 173171ea-73b4-4ee2-a19e-ced7e16ba2a5
- x-correlation-id: 7f7b249a-865f-4ffe-9aab-98b53b4dc152 

Could you either adjust the swagger.json or correct the implementation?

**Comment by AIV-Bert** [comment]
Hi @ireactsam,

We could not change the implementation. as this would cause a breaking change for some. We adjusted the swagger.json.
We will release this fix in API version 1.2.0. Keep an eye on the announcements for the exact timing of this release. 

Kind regards,

Bert
