### ISSUE TITLE
Conflictdetectie in GIPOD2.O

### ISSUE THREAD

**Issue by castersjef** [Informatievlaanderen/GIPOD#226]
Beste,

Is er reeds een conflictdetectie in GIPOD2.0 voorzien?
Tijdens gesprekken met de applicatie eigenaar van WERF werd duidelijk dat in GIPOD1 aan conflictdetectie tussen innames werd gedaan. Hij moest deze conflicten dan goed of afkeuren.
Wij doen al een conflictdetectie in WERF (ook tussen gipod innames en WERF werven) waardoor het voor hem dubbel werk is.
Op termijn zouden deze idealiter synchroniseren. Aangezien we nu bezig zijn met onze GIPOD integratie zouden we dit willen mee opnemen. (indien dit al beschikbaar is.)

Groeten,
Jef

**Comment by AIV-Bert** [comment]
Dag @castersjef,

De conflictdetectie zoals in GIPOD1 bestaat niet in de huidige versie van GIPOD2. Tijdens het intekenen in de UI zie je wel al meteen de mogelijke conflicten die kunnen optreden.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Closed due to inactivity
