### ISSUE TITLE
Occurances en periodes in GIPOD2.0

### ISSUE THREAD

**Issue by castersjef** [Informatievlaanderen/GIPOD#227]
Beste,

We zijn bezig met het uitbreiden van onze synchronisatie van werf innames naar GIPOD2.0
In een vorig gesprek hebben we het reeds gehad over periodes en occurances in WERF.
Hierin duiden we aan wanneer het openbaar domein effectief zal ingenomen worden tijdens de periode van een inname.

In Werf kan dit redelijk complex worden. Hieronder zijn een aantal screenshots van de mogelijkheden. 
We hebben de mogelijkheden bekeken in de werk/grondwerk en hinder API's.
Op basis hiervan zien we niet meteen een oplossing.

- We zouden meerdere hinders kunnen maken voor ieder moment dat er hinder is op basis van ons regime
- We zouden ieder occurance kunnen berekenen en deze als "periods" doorgeven"
- In de timeschedule lijkt het enkel mogelijk om 1 specifieke dag + tijdstip door te geven. Voor het eerste voorbeeld hieronder zouden we dus meerdere hinders moeten aanmaken voor ieder tijdspannen binnen een dag en dit voor iedere dag in het regime
- Hebben jullie nog een andere suggestie?

Voor iedere suggestie hierboven kan het resultaat aanzienlijk oplopen aangezien een inname over meerdere weken/maanden kan lopen.

![image](https://user-images.githubusercontent.com/37434828/104280373-1813f000-54ac-11eb-883f-d3577f9bfb69.png)

![image](https://user-images.githubusercontent.com/37434828/104280915-ee0efd80-54ac-11eb-8a91-3a8a8f7a25b7.png)

![image](https://user-images.githubusercontent.com/37434828/104280949-f9622900-54ac-11eb-80dc-17fe7ad0b4c9.png)

**Comment by AIV-Bert** [comment]
Dag @castersjef,

Bedankt voor je geduld, de aanloop naar de release was druk en dit is uit het oog verloren.

Ik zie weinig problemen met jullie mogelijkheden. Die komen bijna volledig overeen met de mogelijkheden die Gipod je geeft.

- Elk weekdag van 8-17 --> stemt perfect overeen met tijdschema in Gipod
- Elk weekend hele dag --> stemt perfect overeen met tijdschema in Gipod
- Elke dag buiten spits --> lukt niet met 1 tijdschema, hier kan je een hinder aanmaken die loopt van 20:00 tot 06:00 en een hinder die loopt van 10:00 tot 15:00

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Closed due to inactivity
