### ISSUE TITLE
notificaties filteren : anders niet werkzaam

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#228]
We merken dat de filtering van notificiaties nog niet mogelijk is. Dit dient per suborganisatie en per type en dergelijke filterbaar te zijn om werkbaar te zijn.

![image](https://user-images.githubusercontent.com/47108018/104415648-aa7ec700-5572-11eb-8321-32dffe5fb82a.png)
We zien dat dit nog niet mogelijk is, maar dat er aangegeven werd dat dit er zeker zou zijn voor R1 van GIPOD.

**Comment by olivermay** [comment]
Dag Jan, 

ik begrijp dat dit vervelend is. We doen er alles aan om dit zo snel als mogelijk toe te voegen. 

Het filteren per suborganisatie is wel al mogelijk, via het selecteren van de suborganisatie rechts bovenaan. Via de API kan ook al gefilterd worden. 

mvg, 

Oliver
