### ISSUE TITLE
Final urls for production

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#229]
Can you confirm the final URLs for production for both the API and the GUI?
In the confluence documentation I find "Production: https://api-gateway.gipod.vlaanderen.be" (see https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1245610719/API+documentation), but I also found the following "https://private-api.gipod.vlaanderen.be" (see https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1322024961/Release+-+Big+Bang?preview=%2F1322024961%2F1937539076%2FGIPOD%20omgevingen.pdf)

Similar for the GUI. Do the URL's include www or not?

**Comment by doomsju** [comment]
Url for the API: https://private-api.gipod.vlaanderen.be
Url for the GUI: https://gipod.vlaanderen.be (without www)

I corrected the documentation.

**Comment by berdienderoo** [comment]
Thanks
