### ISSUE TITLE
Swagger op productie

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#230]
Hallo,

Hoe gaan we swagger omgeving van productie kunnen gebruiken na go-live ?   Momenteel geraak ik daar op met een autorisatie token aangemaakt op de staging omgeving (via /demo).    
Gaat die /demo ook mogelijk worden op productie of kunnen we deze van staging blijven gebruiken ?

Met vriendelijke groeten,
Bert De Groote

**Comment by AIV-Bert** [comment]
Dag @hij242,

De swagger en /demo pagina blijft momenteel op dezelfde wijze werken, ook op productie zal je dit kunnen gebruiken.

Met vriendelijke groeten,

Bert
