### ISSUE TITLE
Oplijsting van de synergieaanvragen :  beschrijving en referentie van lancerend GW wordt niet getoond

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#231]
In de oplijsting van de synergieaanvragen die moeten beantwoord worden zijn heel weinig gegevens te zien.
De beschrijving (waarin ook door de nuts de postcode, gemeenten en straat opgenomen) van het lancerend GW wordt niet getoond alsook niet de referentie. Dit vermoeilijkt de verwerking van de synergieaanvragen.

**Comment by AIV-Bert** [comment]
Dag @JanDegroote,

Inmiddels zijn deze lijsten na overleg met de gebruikers aangepast. Hopelijk is dit voor jou voldoende.

Indien het niet voldoende is of je hebt nog andere suggesties, kan je dit vanaf nu doen via de nieuwe Feedback knop op https://gipod.vlaanderen.be/
Dit leidt je naar de pagina waar je kan stemmen op suggesties of zelf nieuwe aanmaken (https://gipod.nolt.io/roadmap/).

De periode en planning van een grondwerk blijft weldegelijk belangrijk. Als je deze feature in de website wil zien, kan je dus best dit melden via onze feedback tool.

De Github pagina kan je blijven gebruiken voor technische vragen, issues ...

Bedankt voor deze suggestie!

Met vriendelijke groeten,

Bert
