### ISSUE TITLE
Filtering van de notificaties

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#232]
Bij de oplijsting van de notificaties is het niet mogelijk te filteren. We hadden begrepen dat er voor release 1 filtermogelijkheden voorhanden gingen zijn?
 
Daarnaast is de informatie rond de notificatie heel summier en met weinig beschrijving voorzien zodat niet met een snel oog de notificatie kan bekeken worden.

**Comment by olivermay** [comment]
De mogelijkheid om te filteren wordt, als alles goed gaat, deze week toegevoegd, en zal dan ook beschikbaar zijn in de productie omgeving.

Ik neem je feedback ivm de summiere informatie op met onze UI-expert, en we nemen dit op in de UI-verbetingen.

**Comment by olivermay** [comment]
De filtermogelijkheden zijn toegevoegd en beschikbaar op de test omgeving. In de loop van de dag zal dit ook beschikbaar worden op beta en staging.
