### ISSUE TITLE
Fout in conversie van data van GIPOD1 naar GIPOD2?

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#233]
Voor hinderpremie zijn we aan het testen tussen GIPOD1 en GIPOD2 productie.

Er zijn gevallen waarbij een GIPODID voldoet aan onze criteria in GIPOD1, maar die niet meer voldoen aan onze criteria in GIPOD2. Zouden jullie kunnen checken wat de reden is?

Als voorbeelden GIPODID 9219468 en 9237861... alletwee op productie. In GIPOD1 voldoen ze aan onze criteria (categorie1, langer dan 30 dagen, concreet gepland of in uitvoering, ergens op de rijbaan), in GIPOD2 ontbreekt voor die GIPODIDs een consequence/gevolg, en als gevolg langs onze kant worden die dan niet in aanmerking genomen voor een premie.

mvg,
Sven

**Comment by naomioste** [comment]
Sven, 

9219468 is een voorbeeld van een inname die in GIPOD1 waarschijnlijk onterecht geselecteerd werd, 
Als hinderlocatie stond daar "rijbaan", maar bij hinder gevolgen is er geen gevolg voor gemotoriseerd verkeer geselecteerd. In GIPOD2 staat daarom "geen hindergevolgen" op die zone aangeduid, want die zijn er volgens de data niet. 
Als ik de beschrijving van de hinder correct interpreteer, gaat het om signalisatie specifiek voor werfverkeer die daar is aangebracht.

9237861 is een gelijkaardig geval, al kan het hier ook aan de beperkte ingave van hinder liggen.
GIPOD1 heeft als locatie hinder "rijbaan", maar de hinder gevolgen daar zijn beperkt tot "handelaars bereikbaar". Voor de rest niks van hinder aangeduid voor gemotoriseerd verkeer. Vandaar dat in GIPOD2 deze inname niet geselecteerd wordt.

Het was altijd de bedoeling om een juistere selectie van innames voor de hinderpremie te hebben, net door bepaalde hindergevolgen voor gemotoriseerd verkeer (gevalideerd door VLAIO) in rekening te brengen ipv enkel de hinder locatie (om dat die eigenlijk niks zegt over de gevolgen). 

Op basis van GIPOD2 data zouden jullie dus minder onterechte premies uitdelen. Dit zijn daar mooie voorbeelden van.
Laat gerust weten als er nog voorbeelden zijn die we moeten bekijken. 

Groeten,
Naomi
