### ISSUE TITLE
Date misalignment between GIPOD UI & API

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#234]
Hallo,
wij merken een verschil in de start-datum van een GW zoals die verschijnt in GIPOD UI en diezelfde datum, zoals we die terugkrijgen in de GET GW API.
Alvast bedankt voor jullie feedback.
mvg,
Silvie
![MicrosoftTeams-image](https://user-images.githubusercontent.com/70695400/105058643-b8eb4800-5a76-11eb-95b8-b1d2361eb8fa.png)

**Comment by AIV-Bert** [comment]
Beste @SilPal,

De API werkt in UTC tijd.
De website werkt in lokale Belgische tijd (CET+1/+2 afhankelijk van winteruur/zomeruur).

Dit is dus het gewenste gedrag.

Met vriendelijke groeten,

Bert

**Comment by SilPal** [comment]
@AIV-Bert 
En welke datum is dan de correcte ?
De startdatum in de UI (29/01) of die in de API (28/01) ...
Persoonlijk vind ik de manier waarop datums in de UI & API geïmplementeerd werden heel verwarrend. Elke integratie die we gedaan hebben (in elke interne applicatie) heeft hier alleen maar problemen mee gehad. 
Is er een reden waarom de datums niet gewoon dezelfde tijdzone volgen in UI & API ?

Alvast bedankt om dit een beetje te verduidelijken.
mvg,
Silvie

**Comment by AIV-Bert** [comment]
Dag Silvie,

Dat is net het punt het zijn geen verschillende datums. Ze bepalen exact hetzelfde moment, hetzelfde tijdstip en zijn dus beiden gelijk.
Bij twijfel mag je altijd de api als referentie nemen. De UI is gewoon een integratie met de API, net zoals jullie die interne applicaties hebben. Maar in dit geval zijn ze dus beiden correct.

Onze integratie, de website, kiest ervoor om de eindgebruiker datums in lokale Belgische tijd te tonen. De api is voor iedereen gelijk en verwacht UTC.

In jullie applicaties moeten jullie dus eenvoudig de aangeleverde datums van de api afhandelen binnen de UTC tijdzone. Wensen jullie echter zoals de website in lokale tijd te werken, moeten jullie de datums eerst converteren naar de tijdzone die jullie wensen, maar ook terug als je de API opnieuw aanroept. Aangezien we voorlopig nog met 'daylight saving time' werken in België zal je daar ook rekening mee moeten houden.

Met vriendelijke groeten,

Bert
