### ISSUE TITLE
Conversie innames met type riolering naar gipod2

### ISSUE THREAD

**Issue by user1862** [Informatievlaanderen/GIPOD#235]
Beste,
ik zie in staging dat onze grondwerken uit het huidige gipod bij conversie het type 'Riolering (deprecated)' hebben. Op het wijzigscherm-algemeen staat dat het type riolering niet meer ondersteund wordt. Zie de bijlage. Ik volg niet. We hebben dus gegevens die niet volledig geconverteerd zijn. Gezien de conversie morgen gebeurt, is dit redelijk dringen.
Bedankt alvast.
Mvg,
Luc.
[Conversie.docx](https://github.com/Informatievlaanderen/GIPOD/files/5840521/Conversie.docx)

**Comment by olivermay** [comment]
Dag Luc, 

Bij de migratie werden werkopdrachten met de aard "Werken aan riolering" overgezet naar het nieuwe GIPOD met het type "Riolering (deprecated)". Dit type is nog doorzoekbaar in het nieuwe GIPOD, maar bij wijzigingen en of nieuwe innames dient het nieuwe type "Riolering" gebruikt te worden. 

Ik ga nog even na wat de exacte reden hiervoor is, maar dit is alleszins beslist in samenspraak met de nutssector en gevalideerd door de businesswerkgroep. 

Concreet gaat er dus geen informatie verloren. Alle gemigreerde innames zullen het type "Riolering (deprecated)" krijgen. Voor nieuwe en gewijzigde innames dient het type "Riolering" geselecteerd worden in de GUI of doorgegeven via de API.

De boodschap bij de selectie van types is hierin mogelijk wel verwarrend, en ik kijk of dit verduidelijkt kan worden.

**Comment by AIV-Bert** [comment]
Closed due to inactivity
