### ISSUE TITLE
URL for accessing hindrance

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#237]
Will the urls to access hindrance immediately (e.g. /hinder/id) be available tomorrow? They are not working on beta. They seem to do on test.

**Comment by AIV-Bert** [comment]
Dag @berdienderoo,

This will be available tomorrow on production. Later today it will be avaolable on beta.
Example of url: https://gipod.vlaanderen.be/hinder/10033217

Kind regards,

Bert

**Comment by berdienderoo** [comment]
ok, thanks!
