### ISSUE TITLE
Synergie ontbreekt op GIPOD2

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#238]
Bij het rechtzetten van enkele gegevens op ons systeem heb ik gemerkt dat via de swagger API get synergie er geen spoor is van de synergie 9199655.  Nochtans is die wel raadpleegbaar via de oude GUI.

De SSA 6772243 en grondwerk 6769732 worden wel gevonden maar de synergie dus niet.
![SYN9199655 bestaat niet meer op nieuwe GIPOD swagger](https://user-images.githubusercontent.com/60095115/105329011-f7951580-5bd0-11eb-8b83-8978c7e1d5e1.jpg)
![SYN9199655 bestaat niet meer op nieuwe GIPOD](https://user-images.githubusercontent.com/60095115/105329014-f82dac00-5bd0-11eb-813a-0e00dcd300b0.jpg)

Kunnen jullie dit eens nakijken ?

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Dag Bert,

Probleem bij deze synergie is dat de piloot geen werkopdracht heeft in de synergie. Dit is niet volgens de business regels en heeft een import error gegegeven.

mvg,
Jürgen.

**Comment by AIV-Bert** [comment]
Closed due to inactivity
