### ISSUE TITLE
Sortering interessegebieden is random ipv alfabetisch

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#239]
![image](https://user-images.githubusercontent.com/38762917/105347142-c58eae00-5be6-11eb-9dd4-5ee2e385f751.png)

Is het mogelijk om deze lijst alfabetisch te sorten? Nu zit er geen logica in, wat het moeilijk maakt om te hanteren bij bv veel wisselen tussen interessegebieden.

Bedankt.

**Comment by AIV-Bert** [comment]
Dag @TomasVerheyen,

Dit is inderdaad zeer onhandig. We zullen dit aanpassen.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Today (28/01/2021 at 13:00) the UI hotfix 1.0.1 was released. This included a fix for your issue. https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing
