### ISSUE TITLE
Informatie (oa nauwkeurige plaatsbepaling) op niveau van synergieaanvraag

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#240]
Op niveau van synergieaanvraag is er nood aan het toevoegen van een beschrijving.
Deze kan op basis van het lancerende grondwerk (of één ervan, indien meerdere), of door evt bij mouse-over de info van het grondwerk weer te geven.

Op de huidige manier is een plaatsbepaling zeer moeilijk (bv randomstraat te deelgemeente van gemeente die te klein is voor op de kaart)
![image](https://user-images.githubusercontent.com/38762917/105347364-16060b80-5be7-11eb-846f-77242c3e17af.png)

**Comment by AIV-Bert** [comment]
Dag @TomasVerheyen,

Ik geef je feature request door aan de juiste persoon.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Jouw suggestie is toegevoegd aan de backlog. 

Alvast bedankt,

Bert
