### ISSUE TITLE
Importeren van geometrycollection werkt niet

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#241]
Hallo,
Je kan een multipolygoon inladen, maar bewaren lukt niet.
Dit geeft error.

De files zijn maw altijd correct, maar jullie aanvaarden ze niet.

Dit is een groot probleem, omdat het veel voorkomt dat er verschillende, niet grenzende, polygonen een grondwerk maken.

![image](https://user-images.githubusercontent.com/38762917/105359842-312d4700-5bf8-11eb-92c9-e1aca9978ed8.png)

**Comment by SilPal** [comment]
@olivermay 
Oliver, ik heb dit meermaals gevraagd in de meetings, en er is mij altijd gezegd dat de import meerdere polygonen zou toelaten.
Kan je bevestigen aub ?

Alvast bedankt.

**Comment by olivermay** [comment]
Kan je de WKT even doorsturen?

**Comment by olivermay** [comment]
Werkte het met diezelfde file op staging?

**Comment by TomasVerheyen** [comment]
WKT werkt ook niet op BETA
[NR11 Johan.zip](https://github.com/Informatievlaanderen/GIPOD/files/5849768/NR11.Johan.zip)

**Comment by TomasVerheyen** [comment]
Na wat aanpassingen lijkt het toch te lukken. 
Het is wel echter zo dat een QGIS naar WKT zonder manuele aanpassingen niet mogelijk blijft. 
Ik hoop dat GML support er snel komt.

**Comment by doomsju** [comment]
De WKT in bijlage is een geometrycollection. Wij aanvaarden enkel een polygon of multipolygon.

**Comment by doomsju** [comment]
Indien er een polygon of multipolygon is die jullie niet kunnen inladen kan je deze dan ook als bijlage koppelen?

**Comment by AIV-Bert** [comment]
Beste @TomasVerheyen,

De mogelijkheid om GML te importeren tijdens het intekenen in de UI wordt toegevoegd in de volgende release.
Hou onze aankondigingen of demo's in de gaten voor de exacte release date.

Met vriendelijke groeten,

Bert Lerno
