### ISSUE TITLE
Toelaten om te "openen in nieuw tabblad", ofwel via knop, ofwel door rechterklik

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#242]
![image](https://user-images.githubusercontent.com/38762917/105463545-83ba4200-5c90-11eb-85be-ee513e3fccad.png)

**Comment by AIV-Bert** [comment]
Dag @TomasVerheyen,

Dit is inderdaad niet het gewenste gedrag. We bekijken het.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Today (28/01/2021 at 13:00) the UI hotfix 1.0.1 was released. This included a fix for your issue. https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2363359568/Release+notes+GUI+webtoepassing

**Comment by TomasVerheyen** [comment]
Hallo Bert, 
Helaas lijkt dit nog steeds een probleem...
Kan je even nakijken?

Bedankt.

**Comment by AIV-Bert** [comment]
Hallo @TomasVerheyen,

Kan je even je lokale cache leegmaken door Ctrl+f5 in te drukken?

Ik kan dit niet meer reproduceren
![image](https://user-images.githubusercontent.com/55388892/106168161-440ec100-618e-11eb-8afd-822361aff083.png)

Met vriendelijke groeten,

Bert

**Comment by TomasVerheyen** [comment]
Hallo,
Excuses, het werkt nu wel.
Bedankt voor de bugfix!

**Comment by bertzor** [comment]
Graag gedaan ;)
