### ISSUE TITLE
Weergeven zoekfunctie en homeknop bij "smaller" scherm

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#243]
Hallo,
Ik werk oa met split screens, maar er is gekozen om in de dynamische layout de zoekvelden en homeknop te laten vallen. Een link naar vlaanderen blijft echter wel werkzaam, maar hier zie ik niet veel nut in.

Is er mogelijkheid om:
- knop vlaanderen wordt home knop
- zoekfunction blijft altijd zichtbaar
aanpassing te doen?

Bedankt.

![image](https://user-images.githubusercontent.com/38762917/105463772-d8f65380-5c90-11eb-91a9-da679cb3d3f2.png)
![image](https://user-images.githubusercontent.com/38762917/105463893-ff1bf380-5c90-11eb-9e65-f8af831faf34.png)

**Comment by AIV-Bert** [comment]
Dag @TomasVerheyen,

In welke browser werk je en hoe smal maak je het scherm? Ik kon dit niet meteen reproduceren.
![image](https://user-images.githubusercontent.com/55388892/105476197-a18fa300-5ca0-11eb-8515-05f1b4b66027.png)

Met vriendelijke groeten,

Bert

**Comment by TomasVerheyen** [comment]
@AIV-Bert van zodra je in bv een inname/synA/syn gaat, verandert de layout naar een zonder zoek/home knop.

**Comment by AIV-Bert** [comment]
Bedankt voor de toelichting ik kan dit nu reproduceren.

**Comment by AIV-Bert** [comment]
Dag @TomasVerheyen,

De fix voor deze bug staat nu op beta. Na validatie zal deze naar staging vloeien, en later naar productie

Met vriendelijke groeten,

Bert

**Comment by TomasVerheyen** [comment]
Beste,
Deze bug is nog steeds niet gefixt...

**Comment by AIV-Bert** [comment]
Beste,

Deze bug was wel degelijk gefixed op 12 maart, maar is dus terug.
We zullen dit bekijken maar heeft geen prioriteit.

Met vriendelijke groeten,

Bert
