### ISSUE TITLE
Hoe geven we via de api om een grondwerk aan te passen aan dat de periode om hele dagen gaat ?

### ISSUE THREAD

**Issue by user1862** [Informatievlaanderen/GIPOD#245]
Via de GUI kan je aangeven dat een periode betrekking heeft op een hele dag. Zie de rode cirkel in de bijlage. Kan dat worden aangegeven via de api en kunnen we de datums dan zonder uren doorgeven ook als de begin - en de einddatum gelijk zijn ?

Bedankt alvast.

Mvg,

Luc.
![Knipsel](https://user-images.githubusercontent.com/72242523/105471112-ab160c80-5c9a-11eb-9df9-e4ccdf0465b0.PNG)

**Comment by AIV-Bert** [comment]
Dag Luc,

De API ondersteunt dit niet, maar werkt met het exacte moment dat je ingeeft. Dus wil je 1 volledige dag, 24uur, kan je bv 2021-01-22 00:00 (start) en 2021-01-23 00:00 (einde) meegeven aan de API.

Wil je dus dezelfde functionaliteit als de website nabouwen in jouw applicatie kan dit met de mogelijkheden die de API voorziet. De optie in de UI is dus een hulpmiddel in de website, maar wordt naar de API toe vertaald naar een volledige dag, middernacht tot middernacht.

Met vriendelijke groeten,

Bert
