### ISSUE TITLE
Runtime problemen met geoselect

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#246]
Is er soms een probleem met de geoselect interface (nu aan de gang)?

We zijn nu aan het syncen met gipod/geoselect, en alle geoselect requests lijken te blijven staan in "InVerwerking".

Als voorbeelden van geoselect taskIds die blijven hangen: 9c3eef20fd3741b69cace7e61d8f7ac3, 8b25f7034e6b448880f0f44e83f689e2, 9466d38803bd425da117cda8a2761691

mvg,
Sven

**Comment by AIV-Bert** [comment]
Dag Sven,

We ondervinden een zware load op de service. We bekijken dit momenteel. Ik kan alvast melden dat de taken niet vast zitten, maar heel traag verwerkt worden.

Met vriendelijke groeten,

Bert

**Comment by doomsju** [comment]
Performantie problemen zouden moeten opgelost zijn.
