### ISSUE TITLE
Toegang tot GIPOD new beta

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#247]
Ik slaag er niet in om in te loggen op GIPOD new beta omgeving, is ze nog on-line ?
![image](https://user-images.githubusercontent.com/70695400/105485897-df46f880-5cad-11eb-816f-ef9832f353dc.png)

**Comment by AIV-Bert** [comment]
Dag @SilPal,

De beta omgeving is zeker online en werkt.
Hou er zeker rekening mee dat de oude URL new.beta.gipod.vlaanderen.be donderdag vervangen werd door https://gipod.beta-vlaanderen.be/

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Dag @SilPal,

Ik heb jouw issue nog even verder bekeken deze avond. De aanpassing aan de beta omgeving werden samen met de productie release uitgevoerd. Ik zie in onze interne kanalen dat dit echter nog niet gecommuniceerd was en dus nog niet uitgevoerd mocht worden. Er is een redirect voorzien vanuit de new.beta.gipod.vlaanderen.be maar jullie hebben natuurlijk de firewall nog niet kunnen aanpassen. Lukt dit alsnog?

Sorry voor het ongemak en vriendelijke groeten,

Bert

**Comment by SilPal** [comment]
@AIV-Bert 
denk dat het OK is, maar er was wat verwarring omdat de oude beta ook nog on-line staat 
![image](https://user-images.githubusercontent.com/70695400/105850097-91016480-5fe1-11eb-830e-3d87af711c97.png)

**Comment by bertzor** [comment]
Bedankt voor de feedback.

**Comment by AIV-Bert** [comment]
Bedankt voor de feedback.

**Comment by SilPal** [comment]
@AIV-Bert 
IT vraagt mij de "source IP details". Kan jij me die bezorgen ?

Alvast bedankt.
