### ISSUE TITLE
Melding "synA niet beantwoord"

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#248]
Ik ben niet op de hoogte van wat er nog in de pijplijn zit.
Maar in geval van onvoorziene omstandigheden lijkt het mij wel handig dat er evenzeer een lijst is van synA waar antwoord werd verwacht, maar niet tijdig werd gegeven.

Dit kan dus zowel zijn:
- synA - U hebt geen antwoord gegeven voor DL1
als
- synA - U hebt geen grondwerk gekoppeld voor DL2

![image](https://user-images.githubusercontent.com/38762917/105488863-9cd3ea80-5cb2-11eb-9c56-2a250f5af29e.png)

**Comment by olivermay** [comment]
Dag Thomas, 

Deze notificaties werden in overleg met de business werkgroep vastgelegd, concreet rond synA DL1 en DL2 zijn deze als volgt:

- DL1: De notificatie wordt uitgestuurd 3 dagen voor het verstrijken van deadline 1 en is zichtbaar gedurende 5 dagen na notificatie of tot het beantwoorden door de organisatie die de notificatie ontving.
- DL2: De notificatie wordt uitgestuurd 5 dagen voor het verstrijken van deadline 2 en is zichtbaar tot deadline 2, of tot het beantwoorden door de organisatie die de notificatie ontving.

De notificaties zullen dus steeds 5 dagen zichtbaar zijn, indien niet gereageerd wordt. 

Daarnaast is het ook mogelijk om de vervallen (of gearchiveerde) notificaties te alsnog op te vragen. We hebben, op basis van gebruikersfeedback, bewust gekozen om het aantal notificaties net te beperken. 

Ik neem je suggestie wel mee als feedback, zodat we dit eventueel kunnen terugkoppelen naar de werkgroepen.
