### ISSUE TITLE
Error "inname bestaat niet" bij nee beantwoorden actieve synA

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#249]
Omschrijving collega: (betreft synA [https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/11215926]) 
Goeiemorgen Tomas,

Als ik negatief probeer te antwoorden op gipod 8992766 dan krijg ik een foutmelding.
Screenshot zit in bijlage.
Hij probeert steeds naar een oude gipod terug te koppelen, geen idee waarom hij dit doet. Ik heb hiervoor die oude gipodnummer alleszins niet bezocht.

Momenteel geprobeerd met chrome en edge, beiden laten me geen wijziging toe.

Misschien een algemene bug dat doorgegeven moet worden?

Bedankt en groeten,
![foutmelding](https://user-images.githubusercontent.com/38762917/105680200-b01fc980-5eef-11eb-9c81-b2951d678a2e.png)

**Comment by olivermay** [comment]
Er is momenteel een storing op de productie omgeving, waardoor heel recente innames niet opgevraagd kunnen worden. Er wordt aan gewerkt.

**Comment by doomsju** [comment]
Dit zou ondertussen op productie moeten opgelost zijn. 
We werken aan een hotfix om het probleem in de toekomst te vermijden.

**Comment by olivermay** [comment]
Kan je bevestigen dat het terug correct werkt @TomasVerheyen ?

**Comment by TomasVerheyen** [comment]
> Kan je bevestigen dat het terug correct werkt @TomasVerheyen ?

Werkt nu wel voor bovenvermelde synA (y)
Bedankt.
