### ISSUE TITLE
Niet mogelijk om SSA aan te maken via Swagger

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#25]
Hallo,

Momenteel is het niet mogelijk om een SSA aan te maken via de Swagger op een grondwerk dat door ons werd aangemaakt in de suborganisatie "Fluvius Dilbeek".  vb, ID 10136235 Ik krijg de boodschap "User needs to be belong to the owner organisation to perform this action".

In het verleden was me dit wel gelukt met een grondwerk in de hoofdorganisatie Fluvius, maar we gaan nu alles op suborganisatie ingeven.   De autorisatie token die ik gebruik bevat "gipod_ts_write", dus ik zou normaal toegang moeten hebben.

Kunt u dit nakijken ?

Met vriendelijke groeten,
Bert De Groote

**Comment by doomsju** [comment]
Dag Bert,

We hebben dit vandaag gefixt op de Beta omgeving.

https://github.com/Informatievlaanderen/GIPOD/issues/26

met vriendelijke groeten,
Jürgen.
