### ISSUE TITLE
Inname bij te behandelen, onbehandelbaar wegens verwijderd

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#250]
Na migratie is alles goed verlopen, behalve bij deze:
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/9240145

Die komt terug in mijn lijst te behandelen, maar bestaat niet
![image](https://user-images.githubusercontent.com/38762917/105702000-6c3abd80-5f0b-11eb-9d6d-3f64397208dc.png)
![image](https://user-images.githubusercontent.com/38762917/105702023-7361cb80-5f0b-11eb-8e66-ce1485bb4737.png)

**Comment by AIV-Bert** [comment]
Beste @TomasVerheyen,

Deze aanvraag werd ingetrokken en moest meteen uit je lijst verdwijnen. Door een kleine vertraging, bleef deze nog in je lijst staan, wanneer deze al niet meer te raadplegen was.
Dit zou niet langer mogen voorkomen. Indien je toch nog een issue hebt, contacteer ons dan zeker en vermeld ook even de sub-organisatie die problemen heeft.

Met vriendelijke groeten,

Bert
