### ISSUE TITLE
DELETE on contact organisation fails

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#251]
When we retrieve the contact organisations for the GIPOD GroundWork with id: 6825771
we get back the following list:
/api/v1/trench-synergies/9192307/contactorganisations/2f5bbc70-879b-46ee-be1b-fd4bf4f2763d
/api/v1/trench-synergies/9192307/contactorganisations/0aa7b3e1-10ac-4183-ba34-a4324dc6076e
/api/v1/trench-synergies/9192307/contactorganisations/2be6cf81-2778-4719-bc1d-8a8aacaae27d
/api/v1/trench-synergies/9192307/contactorganisations/89c58c78-d4c0-4cbd-a1ca-5f3a7af44342
/api/v1/trench-synergies/9192307/contactorganisations/7cd6b2e7-a58f-4a67-ac69-33a744abfb25

however when we try to remove the groundwork contact organisation with a 
DELETE to  /api/v1/trench-synergies/9192307/contactorganisations/0aa7b3e1-10ac-4183-ba34-a4324dc6076e we get back a HTTP 404
{"type":"https://httpstatuses.com/404","title":"The requested resource could not be found.","status":404,"detail":"Contactorganisation with 0aa7b3e1-10ac-4183-ba34-a4324dc6076e does not exist"}

**Comment by AIV-Bert** [comment]
Hi @langens-jonathan 

Could you provide us with the correlation id from the request that is failing for you?

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
Hi @langens-jonathan,

This bug occurs when deleting contactorganisations on a synergy that is imported from the old Gipod system. We are working on a hotfix to resolve this as soon as possible.

Kind regards,

Bert

**Comment by langens-jonathan** [comment]
Thank you, 

we just identified another instance of this bug:
{"type":"https://httpstatuses.com/404","title":"The requested resource could not be found.","status":404,"detail":"Contactorganisation with 54a70ff3-8365-4ae5-aa40-2a6a22fcd70b does not exist"}

**Comment by AIV-Bert** [comment]
Tonight (26/01/2021 19:00) the API hotfix 1.0.2 is released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2355532566/Hotfixes+1.0.x

**Comment by AIV-Bert** [comment]
Could you confirm your issue is resolved?

**Comment by langens-jonathan** [comment]
Hey Bert

I confirm that the issue is resolved.

Thanks!
Jonathan

**Comment by AIV-Bert** [comment]
Thanks you for your feedback!
