### ISSUE TITLE
Feedback: intekenen nieuw GW : andere polygonen op de map

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#252]
**Is your feature request related to a problem? Please describe.**
Wanneer we een nieuw GW aanmaken, zie je op de kaart alle polygonen in de buurt, hetgeen het aanmaken moeilijk maakt. 

**Describe the solution you'd like**
Het zou handig zijn als die laag met andere polygonen per default afstaat en dat je ze kan opzetten als je dat wenst. Een filter op bvb. periode, beheerder, status,... zou ook handig zijn in dat geval.
![image](https://user-images.githubusercontent.com/70695400/105850693-59df8300-5fe2-11eb-8caf-ebff96993ab8.png)

**Comment by TomasVerheyen** [comment]
+1 
Die layer mogen overal beschikbaar zijn.

**Comment by AIV-Bert** [comment]
Release 1.1.0 voegt de mogelijkheid toe om deze layers af te zetten.
