### ISSUE TITLE
refresh probleem

### ISSUE THREAD

**Issue by SilPal** [Informatievlaanderen/GIPOD#253]
Als je een GIPOD ID geopend hebt en je geeft een nieuw GIPOD ID in via de zoekbalk en je drukt enter, dan blijft de zone van het vorige GW op het scherm staan. Je moet het scherm refreshen vooraleer je de correcte GW-polygoon ziet

**Comment by AIV-Bert** [comment]
Release 1.1.0 lost dit probleem op.
