### ISSUE TITLE
Period update not possible for GW=3384903 even though the GRB impact=Geen GRB afwijking.

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#254]
**Describe the bug**
Period update not possible for GW=3384903 even though the GRB impact=Geen GRB afwijking.

**Expected behavior**
GW period update should be possible.

**Correlation id and request**
curl -X PATCH "https://private-api.gipod.vlaanderen.be/api/v1/groundworks/3384903" -H "accept: application/json" -H "Authorization: Bearer ij9WS1gM/TGaFp8Urcki0A==" -H "Content-Type: application/json" -d "{\"items\":[{\"key\":\"Period\",\"value\":{\"start\":\"2021-01-26T00:00Z\",\"end\":\"2021-01-26T21:59Z\"}}]}"

x-correlation-id: f864afc8-59da-4332-af78-8e139c9c6ad4 .

**Comment by AIV-Bert** [comment]
Hi @rajeevchugh71,

Thanks you for this detailed bug report. We will look into this.

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
Hi @rajeevchugh71,

I got an update for you. We found the issue and this will be fixed in hotfix 1.0.3 tonight. 

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
Today (27/01/2021 at 15:00) the API hotfix 1.0.3 was released https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/2355532566/Hotfixes+1.0.x

Could you confirm this resolves your issue?

**Comment by rajeevchugh71** [comment]
Indeed, our issue is solved.

Thanks a lot @AIV-Bert !

**Comment by AIV-Bert** [comment]
You are welcome. Thank you for confirming the fix!
