### ISSUE TITLE
GW period-status rules do not apply to SYN.

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#255]
**Describe the bug**
(Urgent & blocking issue)
GW period-status rules do not apply to SYN. For ex  SYN start date can be set in past whereas a normal GW start date cannot be set in the past in combination with status=Concretely planned & same for other statuses.

**Expected behavior**
SYN GW start dates should not be allowed to be in the past.

![PXS-concretely-plan-issue-1](https://user-images.githubusercontent.com/65851740/105967504-33732380-6086-11eb-9bc6-2d60aa791d1f.jpg)
![PXS-concretely-plan-issue](https://user-images.githubusercontent.com/65851740/105967508-340bba00-6086-11eb-986a-1918b11e4f65.jpg)

**Correlation id and request**
See attachments.

**Comment by AIV-Bert** [comment]
Hi @rajeevchugh71,

 I agree this would be an improvement to the api. But in essence, you are requesting extra validation on the SYN period.
 This is something with high impact to all users. We need to analyze the impact before we can make a commitment to resolve this issue for you.
 
 Kind regards,
 
 Bert

**Comment by TomasVerheyen** [comment]
> Hi @rajeevchugh71,
> 
> I agree this would be an improvement to the api. But in essence, you are requesting extra validation on the SYN period.
> This is something with high impact to all users. We need to analyze the impact before we can make a commitment to resolve this issue for you.
> 
> Kind regards,
> 
> Bert

Hello Bert,

I hope you understand that we need to keep a continuity between a groundwork and linked synergie if we are the pilot, or if someone else is the pilot.
This creates issues, where a synergy will obtain a different, wrong set of data in accordance to the groundwork, because we can not push the same "wrong" items to a groundwork...

I think this is a serious oversight, therefore should be relabeled as urgent, not as a feature request.

Thank you.

**Comment by AIV-Bert** [comment]
Hi @TomasVerheyen,

Thank you for your additional feedback. We did not label this issue yet as we are still analyzing this at this very moment. I was just providing an update to the initial request :)

Kind regards,

Bert

**Comment by naomioste** [comment]
Dag @TomasVerheyen 

we nemen dit apart op met jou en Silvie.
Kwestie van het probleem goed te begrijpen en een robuuste oplossing samen uit te werken.

Groeten,
Naomi
