### ISSUE TITLE
Grondwerk met verkeerde organisatie

### ISSUE THREAD

**Issue by castersjef** [Informatievlaanderen/GIPOD#257]
Goedemorgen,

Na de migratie zien we dat voor een aantal innames in WERF de GIPOD werken en grondwerken aan een organisatie (De werkvennootschap) hangen die niet rechtstreeks een suborganisatie zijn van AWV.
gipodId=7163003
gipodId=9018577
gipodId=9018578

Deze grondwerken en de hinder die er aan vast hangt behoort tot de organisatie de Werkvennootschap (die geen suborganisatie is van AWV)

Is het mogelijk om deze Grondwerken/Werken en de hinder ervan de verplaatsen naar de organisatie "De werkvennootschap" die onder AWV valt. (idem voor Lantis)

Groeten,
Jef

**Comment by olivermay** [comment]
Dag Jef, 

we hebben dit via mail verder uitgeklaard, en we volgen het daar op. 

mvg, 

Oliver
