### ISSUE TITLE
Error regarding InvalidMobilityHindranceStatus

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#259]
For our integration we sometimes see the error 'InvalidMobilityHindranceStatus' (The specified condition was not met for 'StatusId'.","detail":"StatusId"). 
However, this is not a structured error, so sometimes it appears for an action and sometime it doesn't.

We saw this error e.g. when updating the period of an intake and mobility hindrance (period in the future to another period in the fucture, the status was Concreet gepland and gevalideerd before the update). We had the same error when updating the status of an intake and mobility hindrance from niet-concreet gepland & in opmaak to concreet gepland & gevalideerd.

Sometimes it happens that retrying the same action after some moments is successfull (Nothing changed in the meantime).

Details of one of the cases:

2021-01-29 14:09:12,842 We try to update WORK: 11227002 (set status)
2021-01-29 14:09:12,941 We get the following error:  {"type":"https://httpstatuses.com/400","title":"One or more validation errors occurred.","status":400,"detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:InvalidMobilityHindranceStatus","title":"The specified condition was not met for 'StatusId'.","detail":"StatusId"}]}

Can you help us figuring out why it sometimes fails and sometimes works?

**Comment by berdienderoo** [comment]
Is there any update on this?

**Comment by AIV-Bert** [comment]
Hi @berdienderoo,

Sorry for this very late reaction.

I cannot find any failed request for this ID, nor am I able to find any failed patch request within this timeperiod 29/1/2021 14:00 - 15:00.

It is best to provide the CorrelationId. You receice this correlationId in every response. This points us the the exact request you have issues with. 

Could you provide us with a correlationId for a request that has this issue?

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
Hi @berdienderoo,

I would love to investigate this issue for you further. Any chance you had this issue again and could provide a correlationid?

Kind regards,

Bert
