### ISSUE TITLE
Rapporteringstool over innames

### ISSUE THREAD

**Issue by user1862** [Informatievlaanderen/GIPOD#260]
Beste, Aquafin laadt de nodige gegevens uit gipod op in een eigen rapporteringssysteem. Dat gebeurt via de klassieke api's maar dat zijn er sinds de upgrade van gipod wat meer geworden. Gevolg: slechte performantie en verlies van data. Kan er geen rapporteringstool worden voorzien waarbij in bulk grote hoeveelheid kunnen worden opgevraagd over innames, contacten, grondzones en de andere gegevens ? Staat er in die zin iets op de planning ? Bedankt. Mvg, Luc Boon, Aquafin.

**Comment by AIV-Bert** [comment]
Beste @user1862,

Kan je een voorbeeld geven van de slechte performantie en het verlies van data? Dit lijkt me een zeer belangrijke issue, maar staat ver af van wat onze monitoring aantoont. Enkele voorbeelden zouden dus handig zijn.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Closed due to inactivity
