### ISSUE TITLE
Synergie : overdracht pilootschap komt niet te voorschijn indien je url van de synergie gebruikt

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#261]
![image](https://user-images.githubusercontent.com/47108018/106485098-88f96700-64b0-11eb-94c6-390df0c9242c.png)

Verwacht : als je als gebruiker onder je suborganisatie de synergie van je suborganisatie via de url raadpleegt moet je dadelijk ook het scherm zien met de mogelijkheid te koppelen grondwerken en overdracht pilootschap.
https://gipod.vlaanderen.be/samenwerking/synergie/9210202
dit is nu niet het geval, je moet via het grondwerk en sav en dan naar de synergie gaan of met toeval een refresh doorvoeren wat dit dan wel mogelijk wordt (maar niet steeds). Dit is verwarrend.

**Comment by naomioste** [comment]
Dag Jan,

dit lijkt idd een bug te zijn, ik geef het door aan het technisch team. 
Als workaround kan je wel het ID van de synergie in het zoekveld in de menubalk plakken, dan lukt het wel.

Groeten,
Naomi

**Comment by AIV-Bert** [comment]
Dag @JanDegroote,

Deze fix staat nu op beta. Dit zal na validatie naar staging en later naar productie gebracht worden.

Met vriendelijke groeten,

Bert
