### ISSUE TITLE
Status of intake not in line with period

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#262]
**Describe the bug**
For intake 11226720, the status is still concreet gepland, while it should be in uitvoering.

**Expected behavior**
Status should be in uitvoering

Why is the status not updated?

**Comment by AIV-Bert** [comment]
Hi @berdienderoo,

The period is not updated because the owner has not updated the period.
Gipod does not automatic change data.  The owner will need to update the period or status.

Kind regards,

Bert

**Comment by berdienderoo** [comment]
Hi,

I now indeed can reproduce this on the beta environment. I thought that there was a process in GIPOD² to update the status of intakes according to their period, but this seems not be the case.
Is this the same for intakes created through the UI? 
I think that this may cause a lot of the intakes to be in the wrong status, because they won't be updated to 'in uitvoering' or 'uitgevoerd' by the creator.

Berdien
