### ISSUE TITLE
Patch information not reflected in the GIPOD data but a HTTP 201 was returned nevertheless

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#264]
**Describe the bug**
on 22/01/2021 at 9:40 we made a PATCH request to GIPOD to update the period for GroundWork 8142157 to be from the 22/01/2021 0:00Z to 22/01/2021 21:59Z
The response to the PATCH was HTTP 201
However when we retrieved the data on 22/01/2021 at 9:45 (5 minutes later) the period wasn't updated yet.

**Expected behavior**
After an HTTP 201 we expect the data to be updated.

**Additional context**

**Correlation id and request**

**Comment by doomsju** [comment]
In onze logs kunnen wij niet zo'n grote vertraging opmerken. Er kan een kleine vertraging zijn voor het lezen maar het resultaat was na max +/- 1 sec beschikbaar. We hebben wel gezien dat er 2 PATCH requests zijn geweest één om 9u40 & één om 9u45. Bij beide requests werd de periode aangepast.

**Comment by AIV-Bert** [comment]
Closed due to inactivity
