### ISSUE TITLE
Grondwerken categorie 3 waarbij het huisnummer niet gekend is, enkel straat, postnr, gemeente

### ISSUE THREAD

**Issue by burggma** [Informatievlaanderen/GIPOD#265]
Voor de kleine grondwerken met deze kenmerken, plus zijnde een werk van zeer korte duur, aangeleverd via de API: is het ok dat de geometrie van het midden van een straat wordt meegegeven als zone/als punt? 
Concreet voorbeeld: een lek in een straat ergens landelijk, zonder een huis in de buurt. 
Indien dit niet ok zou zijn, dan zal voor zulke werken iemand intern manueel de exacte locatie van het grondwerk dienen aan te duiden op een kaartje, vooraleer doorstroming via de API richting GIPOD.  Alvast bedankt.

**Comment by naomioste** [comment]
Dag @burggma ,

ingeven als punt is ok voor deze cat3 grondwerken (<3m²) als de exacte zone niet gekend is op voorhand. Steden en gemeenten willen vooral weten wie waar gewerkt heeft (mochten er later vragen zijn of problemen opduiken), en dat lukt ook met een punt als locatie of een zone die ongeveer juist is en de periode van de werken.
