### ISSUE TITLE
Verplichte aanpassing op twee tabs onmogelijk in orde te krijgen via GUI

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#266]
Voorbeeld: https://gipod.vlaanderen.be/inname/2580296/wijzig#timing_en_locatie
Deze is uitgevoerd, maar als ik dit wil aanpassen op tab timing & locatie, krijg ik een error op de tweede tab. Ik kan echter niet tussen de twee wisselen zonder verandering te bewaren, wat dus niet lukt omwille van error op andere tab.

1.
![image](https://user-images.githubusercontent.com/38762917/106911115-2b5c5900-6702-11eb-9164-8163e3845c23.png)
2.
![image](https://user-images.githubusercontent.com/38762917/106911202-37e0b180-6702-11eb-8567-32cb83668b36.png)
3. error
![image](https://user-images.githubusercontent.com/38762917/106911275-429b4680-6702-11eb-9a2b-bee53f29397e.png)

Ditto voor de andere...
![image](https://user-images.githubusercontent.com/38762917/106911389-62326f00-6702-11eb-9e79-e638e469320d.png)

**Comment by AIV-Bert** [comment]
Dag @TomasVerheyen,

Dit is een gekende issue. We werken momenteel (deze sprint) aan een oplossing.

Als je dringend de aanpassing wil doorvoeren kan je volgende stappen uitvoeren:
1. Aanpassen status en datum naar In uitvoering met geldige datum voor die status
2. Aanpassen GRB impact
3. Aanpassen status en datum naar de correcte status en datum.

Met vriendelijke groeten,
Bert

**Comment by AIV-Bert** [comment]
Release 1.1.0 heeft dit opgelost door GRB impact te verplaatsen.
