### ISSUE TITLE
Probleem om statusverandering en grb-impact in te brengen.

### ISSUE THREAD

**Issue by user1862** [Informatievlaanderen/GIPOD#267]
Beste,

Zie de bijlage voor een detaillering van de bug.
[bug gui gipod 20 01.docx](https://github.com/Informatievlaanderen/GIPOD/files/5930792/bug.gui.gipod.20.01.docx)

Dit probleem werd op 26/01 via mail gemeld aan Olivber May.

Bedankt alvast.

Mvg,;

Luc

**Comment by olivermay** [comment]
De GRB impact wordt aangepast deze sprint, deze zal op dezelfde tab komen te staan als de timing en status.

Dit zal normaalgezien op het vragenuurtje van 15 februari gedemonstreerd worden.

**Comment by AIV-Bert** [comment]
Duplicate of #266
