### ISSUE TITLE
Innames kunnen niet meer geraadpleegd worden

### ISSUE THREAD

**Issue by castersjef** [Informatievlaanderen/GIPOD#269]
**Describe the bug**
Omgeving: BETA

Innames staan in lijst met overzicht innames
wanneer er op wordt doorgeklikt 
![image](https://user-images.githubusercontent.com/37434828/108983313-04ed6600-768f-11eb-9772-522d3640cf62.png)

Response van API: /api/v1/groundworks/{gipodId}

`
{
  "type": "https://httpstatuses.com/404",
  "title": "The requested resource could not be found.",
  "status": 404,
  "detail": "No groundwork found for GipodId: 10330782."
}
`

**Expected behavior**
Innames kunnen geopend worden en opgehaald via API

**Additional context**
probleem komt voor voor innames in eigen beheer als voor externe organisaties

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by AIV-Bert** [comment]
Beste @castersjef,

We bekijken dit meteen. Kan je even de omgeving toevoegen? Ik vermoed BETA want op de andere omgevingen bestaat deze ID niet.

Met vriendelijke groeten,

Bert

**Comment by castersjef** [comment]
@AIV-Bert , is inderdaad in beta. Het probleem stelt zich voor iedere inname die we probeerde. Zowel voor AWV als voor andere organisaties

**Comment by AIV-Bert** [comment]
Beste @castersjef,

Dit zou terug opgelost moeten zijn.

Met vriendelijke groeten,

Bert

**Comment by castersjef** [comment]
Bedankt voor de hulp.

**Comment by castersjef** [comment]
Goedemorgen @AIV-Bert ,

Sinds vanmorgen kunnen we onze innames niet meer raadplegen in GIPOD (beta)
https://gipod.beta-vlaanderen.be/inname/10360670
![image](https://user-images.githubusercontent.com/37434828/114362663-df9db400-9b77-11eb-8200-35891623d6eb.png)

**Comment by SilPal** [comment]
@AIV-Bert : Zelfde probleem bij Proximus : https://gipod.beta-vlaanderen.be/inname/10361080

**Comment by AIV-Bert** [comment]
Beste, @castersjef en @SilPal,

De website maakt gebruik van het endpoint '/api/v1/entities'. Dit endpoint gaf de nieuw aangemaakte innames niet langer terug. Dit is nu terug opgelost. 

Met vriendelijke groeten,

Bert
