### ISSUE TITLE
Get TrenchSynergieRequest verwarrende veldnamen.

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#27]
Geen groot probleem maar de tags vind ik wel een beetje verwarrend.  
 Je start deze API op met 2 parameters : "The GipodId of the groundwork" en "trench synergy request id".
In het resultaat krijg je dan de tag "GipodID" maar deze bevat dan het "trench synergy request id".
Het "GipodID of the groundwork" zit dan in "launchingGroundwork".

**Comment by doomsju** [comment]
The GipodId slaat altijd op de resource die je opvraagt. Dit zullen we niet meer wijzigen.
