### ISSUE TITLE
Formaat and maximum aantal punten in Geometrie collaborationzone

### ISSUE THREAD

**Issue by castersjef** [Informatievlaanderen/GIPOD#270]
Goedemiddag,

Wij zijn op dit moment bezig met de integratie van de synergie aanvragen in de applicatie WERF.
Wij zouden een aantal samenwerkingszones willen intekenen voor enkele van onze suborganisaties.

In de documentatie staat dat voor de zone een "string" nodig is. Is dit de geometrie in WKT formaat?
Zit er een limiet op het aantal punten dat in deze geometrie mag zitten? 
Is het ook mogelijk om meerdere geometrieën door te geven?

Een verdere praktische vraag, hoe testen wij dit het best? 
Welke rechten zijn hier voor nodig?
Als we dit via de API proberen:
```
{
  "type": "https://httpstatuses.com/403",
  "title": "Not allowed to perform the operation.",
  "status": 403,
  "detail": "Insufficient permissions to perform the operation."
}
```
Kunnen wij met één suborganisatie een samenwerkingsgebied intekenen en met een andere organisatie een synA lanceren of is er een 'dummy' account die als externe partij zou kunnen dienen?

Met vriendelijke groeten,
Jef

**Comment by AIV-Bert** [comment]
Beste @castersjef,

Je kan per organisatie 1 samenwerkingszone instellen. Op basis van deze zone zal je al dan niet synergie-aanvragen ontvangen. Om  een synergie-aanvraag mee te beantwoorden (al dan niet deelnemen) hoef je deze niet noodzakelijk ontvangen hebben. Je bent vrij om aan iedere synergie-aanvraag deel te nemen, onafhankelijk van je samenwerkingszone.

De samenwerkingszone moet je in WKT-formaat aanleveren aan de API. Op het aantal punten staat geen harde limiet. Je kan meerdere geometrieën meegeven onder de vorm van een multipolygoon.

Om de samenwerkingszone in te stellen heb je de scope 'gipod_org_settings' nodig.

Je kan met 1 sub-organisatie een samenwerkingszone instellen en met een andere een synergie-aanvraag lanceren. De beta omgeving heeft echter ook 3 organisaties 'Blauw', 'Groen' en 'Oranje' die je kan gebruiken om mee te testen.

Met vriendelijke groeten,

Bert Lerno
