### ISSUE TITLE
Geen organisatie in GUI bij GW > aanpassingen niet mogelijk via GUI

### ISSUE THREAD

**Issue by TomasVerheyen** [Informatievlaanderen/GIPOD#271]
Sinds gisteren is de eigenaar van het grondwerk in de GUI verdwenen.
Bijgevolg zijn er ook geen aanpassingen mogelijk.

BV
![image](https://user-images.githubusercontent.com/38762917/109771319-f78b2b00-7bfc-11eb-8cf5-a55dd02f1a7b.png)
![image](https://user-images.githubusercontent.com/38762917/109771345-feb23900-7bfc-11eb-8df1-92957312e6cd.png)

Via API is dit wel nog correct:
![image](https://user-images.githubusercontent.com/38762917/109771430-125d9f80-7bfd-11eb-9a88-6b0cb04efaf8.png)

**Comment by AIV-Bert** [comment]
Beste @TomasVerheyen,

Dit zal een caching issue zijn. Kan je even Ctrl + F5 uitvoeren op deze pagina?

Met vriendelijke groeten,

Bert

**Comment by TomasVerheyen** [comment]
Hallo Bert,

Jazeker. Werkt opnieuw. 
Bizar, was bij andere gebruikers ook het geval.

Bedankt!
