### ISSUE TITLE
Niet langer mogelijk ‘Planning en Periode lopen gelijk met synergie’ aan te vinken voor Grondwerken in de nieuwe GIPOD UI

### ISSUE THREAD

**Issue by burggma** [Informatievlaanderen/GIPOD#272]
De functie voor het aanvinken van de functie ‘Planning en Periode lopen gelijk met synergie’ op de Grondwerken lijkt niet meer voorzien te zijn in de nieuwe webapplicatie. Wat is de rede hiervan? Is dat de Periode en Planning van een Grondwerk niet meer belangrijk is (en dus niet moet aangepast worden) als er een effectieve synergie is aangemaakt?

**Comment by AIV-Bert** [comment]
Beste @burggma,

Suggesties zoals deze kan je best doen via de Feedback knop op https://gipod.vlaanderen.be/
Dit leidt je naar de pagina waar je kan stemmen op suggesties of zelf nieuwe aanmaken (https://gipod.nolt.io/roadmap/).

De periode en planning van een grondwerk blijft weldegelijk belangrijk. Als je deze feature in de website wil zien, kan je dus best dit melden via onze feedback tool.

Met vriendelijke groeten,

Bert
