### ISSUE TITLE
Foute tijdspanne voor GIPOD-dossier in Hinder In Kaart applicatie

### ISSUE THREAD

**Issue by ndldddd** [Informatievlaanderen/GIPOD#276]
Er werd een evenement aangemaakt (GIPOD-id=11297128) met tijdsduur en bijbehorende hinder van 06:00-18:00. Bij consultatie van de Hinder in Kaart applicatie wordt incorrect aangegeven dat de hinder voor dit dossier plaatsvindt tussen 04:00 -16:00, ook nadat wijzigingen in het dossier opnieuw worden opgeslagen. Dit lijkt een bug te zijn.

**Comment by AIV-Bert** [comment]
Dag @ndldddd,

Deze bug is opgelost en de data die fout stond is terug aangepast.

Bedankt voor je melding.

Met vriendelijke groeten,

Bert
