### ISSUE TITLE
500 error bij aanmaken collaborationzone

### ISSUE THREAD

**Issue by castersjef** [Informatievlaanderen/GIPOD#277]
Beste,

Wij proberen een samenwerkingszone aan te maken in DEV maar krijgen een 500 unexpected error bij het uitvoeren van de request.
{
  "type": "https://httpstatuses.com/500",
  "title": "Unexpected error.",
  "status": 500,
  "detail": "An unexpected error occurred. Please retry or contact the service administrator."
}

In bijlage de multipolygoon die we proberen aan te maken.

[example.wkt.txt](https://github.com/Informatievlaanderen/GIPOD/files/6188181/example.wkt.txt) (.txt toegevoegd aangezien github geen .wkt aanvaard)
 

Indien het bestand wordt opgeladen via de GUI wordt de samenwerkingszone wel getoond maar kan niet worden opgeslagen.
![image](https://user-images.githubusercontent.com/37434828/112118934-29b8f880-8bbd-11eb-846c-b079c30f3bf0.png)

**Comment by jonas-db** [comment]
Ik merk trouwens ook dat als ik 2 overlappende polygonen teken en deze bewaar dat die 2 gesimplified worden naar 1 polygoon.
Wij zitten mogelijks aan 10000den polygonen dus misschien ligt het daar aan?

**Comment by AIV-Bert** [comment]
Overlappende polygonen worden inderdaad niet ondersteund. In de UI worden deze samengevoegd.

We bekijken de issue verder.

**Comment by jonas-db** [comment]
Bedankt!

Ik heb ondertussen de overlappende polygonen verwijderd door alles te simplifyen, maar ik blijf nog steeds een 500 terugkrijgen met volgende file:


[dump-20m.wkt.txt](https://github.com/Informatievlaanderen/GIPOD/files/6190996/dump-20m.wkt.txt)

**Comment by castersjef** [comment]
@AIV-Bert, heb jij al een idee wanneer dit mogelijks zou opgelost zijn?

**Comment by AIV-Bert** [comment]
Dag @castersjef,

We werken hier momenteel aan, maar er is nog verder onderzoek nodig. We behandelen deze blocking issue prioritair.

Ik post hier een update zodra de fix op beta of staging komt.

Met vriendelijke groeten,

Bert

**Comment by castersjef** [comment]
Dag @AIV-Bert,

Ik ga hier nog eens op moeten terugkomen omdat deze fout onze ontwikkelingen met betrekking tot synergie aanvragen blokkeert. 
Wordt er momenteel gewerkt aan de oplossing of staat dit op de backlog om opgenomen te worden? 

Bedankt,
Jef

**Comment by AIV-Bert** [comment]
Dag @castersjef,

Er wordt hier jammer genoeg nog altijd aan gewerkt. Eenmaal de 'grote' zone opgeladen werd op onze test omgeving, kwamen er nog andere issues aan het licht bij het gebruik van deze zone. We werken er momenteel hard aan, want we willen dit inderdaad zo snel mogelijk vin orde brengen.

Zodra de fix door de QA is, releasen we een hotfix op de productie omgeving.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Dag @castersjef,

Er zijn reeds enkele wijzigingen gereleased. Dit zou al een verbetering moeten geven voor jou. Het is nog niet perfect, maar we onderzoeken verdere verbeteringen.

Met vriendelijke groeten,

Bert

**Comment by jonas-db** [comment]
Best @AIV-Bert,

ik heb de issue opnieuw bekeken met negatief resultaat. Beide files die hier werden meegegeven eindigen nog altijd in een 500 error, zonder enige indicatie wat er fout loopt. Het is helaas zelfs slechter geworden aangezien deze files niet eens meer getoond worden in de UI ("Er liep iets fout bij het verwerken van uw bestand."), wat voordien wel nog gebeurde.

Het bestand in bijlage ([test.wkt.txt](https://github.com/Informatievlaanderen/GIPOD/files/6382916/test.wkt.txt)) kan niet geüpload worden via de UI, maar werkt wel via de API endpoint /api/v1/organisations/{organisationId}/collaborationzone:

```
organisationId (antwerpen) = `a5666964-c552-0364-ad29-a109ae7bc9ff`
zone = contents van bijlage
```

Echter hoeven wij niet up te loaden via de UI, maar wel via de API. Het enige probleem is dat onze vorige bestanden in deze thread nog altijd resulteren in een 500 error waardoor wij onmogelijk kunnen weten wat er fout loopt langs jullie kant.

Graag een dringende hotfix aangezien wij hier reeds een maand op aan het wachten zijn.

**Comment by AIV-Bert** [comment]
Beste @jonas-db,

Je probeert op de UI een .txt file op te laden. Dit ondersteunen we niet. 

De zone hebben we kunnen opladen in de UI.

![image](https://user-images.githubusercontent.com/55388892/116213338-ffbb9e80-a745-11eb-825d-23574b83e5ee.png)

Met vriendelijke groeten,

Bert

**Comment by jonas-db** [comment]
De .txt is enkel voor hier op github te plaatsen. 
Het uploaden van test.wkt (zonder .txt) werkt niet op https://gipod.beta-vlaanderen.be/instellingen.

![Screenshot 2021-04-27 at 10 50 35](https://user-images.githubusercontent.com/2538260/116213865-6f318e00-a746-11eb-8213-9b034af56650.png)

**Comment by AIV-Bert** [comment]
Dag @jonas-db,

WIj kunnen dit niet reproduceren. Het importeren in de website op elke omgeving.

Het bewaren loopt idd fout op beta, maar lukt op productie. Onze beta omgevingen zijn lager geschaald, productie hebben we om dit op te lossen meer resources gegeven.

Met vriendelijk groeten,

Bert

**Comment by jonas-db** [comment]
Dag Bert,

dat verklaard mogelijks wel het probleem, alleen is een productie omgeving niet ideaal om tegen te testen.
We bekijken alvast of we het zo kunnen oplossen. Bedankt!

**Comment by AIV-Bert** [comment]
Dag @jonas-db,

Het is inderdaad niet de bedoeling om op productie te testen. Ik zal de zone manueel voor jou toevoegen op beta.
Aan welke organisatie wil je deze zone koppelen?

Met vriendelijke groeten,

Bert

**Comment by castersjef** [comment]
Dag @AIV-Bert ,

We hebben dit in PROD geprobeerd, ook hier zonder succes voor de drie files in deze thread.
We hebben geprobeerd voor de organisatiesEW Antwerpen en voor Agentschap Wegen en Verkeer.
![image](https://user-images.githubusercontent.com/37434828/116226601-7a3eeb00-a753-11eb-867c-2d98c5162ff8.png)

Het laten opladen in BETA is voor ons niet echt een optie. We proberen de end to end flow te testen waarbij de samenwerkingszones worden opgebouwd en opgeladen.

Kunnen we anders eens kort een meeting opzetten? 
jonas.debleser@mow.vlaanderen.be
jef.casters@mow.vlaanderen.be

Groeten,
Jef

**Comment by castersjef** [comment]
Godemorgen @AIV-Bert,

Is er iemand die ons hier mee kan verder helpen? Ik heb het vanmorgen nog eens geprobeerd en we kunnen nog steeds geen samenwerkingszones aanmaken.

Bedankt,
Jef

**Comment by AIV-Bert** [comment]
Dag @castersjef,

We gaan rechtstreeks contact met jullie opnemen aangezien we dit zelf niet kunnen reproduceren.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Dag @castersjef,

We hebben op beta al een kleine deel van de 1.3.0 wijzigingen in preview. De zone zou nu vlotter moeten werken.

Met vriendelijke groeten,

Bert

**Comment by castersjef** [comment]
Dag Bert,

Ik heb het zojuist nog eens geprobeerd op Beta en nu lukt het op de zone op te slaan via de ui!
Bedankt voor de update. Ik bekijk morgen met Jonas om het end to end proces langs onze kant te testen.

Met vriendelijke groeten,
Jef
