### ISSUE TITLE
GIPOD POLYGON error

### ISSUE THREAD

**Issue by abhisekpaul-dev** [Informatievlaanderen/GIPOD#278]
Dear,

We are sending polygon as a part of GIPOD(beta) groundwork create API request body. But getting error. Please let us know , if something is wrong in this request.

API: **https://api-gateway.beta.gipod.vlaanderen.be/api/v1/groundworks**
HTTP Verb: POST
request body JSON:
**{
    "ownerId": "53cf32f2-19d4-0d00-9b72-97625eac7309",
    "reference": "NPA18032890028994",
    "description": "+NPA+250321+tested remark 2+",
    "groundworkZone": "POLYGON((151391.09554733089 166627.81950216286 151390.07377779236 166630.11839216645 151390.11890399247 166630.13844905328 151391.52891925009 166629.57899215515 151392.83529001923 166634.88285747863 151390.58206744344 166634.70718528584 151390.56296828651 166634.75272510192 151392.18196828652 166635.4317251019 151392.92098070844 166635.66053810759 151393.69021783691 166635.74281198854 151394.46090564795 166635.67546921442 151395.20421585345 166635.46102880375 151395.89234424988 166635.10751209784 151396.49955076011 166634.62814271494 151397.00312226481 166634.04085190882 151397.38422220762 166633.36760783353 151400.15193820468 166627.140494577 151400.5541089708 166626.30658166492 151400.92224272952 166625.63781841879 151401.25143051922 166625.10559416923 151401.54646043366 166624.68298375126 151402.33964097328 166623.8288995568 151403.04215941188 166623.19888044111 151404.07117630163 166622.4271177738 151404.62082717154 166622.127209065 151405.42591769557 166621.80301636292 151406.12510576937 166621.563613317 151406.63094222755 166621.4667510165 151407.42611289592 166621.39878771151 151408.44807023156 166621.45738618259 151409.15211433862 166621.49809108814 151409.7986995253 166621.61062754184 151410.4957315404 166621.76815351247 151412.05727917413 166622.17149573867 151414.27437579754 166622.97942839554 151420.49023548717 166625.50316833952 151420.74506473873 166625.59669233527 151422.10857195433 166626.04522753164 151424.39568197043 166626.807597537 151425.53034150539 166627.194079466 151425.93608427772 166627.35391752783 151429.14652934237 166628.68855247149 151429.23387502087 166628.72366384175 151431.40187502088 166629.56566384176 151431.44058301722 166629.58046681146 151433.93675982492 166630.520278532 151435.56426521807 166635.80358175383 151435.57184986252 166635.82792738071 151437.27684986254 166641.23992738072 151437.56046177924 166641.91636040082 151437.96282108373 166642.52963386351 151438.47039851095 166643.05912655024 151439.06612685407 166643.48703435712 151439.72997484618 166643.79896895497 151440.82897484617 166644.19696895496 151448.39497804511 166646.93697011346 151449.19047731606 166647.22451282272 151449.8613313511 166647.46731522147 151454.48708791556 166649.35148165355 151454.54895793326 166649.37608423838 151456.25495793324 166650.03808423839 151457.0616575584 166650.25741253639 151457.8963269087 166650.30427684306 151458.72250819093 166650.17663015713 151459.33954580242 166649.94249389751 151460.21266262754 166650.2588006242 151460.50157912576 166650.78378564058 151461.03742091759 166651.40824173181 151461.68970125323 166651.90984137249 151462.43081759237 166652.26735837577 151464.76881759238 166653.11135837575 151464.77607465076 166653.11397021246 151475.02614711269 166656.79184332676 151476.09922628992 166657.180697783 151478.82477371008 166649.659302217 151477.74577371008 166649.268302217 151477.73392534925 166649.26402978753 151467.48155513732 166645.58533220756 151467.10903642868 166645.45085582172 151466.82204722767 166644.9291182145 151466.28677607561 166644.30489320017 151465.63517052916 166643.80331340933 151464.89476793047 166643.44557598248 151463.62960547904 166642.98787898189 151459.82944300037 166641.61118239333 151459.03290712557 166641.41223370322 151458.21253064528 166641.38010253795 151457.40287448152 166641.51614252327 151456.92039723723 166641.70443334588 151452.80591208444 166640.02851834646 151452.65830320245 166639.97176967058 151451.91230320247 166639.70176967056 151451.11788209464 166639.41461709022 151444.31304557086 166636.95026973687 151443.20598125993 166633.43623334353 151441.00473478192 166626.29041824615 151440.72775975388 166625.6166254383 151440.33317366673 166625.00424178902 151439.83406474153 166624.4735797545 151439.24698816915 166624.04224112621 151438.59141698279 166623.72453318854 151434.27880932461 166622.10083441419 151432.17400441677 166621.28337789554 151428.97247065764 166619.95244752851 151428.90309807364 166619.92436642878 151428.37509807365 166619.71636642877 151428.198697682 166619.65161915688 151426.962697682 166619.23061915688 151426.93791106407 166619.2222668078 151424.63091106407 166618.4532668078 151424.61593526127 166618.44830766472 151423.37393748955 166618.03974384631 151417.21676451282 166615.53983166048 151417.08154059327 166615.48776124185 151414.61454059326 166614.58876124185 151414.24535425808 166614.47410814013 151412.43735425809 166614.00710814013 151412.31874459711 166613.97839437341 151411.46474459712 166613.78539437341 151411.26887851561 166613.74624237465 151410.29787851559 166613.57724237465 151409.84287783082 166613.52466863045 151408.90887783084 166613.47066863044 151407.59898168268 166613.39555945469 151407.02936159889 166613.40353070773 151405.74236159891 166613.51353070774 151405.33071091696 166613.57037923244 151404.34371091693 166613.75937923242 151403.80024573009 166613.90368752979 151402.7342457301 166614.26868752981 151402.53587335287 166614.34253027741 151401.41587335288 166614.79353027738 151400.99410336922 166614.9926839931 151399.98610336921 166615.54268399312 151399.502 166615.854 151398.102 166616.90399999998 151397.83140871985 166617.12609096605 151396.86240871984 166617.99509096606 151396.60200119345 166618.25100698089 151395.49500119346 166619.4430069809 151395.14616766534 166619.87530572858 151394.62816766533 166620.61730572858 151394.50612621463 166620.80289573726 151394.06512621464 166621.51589573725 151393.9628312818 166621.69106205532 151393.49383128178 166622.54306205534 151393.39510379711 166622.73443303691 151392.91910379712 166623.7214330369 151392.86677779237 166623.83439216646 151391.39429928665 166627.14733700352 151391.15336875751 166627.180077155 151390.95036875753 166627.230077155 151391.09554733089 166627.81950216286))",
    "statusId": "244dd11c-e9e8-4bed-9655-0865d123c36a",
    "contactOrganisation": [
        {
            "organisationId": "53cf32f2-19d4-0d00-9b72-97625eac7309",
            "roleId": "aad5e947-f7bf-4592-a84a-f591555b0b8b",
            "contactName": "Nijenhuis  Ellen",
            "telephone": "32474961514",
            "email": "ellen.nijenhuis.ext@proximus.com",
            "address": {
                "countryCode": "BE"
            },
            "isPublic": false
        }
    ],
    "categoryId": "1cf4ebfb-8702-4fc3-a1b1-9b22c3b909f9",
    "publicDomainOccupancyTypeId": [
        "9ca97530-c1cf-45ed-8d80-e34563694d24"
    ],
    "period": {
        "start": "2021-04-28T10:00Z",
        "end": "2021-05-30T10:00Z"
    },
    "isRelocationGroundwork": false,
    "causingGroundwork": [],
    "specificationId": [],
    "estimatedDurationDays": "14",
    "grbImpactId": "25750cda-438f-40b5-bf43-10668bd9b40b"
}**

response error:  **_The specified condition was not met for 'Groundwork Zone'._**

**Comment by AIV-Bert** [comment]
Hi @abhisekpaul-dev 

Your groundworkzone is not in a valid wkt format. The coordinates are not comma seperated.
You can find more info on the wkt representation of a geometry here: https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

Please use this format:
`POLYGON ((30.5 10.4, 40.0 40.0, 20.2 40.1, 10.0 20.1, 30.5 10.4))`

Kind regards,

Bert
