### ISSUE TITLE
POST, GET issue

### ISSUE THREAD

**Issue by SoroTrestal** [Informatievlaanderen/GIPOD#279]
Beste, we merken op dat wanneer wij direct na ne een succesvolle POST via de verkregen gipod id een GET proberen te doen met diezelfde gipod id dat wij soms de melding krijgen dat de inname niet wordt teruggevonden (terwijl het duidelijk over dezelfde id gaat).

```
Status: 404
Response:
, No event found for GipodId: 11316317.
```

We krijgen wel degelijk het correcte gipod id terug na de eerste POST.

**Comment by AIV-Bert** [comment]
Hi  @SoroTrestal,

The read side of our API is "eventually consistent". This means that after a creation or update there can be some delay on the currrent state of the resource.

We have a mechanism you can use to check if you get the latest state of a resource.
In the response of a POST/PUT/PATCH method a response header "ETAG" is available. The value of the ETAG is an indication of the latest version of the resource. If you do a get method on a resource you can add the value of the ETAG response header in the Request Header "If-Match". If the server cannot response with the expected (latest) version a HttpStatus Code 412 (Precondition Failed) will be returned. In this case you can retry until you get a HttpStatus 200 OK.

So you have to possibilities:

1. increase the time before you get the details
2. use the mechanism described with headers ETAG, If-match

More information in the technical documentation:
https://vlaamseoverheid.atlassian.net/wiki/spaces/GIP/pages/1590494048/Eventually+Consistency

Kind regards,

Bert
