### ISSUE TITLE
Confluence page Mapping for hindrance not accessible

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#28]
The confluence page https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1243022158/Mapping+van+Hinder+in+het+GIPOD reference on https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1242989032/Mapping+data+GIPOD+naar+GIPOD is not accessible

**Comment by olivermay** [comment]
Hi Berdien, 

we are working on a new version of the page. As soon as it is done we'll let you know.

kind regards, 

Oliver

**Comment by berdienderoo** [comment]
Any news on this?

**Comment by olivermay** [comment]
Hi Berdien, 

this page was outdated and archived. I changed the link to this page: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1637090283/Mapping+van+Hinder

Please let me know if the information on this page is not sufficient.
