### ISSUE TITLE
urn:be.vlaanderen.gipod.errors:InvalidWorkScheduleForStatusException bij zetten van Work in status 'In Uitvoering' kort na middernacht

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#280]
Beste,

we krijgen deze fout wanneer we kort na middernacht (Brussels Time) de status van een Werk veranderen naar 'In Uitvoering'

PATCH /api/v1/works/11274334 req = {"items":[{"key":"OwnerId","value":"53fece95-7f78-0bde-af23-b7acdcc5b549"},{"key":"StatusId","value":"14eb1a99-fa22-43e9-b1fb-b3bc7a9fdfce"},{"key":"PublicDomainOccupancyTypeIds","value":["21fefaa4-4d71-4dd7-b104-f0b16d032acb"]},{"key":"Reference","value":"AWV:Werf=WerfId(36532):Inname=5fc64789-c8d3-4f5f-b3f7-019955a0c906"},{"key":"Description","value":"N50, N368 - Gietasfalt op de N050 en de N368 - Beernem+Oostkamp+Zedelgem"},{"key":"Urls","value":["https://wegenenverkeer.be/beernem","https://wegenenverkeer.be/oostkamp","https://wegenenverkeer.be/zedelgem"]},{"key":"Period","value":[{"end":"2021-04-01T15:00:00Z","start":"2021-04-01T06:00:00Z"},{"end":"2021-04-02T15:00:00Z","start":"2021-04-02T06:00:00Z"},{"end":"2021-04-05T15:00:00Z","start":"2021-04-05T06:00:00Z"},{"end":"2021-04-06T15:00:00Z","start":"2021-04-06T06:00:00Z"},{"end":"2021-04-07T15:00:00Z","start":"2021-04-07T06:00:00Z"},{"end":"2021-04-08T15:00:00Z","start":"2021-04-08T06:00:00Z"},{"end":"2021-04-09T15:00:00Z","start":"2021-04-09T06:00:00Z"},{"end":"2021-04-12T15:00:00Z","start":"2021-04-12T06:00:00Z"},{"end":"2021-04-13T15:00:00Z","start":"2021-04-13T06:00:00Z"},{"end":"2021-04-14T15:00:00Z","start":"2021-04-14T06:00:00Z"},{"end":"2021-04-15T15:00:00Z","start":"2021-04-15T06:00:00Z"},{"end":"2021-04-16T15:00:00Z","start":"2021-04-16T06:00:00Z"}]},{"key":"EstimatedDurationDays","value":null},{"key":"SpecificationIds","value":["7b0bc493-0c4c-4f33-8bf0-5f3296931a9e","b2652ecd-af70-4be2-a73c-0c8910f5fd70"]}]}

Dit op Apr 1, 2021 @ 00:01:10.604 (Brussels Time, dus op 31/3 om 22:01:10.604Z) geeft een 400:

400 Bad Request - {"type":"https://httpstatuses.com/400","title":"One or more validation errors occurred.","status":400,"detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:InvalidWorkScheduleForStatusException","title":"Work schedule is invalid for WorkStatus: In uitvoering.\n Combinatie periode en tijdschema is niet in uitvoering.","detail":"Work schedule is invalid for WorkStatus: In uitvoering.\n Combinatie periode en tijdschema is niet in uitvoering."}]} - x-correlation-id: e98f7ed0-9e97-4b48-82be-54c7e3ee3281}

Waarschijnlijk door combinatie:
{"key":"Period","value":[{"end":"2021-04-01T15:00:00Z","start":"2021-04-01T06:00:00Z"},...]
en 
{"key":"StatusId","value":"14eb1a99-fa22-43e9-b1fb-b3bc7a9fdfce"}

Bij een retry van deze operatie >2u later lukt de status aanpassing wel...

Of mogen wij deze status wijziging pas doen om 2021-04-01T06:00:00Z ?

**Comment by AIV-Bert** [comment]
Dag @ireactsam,

Jullie request is valid vanaf 2021/03/31 22:00 (UTC). De request komt op onze server binnen om 2021/03/31 22:01 (UTC), maar toch krijg je onterecht een foutboodschap.  Jullie hoeven dus zeker geen 2 uur te wachten. Kort na middernacht zou dit moeten werken.

We vermoeden dat er een issue is met de tijdsynchronisatie tussen de componenten van de applicatie. We gaan onze logging  uitbreiden en dit verder evalueren.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Dag @ireactsam,

Vanaf release 1.3.0 (16/06/2021) krijg je een duidelijkere foutmelding. Kan je dit verder opvolgen en ons op de hoogte brengen als dit terug voorvalt?

Met vriendelijke groeten,

Bert

**Comment by ireactsam** [comment]
Hallo @AIV-Bert,
sinds 11/6 hebben we dergelijke fouten niet meer gezien, we kunnen dit ticket afsluiten, dank.
mvg
Sam

**Comment by AIV-Bert** [comment]
Dag @ireactsam,

Bedankt voor je opvolging.

Met vriendelijke groeten,

Bert
