### ISSUE TITLE
Grondwerk aanmaken op BETA lukt niet meer

### ISSUE THREAD

**Issue by roelalgoet** [Informatievlaanderen/GIPOD#281]
Bij het aanmaken van een grondwerk op beta (via UI) krijgen we volgende melding

![foutmelding GIPOD](https://user-images.githubusercontent.com/84007891/117779882-6315f800-b23f-11eb-9986-f8f36990f46b.PNG)

**Comment by AIV-Bert** [comment]
Beste,

Het aanmaken lukte, maar je kon dit niet opvragen. We hebben dit verholpen.

Met vriendelijke groeten,

Bert
