### ISSUE TITLE
Lijst van synergieaanvragen wordt niet vernieuwd op Beta

### ISSUE THREAD

**Issue by roelalgoet** [Informatievlaanderen/GIPOD#282]
**Describe the bug**
Nieuwe synergieaanvragen zijn niet zichtbaar in de lijst met te beantwoorden synergieaanvragen en alle synergieaanvragen.

Nieuwe SSA aangemaakt.
![SSA-10421323](https://user-images.githubusercontent.com/84007891/118451717-d44d2380-b6f5-11eb-90ac-fbe6ac811541.PNG)

Niet zichtbaar in te beantoorden SSA
![Te beantwoorden SSA](https://user-images.githubusercontent.com/84007891/118451774-e16a1280-b6f5-11eb-8679-63ec5fbbdb7b.PNG)

Ook niet zichtbaar in alle aanvragen (enkel gegevens tem 15/5 en kan ook niet want SSA's van 15/5 moeten afgesloten zijn).
 
![alle aanvragen](https://user-images.githubusercontent.com/84007891/118451931-0494c200-b6f6-11eb-98e3-3d6d0d63faed.PNG)

**Comment by roelalgoet** [comment]
De nieuwe synergieaanvragen komen ook niet door via Swagger. Ook enkel reeds verlopen synergieaanvragen (van 15/5){
  "@context": [
    "http://www.w3.org/ns/hydra/context.jsonld",
    "https://api-gateway.beta.gipod.vlaanderen.be/api/v1/context/enriched/public-domain-occupancy.jsonld"
  ],
  "@id": "/api/v1/trench-synergy-requests-to-be-answered",
  "@type": "Collection",
  "totalItems": 2,
  "member": [
    {
      "@id": "/api/v1/groundworks/10417020/trench-synergy-requests/10417021",
      "trenchSynergyRequestId": 10417021,
      "additionalInfo": "Test extra info",
      "gipodId": 10417020,
      "organisationId": "a7b69948-6364-0b17-9902-3be0322407df",
      "organisation": "Fluvius Site Schelde-Waas",
      "pilotId": "7a989d85-ce5e-076c-9e77-a3cbf4e7078d",
      "pilot": "Oranje",
      "launchDate": "2021-05-15T15:56:12.4532301Z",
      **"deadline1": "2021-05-15T19:56:12.4532301Z"**
    },
    {
      "@id": "/api/v1/groundworks/10417022/trench-synergy-requests/10417032",
      "trenchSynergyRequestId": 10417032,
      "additionalInfo": null,
      "gipodId": 10417022,
      "organisationId": "a7b69948-6364-0b17-9902-3be0322407df",
      "organisation": "Fluvius Site Schelde-Waas",
      "pilotId": "7a989d85-ce5e-076c-9e77-a3cbf4e7078d",
      "pilot": "Oranje",
      "launchDate": "2021-05-15T16:00:23.3976011Z",
      "deadline1": "**2021-05-15T20:00:23.3976011Z**"
    }
  ],
  "view": {
    "@id": "/api/v1/trench-synergy-requests-to-be-answered?organisationid=a7b69948-6364-0b17-9902-3be0322407df",
    "@type": "PartialCollectionView",
    "first": null,
    "previous": null,
    "next": null,
    "last": null
  }
}

**Comment by AIV-Bert** [comment]
Beste @roelalgoet,

De issues zijn opgelost. Er ging geen data verloren.
Kan je nog even bevestigen of dit voor jou kan afgesloten worden?

Met vriendelijke groeten,
Bert

**Comment by roelalgoet** [comment]
Ik heb het uitgetest en ik heb de synergieaanvragen kunnen inlezen.
Voor mij is het dus ok.
Ticket mag worden afgesloten.

Bedankt,

Roel
