### ISSUE TITLE
Beta GUI and API geven fout

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#285]
**Describe the bug**
Wanneer we inloggen op de beta omgeving (https://gipod.beta-vlaanderen.be/) wordt na aanmelden elke +/-2 seconden de pagina vernieuwd. 
Bij het aanmaken van een nieuw werk of evenement via de API krijgen we eveneens een fout.

**Comment by AIV-Bert** [comment]
Dag @berdienderoo,

Er was een issue met organisaties die een niscode hebben. Dit is verholpen en werkt terug op beta.

Met vriendelijke groeten,

Bert
