### ISSUE TITLE
Syntax multipolygoon

### ISSUE THREAD

**Issue by user1862** [Informatievlaanderen/GIPOD#287]
Beste, ik slaag er niet in via de daartoe voorzien een multipolygoon te registreren bij een inname. Wat is de exacte syntax ?
Wij krijgen altijd de volgende melding : GroundworkZone:  Groundwork Zone could not be processed: wkt is not valid.

Hierbij een voorbeeld van een syntax die problemen geeft : 
MULTIPOLYGON(((177630.56 175183.67,177620.56 175183.67,177620.56 175173.67,177630.56 175183.67)),((177630.56 175173.67,177620.56 175173.67, 177620.56 175163.67,177630.56 175163.67)))
Bedankt alvast.
Mvg,
Luc.

**Comment by AIV-Bert** [comment]
Beste @user1862,

De 2 polygonen in deze multipolygoon overlappen. Ze hebben beiden hetzelfde startpunt en overlappen dus elkaar op dat ene punt.

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Beste @user1862,

De 2 polygonen in deze multipolygoon overlappen. Ze hebben beiden hetzelfde startpunt en overlappen dus elkaar op dat ene punt. Polygonen moeten ook hetzelfde begin- en eindpunt hebben, anders is de polygoon niet gesloten en dus ongeldig.

Met vriendelijke groeten,

Bert
