### ISSUE TITLE
Deadlines SSA op Beta zijn op 0 gezet

### ISSUE THREAD

**Issue by roelalgoet** [Informatievlaanderen/GIPOD#288]
**Describe the bug**
Bij het lanceren van een synergieaanvraag krijg ik voor deadline 1 en deadline 2 dezelfde datum als de aanmaakdatum.  Hierdoor kunnen we geen te beantwoorden synergieaanvragen meer inlezen want de SSA komt direct op afgesloten zonder gevolg.

![image](https://user-images.githubusercontent.com/84007891/120307609-79a9ef00-c2d3-11eb-9ee6-8efb52d67da2.png)

**Expected behavior**

**Additional context**

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by AIV-Bert** [comment]
We resolved your issue.

Kind regards,

Bert
