### ISSUE TITLE
Datums bij het aanmaken van een nieuw grondwerk

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#29]
Hey,

Ik heb de documentatie (url) gevolgd om een nieuw grond werk te maken. Ik krijg een error op de formatting van de datums.

Van daar mijn vraag; hoe moeten de datums geformateerd worden?

Ter info hieronder het request/resposne paar.
request:
{
    "ownerId": "760bb1a4-bc1c-0bb8-868d-c0b6fd937233",
    "reference": "5c542bf4-52fc-4639-8c1b-818d54342ff2",
    "description": "Dit is een test grondwerk.",
    "url": [
        "https://vlaanderen.be/"
    ],
    "publicDomainOccupancyStatusId": "3232baa5-a157-4126-a2be-354ad1e480f7",
    "categoryId": "bb0b471a-7f4d-4eaa-b788-adae1aaf30f8",
    "publicDomainOccupancyTypeId": [
        "a486a968-e498-4708-8820-901686f0712f"
    ],
    "period": {
        "start": "2020-09-30T22:00:00Z",
        "end": "2020-10-31T22:00:00Z",
        "duration": null
    },
    "isRelocationGroundwork": false,
    "causingGroundwork": [ ],
    "specificationTypeId": [
        "57438692-f1e3-4010-a1c8-725f42b85f56"
    ],
    "estimatedDurationDays": 5
}

response:
{
    "type": "https://httpstatuses.com/400",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "detail": "Please refer to the errors property for additional details.",
    "errors": [
        {
            "type": "urn:be.vlaanderen.gipod.errors:ModelState",
            "title": "period.end",
            "detail": "The supplied value is invalid."
        },
        {
            "type": "urn:be.vlaanderen.gipod.errors:ModelState",
            "title": "period.start",
            "detail": "The supplied value is invalid."
        }
    ]
}

**Comment by doomsju** [comment]
Voor het registreren van innames accepteren we tijdstippen tot op de minuut. Formaat "YYYY-MM-DDTHH:MMZ".

mvg,
Jürgen.
