### ISSUE TITLE
Question: Changing Payload (maybe a caching issue?)

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#291]
Hey

We had an issue with a payload for a site that was different a week after the last change in GIPOD has been recorded.
The original payload (which was received some time ago) is pasted in first, and then the payload we retrieved today. The 2 differences are that the contactOrganisation isn't present in the orignal payload and the last modified information is neither. But a week later both fields are present, even though no change to the item has been made. Is there a reason for this and a way to avoid this?

Original payload:
{
  "@context": "https://private-api.gipod.vlaanderen.be/api/v1/context/enriched/public-domain-occupancy.jsonld",
  "@id": "/api/v1/groundworks/11534677",
  "@type": "Groundwork",
  "gipodId": 11534677,
  "identifier": [
    {
      "@type": "Identifier",
      "identifier": {
        "value": "11534677",
        "type": "gipodId"
      },
      "assignedByName": "https://gipod.vlaanderen.be"
    },
    {
      "@type": "Identifier",
      "identifier": {
        "value": "54513353",
        "type": "reference"
      },
      "assignedByName": "Fluvius Site Ijzer-Mandel"
    }
  ],
  "description": "8670 KOKSIJDE, JULIEN DILLENSLAAN",
  "remark": null,
  "url": [],
  "attachment": [],
  "publicDomainOccupancyType": [
    {
      "@id": "/api/v1/taxonomies/public-domain-occupancy/types/7ab7ce8f-e648-4765-9d47-1983adcc461c",
      "prefLabel": "Olie, gas, chemicaliën"
    }
  ],
  "specification": [
    {
      "@id": "/api/v1/taxonomies/public-domain-occupancy/specifications/95fcfa60-51fe-4528-a8cc-8b5d37a51e47",
      "prefLabel": "klantaansluiting"
    }
  ],
  "category": {
    "@id": "/api/v1/taxonomies/public-domain-occupancy/groundworkcategories/1cf4ebfb-8702-4fc3-a1b1-9b22c3b909f9",
    "prefLabel": "Categorie 2"
  },
  "owner": {
    "@id": "/api/v1/organisations/031c4cfd-32b8-09be-83d9-f578b6b0615e",
    "@type": "Organisation",
    "preferredName": "Fluvius Site Ijzer-Mandel"
  },
  "contactOrganisation": [],
  "period": {
    "@type": "PeriodWithDuration",
    "start": "2021-07-02T00:00:00Z",
    "end": "2021-07-09T20:00:00Z",
    "duration": null
  },
  "estimatedDuration": null,
  "occurrence": "/api/v1/groundworks/11534677/occurrences",
  "status": {
    "@id": "/api/v1/taxonomies/statuses/244dd11c-e9e8-4bed-9655-0865d123c36a",
    "prefLabel": "Concreet gepland"
  },
  "zone": [
    {
      "@id": "/api/v1/groundworks/11534677/zones/d801a970-02bb-41f4-ac8e-dffe3a84347b",
      "@type": "Zone",
      "geometry": {
        "@type": "Geometry",
        "wkt": "POLYGON ((26869.7265183 201162.6256297, 26871.7265183 201162.6256297, 26871.7265183 201164.6256297, 26869.7265183 201164.6256297, 26869.7265183 201162.6256297))"
      },
      "zoneType": {
        "@id": "/api/v1/taxonomies/zonetypes/6ee12839-8002-4f51-b509-4000b4a29b44",
        "prefLabel": "GrondwerkZone"
      },
      "pointOnSurface": {
        "@type": "Geometry",
        "wkt": "POINT (26870.7265183 201163.6256297)"
      }
    }
  ],
  "addressRepresentation": null,
  "grbImpact": {
    "@id": "/api/v1/taxonomies/public-domain-occupancy/grbimpact/25750cda-438f-40b5-bf43-10668bd9b40b",
    "prefLabel": "Geen GRB afwijking"
  },
  "isRelocationGroundwork": false,
  "causingGroundwork": [],
  "isPartOfTrenchSynergy": [],
  "hasConsequence": [],
  "publicDomain": true,
  "requestForGroundworks": [],
  "lastModifiedOn": null,
  "lastModifiedBy": null,
  "createdOn": "2021-06-22T08:07:05.3870174Z",
  "createdBy": {
    "@id": "/api/v1/organisations/f16e5d31-5645-01cb-93fa-bcf421779ecc",
    "@type": "Organisation",
    "preferredName": "Fluvius"
  }
}

new payload:
{
  "@context": "https://private-api.gipod.vlaanderen.be/api/v1/context/enriched/public-domain-occupancy.jsonld",
  "@id": "/api/v1/groundworks/11534677",
  "@type": "Groundwork",
  "gipodId": 11534677,
  "identifier": [
    {
      "@type": "Identifier",
      "identifier": {
        "value": "11534677",
        "type": "gipodId"
      },
      "assignedByName": "https://gipod.vlaanderen.be"
    },
    {
      "@type": "Identifier",
      "identifier": {
        "value": "54513353",
        "type": "reference"
      },
      "assignedByName": "Fluvius Site Ijzer-Mandel"
    }
  ],
  "description": "8670 KOKSIJDE, JULIEN DILLENSLAAN",
  "remark": null,
  "url": [],
  "attachment": [],
  "publicDomainOccupancyType": [
    {
      "@id": "/api/v1/taxonomies/public-domain-occupancy/types/7ab7ce8f-e648-4765-9d47-1983adcc461c",
      "prefLabel": "Olie, gas, chemicaliën"
    }
  ],
  "specification": [
    {
      "@id": "/api/v1/taxonomies/public-domain-occupancy/specifications/95fcfa60-51fe-4528-a8cc-8b5d37a51e47",
      "prefLabel": "klantaansluiting"
    }
  ],
  "category": {
    "@id": "/api/v1/taxonomies/public-domain-occupancy/groundworkcategories/1cf4ebfb-8702-4fc3-a1b1-9b22c3b909f9",
    "prefLabel": "Categorie 2"
  },
  "owner": {
    "@id": "/api/v1/organisations/031c4cfd-32b8-09be-83d9-f578b6b0615e",
    "@type": "Organisation",
    "preferredName": "Fluvius Site Ijzer-Mandel"
  },
  "contactOrganisation": [
    {
      "@id": "/api/v1/groundworks/11534677/contactorganisations/91717024-7877-43bb-8385-a2a3cf628157",
      "@type": "ContactOrganisationInRole",
      "role": {
        "@id": "/api/v1/taxonomies/contactroles/aad5e947-f7bf-4592-a84a-f591555b0b8b",
        "prefLabel": "Dossierbeheerder"
      }
    }
  ],
  "period": {
    "@type": "PeriodWithDuration",
    "start": "2021-07-02T00:00:00Z",
    "end": "2021-07-09T20:00:00Z",
    "duration": null
  },
  "estimatedDuration": null,
  "occurrence": "/api/v1/groundworks/11534677/occurrences",
  "status": {
    "@id": "/api/v1/taxonomies/statuses/244dd11c-e9e8-4bed-9655-0865d123c36a",
    "prefLabel": "Concreet gepland"
  },
  "zone": [
    {
      "@id": "/api/v1/groundworks/11534677/zones/d801a970-02bb-41f4-ac8e-dffe3a84347b",
      "@type": "Zone",
      "geometry": {
        "@type": "Geometry",
        "wkt": "POLYGON ((26869.7265183 201162.6256297, 26871.7265183 201162.6256297, 26871.7265183 201164.6256297, 26869.7265183 201164.6256297, 26869.7265183 201162.6256297))"
      },
      "zoneType": {
        "@id": "/api/v1/taxonomies/zonetypes/6ee12839-8002-4f51-b509-4000b4a29b44",
        "prefLabel": "GrondwerkZone"
      },
      "pointOnSurface": {
        "@type": "Geometry",
        "wkt": "POINT (26870.7265183 201163.6256297)"
      }
    }
  ],
  "addressRepresentation": null,
  "grbImpact": {
    "@id": "/api/v1/taxonomies/public-domain-occupancy/grbimpact/25750cda-438f-40b5-bf43-10668bd9b40b",
    "prefLabel": "Geen GRB afwijking"
  },
  "isRelocationGroundwork": false,
  "causingGroundwork": [],
  "isPartOfTrenchSynergy": [],
  "hasConsequence": [],
  "publicDomain": true,
  "requestForGroundworks": [],
  "lastModifiedOn": "2021-06-22T08:07:05.3903005Z",
  "lastModifiedBy": {
    "@id": "/api/v1/organisations/f16e5d31-5645-01cb-93fa-bcf421779ecc",
    "@type": "Organisation",
    "preferredName": "Fluvius"
  },
  "createdOn": "2021-06-22T08:07:05.3870174Z",
  "createdBy": {
    "@id": "/api/v1/organisations/f16e5d31-5645-01cb-93fa-bcf421779ecc",
    "@type": "Organisation",
    "preferredName": "Fluvius"
  }
}

**Comment by AIV-Bert** [comment]
Beste @langens-jonathan,

Na het aanmaken kan er een korte periode zitten tussen de registratie van de inname en het volledig opbouwen van het detail.

Zonder het exacte tijdstip  waarop jullie de originele payload opvragen of de correlationid kan ik niet exact nagaan of dit een fout zou zijn aan onze kant. 

Met vriendelijke groeten,

Bert
