### ISSUE TITLE
BETA: Innames openbaar domein blijven 'in verwerking'

### ISSUE THREAD

**Issue by Foodbait** [Informatievlaanderen/GIPOD#292]
**Describe the bug**
Na het posten van een event/work/groundwork blijft de API http 412's returnen als je de resource opnieuw opvraagt sinds 13/07.

Vermoed dat het probleem niet aan mijn kant zit, aangezien deze innames wel terugkomen op https://gipod.beta-vlaanderen.be, maar deze geven allen onderstaande melding wanneer je ze selecteert in het overzicht. (ook bij innames die niet uit ons systeem komen):

Inname niet gevonden
De inname met id X bestaat niet.

Een voorbeeld hiervan is id: 10492433, 10492365 , 

Alvast bedankt

**Comment by AIV-Bert** [comment]
Beste @Foodbait,

Bedankt voor de melding. Dit is ondertussen verholpen.

Met vriendelijke groeten,

Bert
