### ISSUE TITLE
Creation groundwork, can not be fetch after 201-response

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#293]
**Describe the bug**
When we create a groundwork in the bèta-environment, we receive a 201 response.
When we want to open it in GIPOD itself or fetch it with a get-call afterwards, we get a not-found.

**Expected behavior**
We expect when we receive a successful response, that we can fetch the groundwork and that we can open it on the GIPOD-platform.

**Correlation id and request**
Groundwork creation (15/07/2021 - 9u22):
![image](https://user-images.githubusercontent.com/47892553/125758190-373342be-6e50-4001-907f-fdbd4d0b7a96.png)

Fetch afterwards: (15/07/2021 - 10u47):
![image](https://user-images.githubusercontent.com/47892553/125758696-fb369dc3-2975-46e6-a8af-c42047e909c2.png)

**Comment by AIV-Bert** [comment]
Beste @TomCap1432,

Bedankt voor de melding. Deze issue is inmiddels verholpen.

Met vriendelijke groeten,

Bert
