### ISSUE TITLE
deprecation van /api/v1/localgovernments

### ISSUE THREAD

**Issue by jonas-db** [Informatievlaanderen/GIPOD#295]
Wij zouden de endpoint /api/v1/localgovernments gebruiken voor te bepalen of een gemeente een externe tool voor vergunningen gebruikt of niet. Gaat deze endpoint weg of is hier een andere manier voor?

https://api-gateway.beta.gipod.vlaanderen.be/swagger/index.html

**Comment by AIV-Bert** [comment]
Dag @jonas-db,

Tijdens de 1.4.0 release hebben we gezien dat dit endpoint onterecht mee gereleased werd . We hebben ervoor gekozen de release niet tegen te houden, maar het endpoint (tijdelijk) obsolete te zetten. Dit is een vroeger versie van het endpoint en er zullen met zekerheid nog enkele aanpassingen gebeuren.

Met vriendelijke groeten,

Bert
