### ISSUE TITLE
Ik kan momenteel geen Grondwerk aanmaken in de staging omgeving (ook probleem met SSA)

### ISSUE THREAD

**Issue by roelalgoet** [Informatievlaanderen/GIPOD#296]
In de staging omgeving heb ik een probleem waarbij grondwerken en SSA's een ID krijgen maar er geen gegevens worden weggeschreven : 
- Wanneer ik een grondwerk in het GIPOD heb aangemaakt krijg ik deze niet te zien. Na het aanmaken van de inname krijg ik de melding er ging iets mis bij het laden
![image](https://user-images.githubusercontent.com/84007891/129542221-669f2d6f-8748-47ee-af2d-d73b94575f43.png)
wanneer ik nadien het grondwerk vanuit de lijst wil openen krijg ik de melding: De inname met ID xxxxxxx bestaat niet
![image](https://user-images.githubusercontent.com/84007891/129542570-3bda009e-6776-4a49-8d1a-2235cc117383.png)

Voor een SSA die ik heb aangemaakt voor een bestaand grondwerk krijg ik ook de melding: We kunnen de synergiegegevens niet terugvinden
![image](https://user-images.githubusercontent.com/84007891/129542912-1dffd72e-4b24-447f-beb7-becc6c4db10d.png)

**Comment by AIV-Bert** [comment]
Beste @roelalgoet,

Tijdens de voorbereiding van de API release 1.4.0 waren er enkele problemen met het opvragen van de data. Alle request zijn echter wel verwerkt. Staging is nu terug stabiel.

Met vriendelijke groeten,

Bert
