### ISSUE TITLE
statusFollowsTiming vs. StatusFollowsTiming

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#297]
In the openapi.json (https://api-gateway.beta.gipod.vlaanderen.be/swagger/v1/swagger.json?culture=):
For RegisterEventRequest / RegisterWorkRequest:
```
          "statusFollowsTiming": {
            "type": "boolean",
            "description": "Indicates if the status should follow the specified timing.\r\nWhen not provided it will be handled by the system default.",
            "nullable": true
          }
```
while in EventLd/WorkLd:
```
          "StatusFollowsTiming": {
            "type": "boolean"
          },
```
is it possible to adapt the openapi.json for `EventLd` and `WorkLd` to  also use a lowercase s: `statusFollowsTiming` ?

**Comment by AIV-Bert** [comment]
Hi @ireactsam,

The properties in EventLd/WorkLd should not start with a capital letter. We will update the OpenApi specification in release 1.4.1

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
Released on production
