### ISSUE TITLE
Geometry issue in Workorder API

### ISSUE THREAD

**Issue by srjtkrmkr** [Informatievlaanderen/GIPOD#299]
**Groundwork polygon geometry is neither  3D nor 2D**
Received a Geometry from groundwork API that is throwing error while inserting postgres db. 
Groundwork ID: 670186
**geom:**  POLYGON ((245502.783 192896.553, 245472.489 192832.012, 245441.535 192843.208, 245446.804 193034.197, 245473.147 193220.576, 245517.272 193363.488, 245581.155 193561.062, 245688.232 193828.844, 245859.389 194224.892, 245946.288 194415.957, 245963.553 194414.918, 245976.896 194413.041, 245983.178 194411.699, 245979.783 194405.311, 245965.418 194369.245, 245930.001 194282.12, 245871.481 194144.308, 245834.13 194053.304, 245774.18 193911.577, **245728.851 193799.97 80**, 245712.426 193752.933, 245687.547 193684.035, 245834.05 193674.997, 245913.08 193659.191, 245900.567 193620.993, 245816.268 193624.945, 245685.211 193456.348, 245652.94 193429.346, 245620.67 193423.419, 245557.446 193210.697, 245616.718 193160.645, 245593.009 193119.813, 245520.565 193172.499, 245514.638 193169.206, 245500.149 193066.467, 245491.588 192959.777, 245502.783 192896.553))

**Error:** can not mix dimensionality in a geometry

**Expected behavior**
geometry should be either in 3d or 2d.

**Additional context**

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by SilPal** [comment]
@olivermay Hello Oliver, can you take a look at this issue please ? Our GNA application cannot import this GW because of the geometry.
Thanks & best regards, Silvie

**Comment by olivermay** [comment]
This was a data issue, we corrected the data and this should be OK now.
