### ISSUE TITLE
GIPOD Beta SSL Certificate cannot be verified

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#300]
When I try to create a POST Request to the GIPOD beta environment my library informs me that the SSL Certificate cannot be verified.

The error that I get is: SSL Error: Hostname/IP does not match certificate's altnames)

The endpoint used is: https://api-gateway.beta.gipod.vlaanderen.be/api/v1/groundworks

(the same is true for the documentation site: https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/GetGroundwork Firefox warns me not to trust this website.

**Comment by olivermay** [comment]
It seems you are using the old URL's. The correct URL's are listed in this issue: #289
