### ISSUE TITLE
Timestamp API is not the same as GUI

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#302]
**Describe the bug**
The timestamp of the period of a groundwork in the GUI is not the same as the one in the API call:
![image](https://user-images.githubusercontent.com/47892553/140892302-a706af0d-7d2a-4ed2-925f-ff708bdd81b7.png)

![image](https://user-images.githubusercontent.com/47892553/140892373-ddde7871-71f1-48dc-a319-df7f9650990b.png)

**Expected behavior**
We expect them to be the same.

**Additional context**
Problem with winter hour conversion? 

**Correlation id and request**
https://private-api.gipod.beta-vlaanderen.be/api/v1/groundworks/10506274

**Comment by AIV-Bert** [comment]
Hi @TomCap1432,

The API uses UTC time.
The website shows the time in local Belgian time.

> In Belgium the standard time is Central European Time (UTC+01:00). Belgium observes Summer Time (daylight saving time) from the last Sunday in March (02:00 CET) to the last Sunday in October (03:00 CEST).

Kind regards,

Bert

**Comment by TomCap1432** [comment]
Hi @AIV-Bert 

So we need to send an updated timestamp in the API call to get the time on 00:00:00 in the GUI? 

Thanks in advance,
Tom

**Comment by AIV-Bert** [comment]
Hi @TomCap1432,

All dates in your requests to the API should be in UTC time. It appears that you sent the incorrect time in your original request. Like you suggest, this can be fixed through an update to the API. Or by editing in the UI.

Kind regards,

Bert
