### ISSUE TITLE
Groundwork is not getting created

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#303]
**Describe the bug**
We get a 201 HTTP-response from GIPOD when we create a groundwork but if we do a read after 15min or multiple hours, we still get a 404 code. Also the groundwork is not visible in GIPOD platform.

**Expected behavior**
When we get a 201 code, we expect that the groundwork is created.

**Correlation id and request**
{
    "status": 201,
    "message": "Groundwork was registered.",
    "location": "/api/v1/groundworks/10508181"
}

https://private-api.gipod.beta-vlaanderen.be/api/v1/groundworks/10508181
{
    "type": "https://httpstatuses.com/404",
    "title": "The requested resource could not be found.",
    "status": 404,
    "detail": "No groundwork found for GipodId: 10508181."
}

**Comment by AIV-Bert** [comment]
Hi @TomCap1432,

We had an issue on the beta environment. Items created after 6:00 this morning weren't showing up. This is now resolved.

Website:
![image](https://user-images.githubusercontent.com/55388892/143430190-29d5d981-2055-4566-9b66-8e62232b88b9.png)

 
 Kind regards,
 
 Bert
