### ISSUE TITLE
It's not possible to create or update a groundwork on the BETA environment

### ISSUE THREAD

**Issue by JoYsenbaardt** [Informatievlaanderen/GIPOD#304]
After saving a new created groundwork or updating an existing one, the below error message is shown :
"Fout. Er ging iets mis bij het laden."
Below this message the button 'Probeer opnieuw' is shown.

Can this be investigated and corrected ?

Thanks,
Jo

**Comment by Roel** [comment]
I can confirm this with recently created works: I can create it, but subsequently get a 404 when requesting it by id. E.g. work 10680550 on beta.

**Comment by AIV-Bert** [comment]
Hi @JoYsenbaardt  & @Roel,

Our beta environment was processing the creates and updates very slow. We have resolved this issue and you should once again see the normal behavior.

Kind regards,

Bert
