### ISSUE TITLE
500 request attachment creation

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#305]
Dear,

We are sending a request from our system to gipod but we always get a 500 request, if we send the request through postman then we get a 201 request. Is it possible to see what the cause is of the 500 request?

Request date http 500 (timestamp : Jan 05, 2022, 20:06:28):
![POST1](https://user-images.githubusercontent.com/47892553/148275271-0655e710-3e1f-46bc-bb62-cb91a9f06a43.png)
![POST2](https://user-images.githubusercontent.com/47892553/148275324-e001ef81-b6b6-48cf-b914-13229312809d.png)

Request date http 201 (timestamp:  05 Jan 2022 20:11:11):
![Postman](https://user-images.githubusercontent.com/47892553/148275213-135c0141-dab0-442d-bc0e-ad11bb883b74.png)

Binary file is the same for both requests:
[MessageFlowBody.txt](https://github.com/Informatievlaanderen/GIPOD/files/7817269/MessageFlowBody.txt)

Thanks in advance,
Tom

**Comment by olivermay** [comment]
Hi Tom, 

we see following error in the back-end on these requests:
'Transfer-Encoding: chunked' header can not be used when content object is not specified.

**Comment by TomCap1432** [comment]
Hi Oliver,

I am sending the Content-Type in the HTTP-header, how is the content object determined, in which HTTP-header is this specified? 

Thanks in advance,
Tom

**Comment by TomCap1432** [comment]
> Hi Tom,
> 
> we see following error in the back-end on these requests: 'Transfer-Encoding: chunked' header can not be used when content object is not specified.

Is it possible the HTTP-header Transfer-Encoding: chunked is not allowed by the API because it can't read the encoded chunks?

**Comment by TomCap1432** [comment]
Dear @vmateiaiv ,

The problem is we use a framework that either use "Transfer-Encoding: chunked" or "Content-Length".
If we send the request as a string then the Content-length is filled, but due to encoding to string there is data loss.
If we send it as a file Transfer-Encoding is used, but it seems like the API can't handle such requests.

Can the API handle the HTTP-header Transfer-Encoding?

Thanks in advance,
Tom

**Comment by AIV-Bert** [comment]
> Can the API handle the HTTP-header Transfer-Encoding?

No it does not.

**Comment by TomCap1432** [comment]
Ok thanks for the confirmation, I have implemented an alternative to meet your requirements.
Thanks for the support!
