### ISSUE TITLE
Groundwork is not getting created

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#306]
Describe the bug
We get a 201 HTTP-response from GIPOD when we create a groundwork but if we do a read after 15min or multiple hours/days, we still get a 404 code. Also the groundwork is not visible in GIPOD platform.

Expected behavior
When we get a 201 code, we expect that the groundwork is created.

Correlation id and request
{
"status": 201,
"message": "Groundwork was registered.",
"location": "/api/v1/groundworks/10697094"
}

https://private-api.gipod.beta-vlaanderen.be/api/v1/groundworks/10697094
{
"type": "https://httpstatuses.com/404",
"title": "The requested resource could not be found.",
"status": 404,
"detail": "No groundwork found for GipodId: 10697094."
}

**Comment by AIV-Bert** [comment]
The request was registered but the groundwork was not created. We fixed this issue, no data was lost. You can now request the detail of the groundwork

**Comment by TomCap1432** [comment]
The groundwork can not be searched on the bèta UI:
![2022-01-19 09_48_32-DESKTOP2019 - Desktop Viewer](https://user-images.githubusercontent.com/47892553/150095814-c0559541-deee-4e9a-aaa2-c407eeb8fda7.png)

**Comment by AIV-Bert** [comment]
I can search this in the beta UI. Maybe a local caching issue?
