### ISSUE TITLE
Antwoorden synergieaanvraag suborganisatie id

### ISSUE THREAD

**Issue by basefactory** [Informatievlaanderen/GIPOD#309]
Bij het antwoorden van een synergieaanvraag via de gipod API geven wij het organisatie id van de suborganisatie mee.
In dit geval is dit Fiberklaar - DG010 CP, op de synergieaanvraag wordt echter onder de aangeschreven organisaties "Fiberklaar" aangemaakt met daar het positief antwoord aan gekoppeld.  Het antwoord wordt echter niet gekoppeld aan de suborganisatie waarvan we het organisatie id hebben meegegeven in de request.
Komt dit omdat we authenticeren met gebruiker Fiberklaar, zijnde de hoofdorganisatie?  Hoe kunnen we de request opmaken zodat het antwoord gekoppeld wordt aan de aangeschreven suborganisatie zonder dat de hoofdorganisatie wordt aangemaakt.

het betreft 2 synergieaanvragen:
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12655156
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12655181

Het aangemaakt grondwerk en positief antwoord voor suborganisatie DG010 CP is achteraf via de GUI toegevoegd niet via de API.

Met vriendelijke groeten,
Rutger Meeuwis

**Comment by AIV-Bert** [comment]
Beste Rutger,

Heb je een correlation-id van je request waarmee je de synergieaanvraag beantwoord hebt?

Met vriendelijke groeten,

Bert

**Comment by AIV-Bert** [comment]
Beste,

Na even zoeken vind ik de correlationId. 

Dit is de request die jullie verzonden:
`{"joining":"true","organisationId":""}`

Er werd dus geen organisationId mee gestuurd, waardoor de API default naar de hoofdorganisatie.

Aangezien u mij verteld dat jullie wel de suborganisatie meegestuurd hebben, veronderstel ik dat jullie dit in een niet ondersteund veld gedaan hebben. Hierdoor pikt de API dit niet op.

Kan je nakijken of jullie effectief een request versturen die identiek is aan dit voorbeeld:
`{"joining":"true","organisationId":"5f97d30d-7e57-4260-8141-911ef416ab29"}`

Met vriendelijke groeten,

Bert

**Comment by basefactory** [comment]
Onderstaand is de opbouw van onze request, wij hebben geen correlationId meegegeven met de request.

-X PUT
-H "Content-Type: application/json"
-H "Authorization: Bearer xxxxxxxxxxxxxxx"
-d {"joining":"true","organisationId":"5f97d30d-7e57-4260-8141-911ef416ab29"}

**Comment by AIV-Bert** [comment]
Een correlation-id meegeven is optioneel, maar in de response krijg je altijd eentje terug. Die hebben we normaal nodig. 

Maar ik heb intussen al wat research gedaan en de suborganisatie was niet meegegeven of incorrect meegegeven. Daarom hebben we de default genomen (de hoofdorganisatie).

Maar als jullie het meegeven zoals je nu aangeeft, zal alles correct geregistreerd worden onder die organisatie.

**Comment by basefactory** [comment]
Nu werkt het inderdaad, zou het kunnen dat dit samenhing met hetzelfde probleem via de GUI, onderstaande synergieaanvragen zijn via de GUI aangemaakt en daar werden ook hoofdorganisaties aangemaakt ipv de suborganisaties.
Wij zijn echter niet in de mogelijkheid om deze nog te wijzigen.
Bij ons is zeker de correcte organisationId meegegeven, ik heb nu getest en het werkt zoals het hoort zonder dat ik iets aan onze code heb moeten wijzigen.

https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12695390
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12695986
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12696122
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12696383
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12696538
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12696925
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12697181
https://gipod.vlaanderen.be/samenwerking/synergieaanvraag/12697423

**Comment by AIV-Bert** [comment]
Ik sluit deze issue af en ik geef de issue met de synergieaanvragen door aan de vakkundige handen van het operationeel team.
