### ISSUE TITLE
Ophalen SSA id vanuit het grondwerk

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#31]
Hallo,

Hoe kunnen we het SSA id's te weten komen van een bepaald grondwerk ?   Ik zie op vandaag geen mogelijkheid om dit op te zoeken, of mis ik iets ?
Het eenvoudigste is misschien om het grondwerkID toe te voegen aan de selectievelden van het endpoint  "GET /api/v1/trench-synergy-requests"  ?

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Dag Bert,

Wat wil je precies bereiken?

- De ssa's die werden gelanceerd vanuit een bepaalde grondwerk.
- De ssa's waarin een bepaald grondwerk in een antwoord is opgenomen.

Mvg,
Jürgen.

**Comment by hij242** [comment]
Hallo Jürgen,

Het eerste, de SSA's die gelanceerd werden vanuit een grondwerk.

Mvg,
Bert

**Comment by doomsju** [comment]
Ok, We zullen het op onze backlog plaatsen.

We houden u op de hoogte. Bedankt voor de feedback!

Mvg,
Jürgen.

**Comment by doomsju** [comment]
Dit is opgenomen in onze huidige sprint.

Er wordt een extra query-string parameter (launchingGroundworkId) voorzien op het endpoint: GET /api/v1/trench-synergy-requests.

**Comment by hij242** [comment]
Bedankt Jürgen !
