### ISSUE TITLE
500 when creating synergie request on bèta, staging and production

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#312]
**Describe the bug**
We get a 500 response when creating a synergy request, Tuesday this request was still working.
This behaviour is for all the environments.

**Expected behavior**
We expect a 201 response.

**Additional context**
Timestamp bèta: "Date": "Thu, 09 Jun 2022 11:17:01 GMT", can you see in your logs why it is failing to create a trench synergy request?

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by bertzor** [comment]
![image](https://user-images.githubusercontent.com/42960275/174756632-10b8db58-2690-4396-9750-1b382c2aad9f.png)

**Comment by TomCap1432** [comment]
https://private-api.gipod.staging-vlaanderen.be/api/v1/groundworks/11355186

Tue, 21 Jun 2022 08:55:27 GMT -> 10:55 lokaal
![image](https://user-images.githubusercontent.com/47892553/174761213-f2c0deb2-80c4-4fcd-92d9-e543ecdc4765.png)
