### ISSUE TITLE
API different then internal data GET request for groundwork

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#313]
**Describe the bug**
We receive a date one day later then it is visualized in GIPOD UI
![image](https://user-images.githubusercontent.com/47892553/173566104-25802fbf-6e35-4156-89bc-6938f3d26e89.png)

Data in internal API:
![image](https://user-images.githubusercontent.com/47892553/173566152-88aad88f-8083-41df-a831-073fa2c506c0.png)

Data we receive from API:
![image](https://user-images.githubusercontent.com/47892553/173566226-99dbec60-c54e-479c-b785-3caa8f567e86.png)

**Expected behavior**
We expect the dates to be the same.

**Additional context**
https://gipod.beta-vlaanderen.be/toelatingen/vraagvoorgrondwerken/10815080

**Comment by bertzor** [comment]
Hi @TomCap1432,

The internal data is build to fit the needs of our UI. We use this to build the text 'Toelating van 15/06/2022 tot en MET 17/06/2022.' The UI is build for local use, so we see the local time in the webpage.

The API states the period starts at 2022-06-14 22:00 UTC and ends at exactly 2022-06-17 22:00 UTC. 

Let's translate:

- 2022-06-14 22:00 UTC --> 2022-06-15 00:00 local time
- 2022-06-17 22:00 UTC --> 2022-06-18 00:00 local time is the moment this ends, so it runs up to and including 17-06-2022
"van 15/06/2022 tot en MET 17/06/2022.'' -->  "from 15/06/2022 up to and including 17/06/2022"

Both versions are correct and mean exactly the same.

Kind regards,

Bert
