### ISSUE TITLE
Search request for groundwork & vs &amp;

### ISSUE THREAD

**Issue by TomCap1432** [Informatievlaanderen/GIPOD#315]
**Describe the bug**
/api/v1/request-for-groundworks?ownerid=c06b5bf7-31f5-038f-9956-6cc09fac6f86&lastmodified.start=2022-10-11T00:00:00Z&lastmodified.end=2022-10-12T00:00:00Z

/api/v1/request-for-groundworks?ownerid=c06b5bf7-31f5-038f-9956-6cc09fac6f86&amp;lastmodified.start=2022-10-11T00:00:00Z&amp;lastmodified.end=2022-10-12T00:00:00Z

First doesn't return data, second returns data

**Expected behavior**
We expect that '&' is the right seperator instead of '&amp;' for query parameters

**Correlation id and request**
No response: x-correlation-id "91abecbe-2ae7-4694-830f-ca9e90c909fc"
Response: x-correlation-id "4a0bfeed-e99d-4ffd-9eb6-aca7740c8ac7"

**Comment by olivermay** [comment]
Hi Tom, 

Github removed the difference between two cases.

for clearity, the first request is using & and the second & amp, right? 

so you expect & to work, and only & amp works.

kind regards, 

Oliver

**Comment by TomCap1432** [comment]
Hi Oliver,

Indeed & amp works now but before it was only & that worked, our flows are set on &.

Kind regards,
Tom
