### ISSUE TITLE
replace "&" with "&amp;" in paginated views urls

### ISSUE THREAD

**Issue by wdfluv** [Informatievlaanderen/GIPOD#32]
**Describe the bug**
Example response for Trench Synergy Requests To Be Answered Before Deadline1:
{
   "@context":[
      "http://www.w3.org/ns/hydra/context.jsonld",
      "https://api-gateway.beta.gipod.vlaanderen.be/api/v1/context/enriched/public-domain-occupancy.jsonld"
   ],
   "@id":"/api/v1/trench-synergy-requests-to-be-answered",
   "@type":"Collection",
   "totalItems":0,
   "member":[
   ],
   "view":{
      "@id":"/api/v1/trench-synergy-requests-to-be-answered?Limit=10&Offset=5",
      "@type":"PartialCollectionView",
      "first":"/api/v1/trench-synergy-requests-to-be-answered?limit=10&offset=0",
      "previous":"/api/v1/trench-synergy-requests-to-be-answered?limit=10&offset=0",
      "next":null,
      "last":null
   }
}

We inject this JSON in an xml message for further processing through SAP PO.
The `&` character in @id, first and previous results in an error.

**Expected behavior**
An entity reference `&amp;` in the url, instead of a plain & character.

**Additional context**
Above response is when we use the `&` character in the API url.
If we send the GET request with `&amp;` in the API url, the response urls for the views contain `&amp%3B`, which also gets rejected by our xml engine.

If we send the GET request with `%26` in the url, we receive a validation error: `The value '10%26Offset=5' is not valid for Limit.`

**Correlation id and request**
If you have an issue with an API request, please provide the correlation id (found in the response header) and request.

**Comment by CobeLapierre** [comment]
Dear @wdfluv 
We have looked into this.
It is not the responsibility of an api to encode such values.
Different consumers could expect different encodings.
When reading the values you can encode these before writing them to the specific target.
In your case this would be xml escape the json.
