### ISSUE TITLE
Signaling permit: process description

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#33]
Is there documentation available that describes the flow of a signaling permit? These were shown on a workshop, but I don't find them (at first glance) on Confluence. IT would be helpful to see if we are having it right.
 I only find some business rules on the following page: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1234764302/Business+regels+Inname.
On this page, an attachment is mentioned for the signaling permit, but I don't see the attribute in the API. Will it be added?

**Comment by olivermay** [comment]
Hi Berdien, 

You can find the current version of the flows (Flows.pdf) on this page: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1725464916/2020-06-29+BWG+22

If you prefer, we can elaborate which api's to use during the next vragenuurtje. Just let us know!

kind regards, 

Oliver

**Comment by berdienderoo** [comment]
Hi Oliver,

Thanks. Is it correct that based on signaling requests that a city receives, in GIPOD both a mobility hindrance object and a signaling permit should be registered (either by the tool of the city or gipod)? 
I think I've found the API's already, so for now, no need to further elaborate on this.

**Comment by berdienderoo** [comment]
Is there any update available on this. As the deadline is coming closed, it suprises me that even the documentation on flows and business rules is not available on Confluence. The same counts for the 'Request for Groundworks' (https://github.com/Informatievlaanderen/GIPOD/issues/37).

**Comment by olivermay** [comment]
Hi Berdien, you are correct. I will create some high level flows for Signaling permit and request for groundworks, and describe some common cases.

As for the deadline, the api's and ui for signaling permit and request for groundworks will be available for the release in November (most is already available on beta), however the decree won't be active as early as June 2021. Nevertheless we do want to encourage everybody to start the process on request for groundworks and signaling permit, so your concern does make sense.

**Comment by berdienderoo** [comment]
Thanks Oliver.
Are the API's for request for groundwork already available in beta? I can't see them. Same for UI of signaling permit and request for groundwork.

**Comment by olivermay** [comment]
Sorry, the request for groundwork is being implemented, and will be available in beta in our next beta release. Keep an eye on github for the next release, probably next week. 

The user interfaces will be developed later (currently UI is working on trench synergy), I'll try to keep you updated when we come closer to development and we can share some mock-ups. 

Very high level, for signaling request, in the GIPOD UI the local government will see a list of signaling requests that they can inspect and update the status (and attach the permit) after their internal process is done. This internal process is out of scope of GIPOD, we only need to know the status of a signaling permit. In your case where the municipality uses a third-party tool, the GIPOD UI will probably not be used, and everything happens trough your tool.

For requesting a signaling permit, a contracter will be able to enter a groundwork (or synergy) id, and will be either routed to the tool of the local government, or will be able to request the signaling permit trough GIPOD when the local government does not have a tool. For other public domain occupancies such as events, the users will need to contact the local government directly (the municipalities are in charge of entering these pdo's and signaling permit into GIPOD).

For the request for groundworks, the local government or manager of the domain will see a list of requests and they can inspect and update the status. The request will be done trough the API, or a simple form in the GIPOD ui.

**Comment by berdienderoo** [comment]
Thanks Oliver for the feedback. The general (positive) flow was already clear to me, but I'm particularly interested in the negative flows. What if the contractor cancels his request (for some reason) or if the local government decides to refuse the permit request, do we then remove the mobility hindrance the permit is linked to?, etc.

Is it also the intention to store signaling permits for all gipod intakes? I thought it as only meant for groundworks.

How will GIPOD decide if the local government has a tool or not? Is this based on the availability of a service account for the municipality or will the cities be contacted or the service providers?

**Comment by berdienderoo** [comment]
Is there any confluence page describing the processes? In the cocreation doc I can only find the positive flow. It would be good to see if we are implementing the negative ones right.
Furthermore, will there be an api available to delete signaling permits? I don't see it in the api now. This seems necessary to remove wrongly created objects (e.g. cancelled by the contractor).

**Comment by olivermay** [comment]
Hi Berdien, 

sorry for the long delay, you can find the documentation here: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1904902145/Signalisatievergunning+grondwerken+-+DRAFT
