### ISSUE TITLE
GUI keeps reloading

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#35]
**Describe the bug**
I navigate to https://new.beta.gipod.vlaanderen.be/, then click innames and the 'aanmelden' button starts loading. After a while 'Aanmelden' appears, but immediately starts loading again. 
If I first click the 'login' button, I'm redirected to the login page of AIV and then redirected again to https://new.beta.gipod.vlaanderen.be/ However, I'm not logged in.

**Comment by olivermay** [comment]
Hi Berdien, there was a probmen with your account configuration for the new GIPOD (in combination with a known bug). It should work now, but you should force a logout by opening following url: https://new.beta.gipod.vlaanderen.be/auth/logout

Hope it works now!
