### ISSUE TITLE
Token request with scope=gipod_mh_write gipod_mh_read comes up with error

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#36]
**Describe the bug**
Token request via https://beta.oauth.vlaanderen.be/authorization/ws/oauth/v2/token/
with scope=gipod_mh_write gipod_mh_read
comes up with:
{
    "error": "invalid_scope",
    "error_description": "Scope does not exist or is not available."
}

**Expected behavior**
Should be able to request a token with scope above in order to validate Signaling permit APIs.

**Comment by olivermay** [comment]
Hi, you didn't have the correct scopes in our authorisation/authentication service. This is corrected now.
