### ISSUE TITLE
Description and timing flow Vraag voor grondwerken

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#37]
During the previous business workshops the new functionality 'Vraag voor grondwerken' was discussed. The flow showed at that moment is available on https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1693780093/Vraag+voor+grondwerken. However, no details on how this will work in practice is given. 

- What are the attributes of a request for groundworks? 
- What are the business rules? 
- How is the city announced on a new request, through notification? or do they need to search for it? 
- The city needs to register the response on this request in GIPOD, what is needed? 
- Are there other actions needed by the local government?

**Comment by berdienderoo** [comment]
Is there any timing indication when the functional description or desciption on the API's will be available? Since this new concept is announced to be part of GIPOD and a obligation, the integrators need to have enough time to prepare, test and develop this.

**Comment by doomsju** [comment]
"Request for groundworks" is added in the development backlog and if priorities does not change this will be taken up in august.

- Attributes for "request for groundworks":
  - groundwork
  - owner: domain owner (a city, Agentschap wegen en verkeer)
  - applicant: owner of the groundwork
  - remark: a remark added by the applicant
  - status: status of the request
    - In aanvraag
    - In behandeling
    - Antwoord termijn verstreken
    - Akkoord
    - Geen akkoord
  - period: allowed period
  - createdon
  - createdby
  - lastmodified
  - lastmodifiedby

- Business rules:
  - period is mandatory in status "Akkoord".
  - owner can modify to any status except "Antwoord termijn verstreken". This status will be set by the GIPOD system if the answering period is exceeded (6 weeks).
- A search endpoint "request for groundworks" will be available with the following filter criteria:
  - groundworkid
  - ownerid
  - applicantid
  - createdon
  - lastmodified
- Available notifications for "request for groundworks" will determined the coming weeks.
- Owner (a City, AWV) has to modify the status & allowed period

**Comment by berdienderoo** [comment]
Thanks for the feedback. This is already very useful. The only thing that is not clear yet is how the city will be 'notified' of a new request for groundworks. Will an active search via the search endpoint be necessary? Are these done through notifications?...

**Comment by doomsju** [comment]
Both methods will be available (search endpoint & notifications).

**Comment by berdienderoo** [comment]
Is there any update on the timing for these endpoints? When will these be available in the beta environment?
Will the documentation on confluence also be updated? Currently, confluence only contains a pdf with rather complex flow diagrams without any description or business rules.

**Comment by berdienderoo** [comment]
Is it possible that the creator of the request for groundwork changes elements (e.g. period,...) after the creation? This may cause inconsistencies, because the government can be in progress with the processing of the request.

**Comment by doomsju** [comment]
No, that is not the intention. Only owner (city, awv) can modify the request-fro-groundwork.

**Comment by olivermay** [comment]
@berdienderoo we wrote out the flow, you can find it on following page: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1693780093/Vraag+voor+grondwerken+-+DRAFT

As for the timing, currently the "vraag voor grondwerken" is in development. This will be available in beta release 0.10.0 which will be released by the end of september.
