### ISSUE TITLE
Issues with dynamically typed field "value"

### ISSUE THREAD

**Issue by wdfluv** [Informatievlaanderen/GIPOD#38]
Dear,

We are having problems with the dynamically typed "value" field, as used in Modify Groundwork or Modify Trench Synergy.

"value" is used here to store:
- a string
- an array of strings
- a JSON object (period start/end/duration)

SAP PO cannot cope with this. We have a workaround for the Period JSON object, but we're stuck with the arrays.
If value contains one item, it gets encoded as a string by default.
If value contains multiple items, it gets encoded as an array of strings by default.

We can override this default behaviour on a fieldname basis, so that it is encoded as an array of strings even if there is only one item (we do that already in other API calls). But, since all the fields here are named "value", they all get encoded as an array of strings, even the ones that shouldn't be.

Please allow us to propose a couple of changes that would eliminate this issue:
- allow the use of a non-arrayed string if there is only one item in a 0/1..unbounded field
- use different fieldnames for different content types (value, arrayValue, periodValue, ...)
- allow us to add empty or null as a second value in a 0/1..unbounded field, so the default behaviour interprets it as an array
- other suggestions from your side?

Thank you,
Wouter
Fluvius ICT

**Comment by doomsju** [comment]
We will allow a non-arrayed string if there is only one item. 

We will develop this asap and inform you if this is deployed on the Beta environment.

**Comment by doomsju** [comment]
Tomorrow we will release this as a hotfix on the Beta environment.

**Comment by doomsju** [comment]
We hebben een hotfix uitgevoerd: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1771340182/Hotfixes
Is het mogelijk de oplossing te valideren?
