### ISSUE TITLE
missing API GetTrenchSynergyRequestsWithGroundworksToBeAdded

### ISSUE THREAD

**Issue by wdfluv** [Informatievlaanderen/GIPOD#39]
Dear,

Has the API GetTrenchSynergyRequestsWithGroundworksToBeAdded been removed?
It's not visible on the documentation or the swagger page, and I'm pretty sure we didn't come up with that name by ourselves ;)

https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/GetTrenchSynergyRequestsWithGroundworksToBeAdded

Thanks,
Wouter

**Comment by vmateiaiv** [comment]
Hi @wdfluv,

This is indeed an issue. I am fixing it as we speak. In a few minutes it should be available on the api gateway.

Kind regards,
Voicu Matei
AIV
