### ISSUE TITLE
Signalisatievergunning aanvragen: gipod of tool

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#43]
Kunnen we ervan uitgaan dat signalisatievergunningen enkel worden aangevraagd via GIPOD voor steden en gemeenten die niet over eigen software beschikken? Of anders gesteld, moet een stad die beschikt over een softwarepakket voor de afhandeling nog steeds GIPOD gaan raadplegen om eventuele vergunningsaanvragen die daar zijn binnengekomen te behandelen?
Op welke manier zal deze opdeling worden gemaakt?

**Comment by olivermay** [comment]
Je kan er inderdaad vanuit gaan dat aanvragen voor signalisatievergunningen enkel via het eigen pakket worden ingediend, indien de s&g hier over beschikken.

In het aanvraagformulier zal eerst naar de gemeente gevraagd worden. Afhankelijk van de geselecteerde gemeente verwijzen we door naar het formulier bij de gemeente zelf, of het algemene gipod formulier.
