### ISSUE TITLE
List works, groundworks, ... API ?

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#44]
For the moment I can only find an API to query works or groundworks for a known gipodId:
- GET ​/api​/v1​/works​/{gipodId}
- GET ​/api​/v1​/groundworks​/{gipodId}

But we also need to be able to query for all works/groundworks/... 
Or am I overlooking something?

**Comment by doomsju** [comment]
You can use this endpoint for search public domain occupancies: https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#tag/PublicDomainOccupancies

If you want to restrict your results to works, grounworks you have to use the query string parameter typeid. 
The allowed values for this parameter are available in: https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/GetPublicDomainOccupancyTypes

works: 60ad4826-893d-4695-b815-a0adb39287e4
groundworks: 718225ee-78e8-4b6f-bc63-7748cfd0a4d2
