### ISSUE TITLE
Question on Signaling permit API

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#45]
Hello,
At Proximus we have an application which will be integrated with Gipod platform. This application will perform steps below:
1.	Call Get ground works API as it returns the mobility hindrance Gipod id.
2.	Using mobility hindrance Gipod id from step above, call Get mobility hindrance API.

As Get mobility hindrance does not return signalling permits ids, how can these be retrieved? Is there an API to retrieve all signalling permits for a specific mobility hindrance Gipod id?

Thanks for your quick reply !

**Comment by doomsju** [comment]
This is indeed a missing link in the API. We will take this up and inform you when this will be available on the Beta environment.

**Comment by AIV-Bert** [comment]
Hi @rajeevchugh71 

As @doomsju stated, this is added to our backlog for a future release. However, it won't be in the 0.8.0 release.

**Comment by doomsju** [comment]
This will be available in the next release of the API (version 0.9.0.0).

**Comment by rajeevchugh71** [comment]
Signaling permit is still not being returned in Get Mobility hindrance API call.

For ex. in beta Mobility hindrance Gipod id 10207638 has a signaling permit id 10207639:
https://api-gateway.beta.gipod.vlaanderen.be/api/v1/mobility-hindrances/10207638/signaling-permits/10207639 

but this is not being returned in Get Mobility hindrance API call.

Pls check & feedback.
