### ISSUE TITLE
How to test notifications API?

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#46]
Notifications API have been releases in beta. 
However, performing a Get notifications (/api/v1/notifications) comes up with: "totalItems": 0.

Pls suggest a way(s) to test this API.

**Comment by doomsju** [comment]
On the current Beta-environment there is one notification type implemented. In the coming weeks other notification types will become available.

All implemented notification types are available via this endpoint: /api/v1/taxonomies/notificationtypes.

It's a notification that informs you that a trench synergy request received by your organisation is still to be answered before deadline1.

To receive trench synergy requests your organisation should define a collaboration zone in the GIPOD-system. If a trench synergy request is launched within this zone your organisation will be a receiver for this trench synergy request. If your organisation didn't answer 5 days before deadline1 this notification will be generated.

The manual to define collaboration zones can be found here:
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1661763707/Workaround+instellen+samenwerkingszone+via+Swagger
