### ISSUE TITLE
Vervroegd afsluiten van SSA en inlezen synergie is complex

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#47]
Hallo,

Indien we een SSA vervroegd willen afsluiten om zo een synergie aan te maken dan moeten er 3 api calls na elkaar gebeuren :
* Close Trench Synergie Request
* Get Trench Synergy Request -> voor het ophalen van het synergie ID
* Get Trench Synergy -> voor het ophalen van de sleufsynergie gegevens

Is er geen kortere manier of mis ik iets ?  Het zou handiger zijn mocht de Close Trench Synergie Request ook het synergie nummer teruggeven.

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Bij het vervroegd afsluiten van een SSA krijg je een Http Status Code 202 terug. 

In de response body is er een property "location" opgenomen met de url om het detail van de synergie te kunnen opvragen. Hieruit kan je dus al de id van de synergie afleiden.
```
{
  "status": 202,
  "message": "Trench synergy request was closed.",
  "location": "/api/v1/trench-synergies/{gipodId}"
}
```

Via deze url kan je dan het detail opvragen van de synergie. Let wel op bij het afsluiten van de SSA wordt de synergie niet onmiddellijk aangemaakt. Het kan dus zijn dat je bij onmiddellijk opvragen van de sleufsynergie niet direct een antwoord terug krijgt. Probeer hier dus zeker een retry mechanisme in te voeren. Maar bij normale werking is dat een kwestie van een aantal seconden.

**Comment by hij242** [comment]
Bedankt Jürgen.
