### ISSUE TITLE
SSA status in behandeling.

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#48]
Hallo,

Ik had een SSA aangemaakt met GIPODID 10207689 en Trench synergy ID 10207691.  Deze SSA kwam in de status "Nieuw".   Nadat ik met blauw had geantwoord bleef die in de status nieuw.   Maar nadat de deadline 1 was verstreken bleef de status nog altijd op nieuw staan.  
Volgens de Confluence documentatie zou de status van de SSA toch "In behandeling" moeten komen na het verstrijken van deadline 1 ?

Kunt u dit verduidelijken ?

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Dag Bert,

We hebben gisteren deze bug ontdekt in ons systeem en zijn momenteel een hotfix aan het voorbereiden voor dit issue. Oorzaak was een grondwerk dat werd verwijderd met nog een actieve SSA. Als eens grondwerk wordt verwijderd met nog een actieve SSA zullen we de SSA automatisch laten intrekken.

We gaan dit zo spoedig mogelijk releasen.

mvg,
Jürgen Dooms.

**Comment by doomsju** [comment]
Dag Bert, We hebben hiervoor een fix gedeployed. Kan je valideren?

**Comment by hij242** [comment]
Ik vermoed dat het in orde is maar mijn test was nog volledig.  Momenteel kunnen we geen verbinding meer maken, we krijgen autorisatie fouten terug op alle calls.   Ik test volgende week eens opnieuw.

**Comment by vmateiaiv** [comment]
Beste @hij242 er zijn momenteel idd issues met de authenticatie systeem. Wij zijn dat aan het onderzoeken. Ik laat weten wanneer dat opgelost is.

**Comment by vmateiaiv** [comment]
> Beste @hij242 er zijn momenteel idd issues met de authenticatie systeem. Wij zijn dat aan het onderzoeken. Ik laat weten wanneer dat opgelost is.

>> Dat zou in orde moeten zijn.

**Comment by hij242** [comment]
Dit is aangepast, dank.
