### ISSUE TITLE
Issues with authentication

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#51]
We have some problems with the oauth authentication.

1) It seems that we can't authenticate if the authorization code contains special characters. Is this a known issue? How can we avoid this? 
e.g. the code contains a '+' and the error we received was
{
    "ErrorKey": "invalid_request",
    "error_message": "invalid or missing authorization code. The Code field is required. "
}

2) My colleague hasn't succeeded to authenticate and mostly gets the error 'unsupported_client_assertion_type', while the body is a copy-paste of the one I used.

3) Another colleague is even getting the following message: 'the resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.'. We are both using postman and same settings. What can be the cause of this error?

**Comment by vmateiaiv** [comment]
Hi @berdienderoo,

Could you, please, let me know which OAuth ClientId are you using when you get this error? 

Kind regards,
Voicu Matei 
AIV

**Comment by berdienderoo** [comment]
We are using client with id: 3292

**Comment by vmateiaiv** [comment]
Please make sure you are doing the steps described in this flow:
https://beta.oauth.vlaanderen.be/authorization/Help/Api/B2B

Could it be that the code parameter (authorization-code) was sent without being urlencoded?

Kind regards,
Voicu Matei

**Comment by berdienderoo** [comment]
Not from my side, I have the option set to encode the url. We follow all the same steps, all in postman. For me, it works if the code does not contain a special character.

**Comment by berdienderoo** [comment]
My colleague still has some issues. He updated his postman version, and explicitly set the urlencode option. We started fro mscratch with a new JWT and a new authorisation code. But he now receives the error: "description": "Could not authenticate client through JWT token, Could not authenticate client through the header. Headers do not contain clientcredentials, Could not authenticate client through the body"

**Comment by berdienderoo** [comment]
Update on this issue, one of my colleagues is now able to authenticate (using the latest version of postman). 

However, if we try to authenticate either in postman or in java with an authorization code that contains special characters, it is not possible to authenticate as specified in the original issue

**Comment by berdienderoo** [comment]
We can close the issue, since we switched to client credentials.
