### ISSUE TITLE
Validation errors on RFC3339 date-time fields

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#52]
**Describe the bug**
Validation errors on date-time fields that have a `seconds` part. E.g. in GroundworkPeriod:
```
      "GroundworkPeriod": {
        ...
        "properties": {
          "start": {
            "type": "string",
            "description": "Start date and hour of the groundwork.",
            "format": "date-time"
          },
          ...
        }
      },
```
The date-time format should be RFC3339 (see https://swagger.io/specification/ and https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) but we get validation errors when the seconds part (even when `00`) is filled in.

When using `"period":{"start":"2021-01-16T23:00:00Z"}` -> `{"type":"https://httpstatuses.com/400","title":"One or more validation errors occurred.","status":400,"detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:ModelState","title":"period.start","detail":"The supplied value is invalid."}]}`

When using `"period":{"start":"2021-01-16T23:00Z"}` -> we don't get this validation problem

**Expected behavior**
The request should not be rejected when the seconds (although they must be 00, as for the minutes) are filled in.

**Additional context**
We use libs and generated code for the open-api, quite hard to adjust the code generation not to emit seconds.

**Correlation id and request**
- BUG: x-correlation-id -> List(233bef57-c094-4285-bb4a-0f40ed91eeee)
- WORKING (but it has other validation issues): x-correlation-id -> List(bd3f02f3-54db-454c-85c1-68574f6121fd)

**Comment by vmateiaiv** [comment]
Hi @ireactsam,

This matter is being analyzed internally. We will keep you posted about the evolution.

Kind regards,
Voicu Matei 
AIV

**Comment by AIV-Bert** [comment]
Thank you for the extensive report and the provided correlation-id's.

This bug will be fixed in the next release. Seconds will be allowed but must be 00 like you expect.

**Comment by ireactsam** [comment]
Seems to work for the PATCHes (not yet for the POSTs)

**Comment by doomsju** [comment]
Resolved in https://github.com/Informatievlaanderen/GIPOD/issues/109
