### ISSUE TITLE
Required fields marked as non-required

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#53]
I found a few fields that are required (you get validation issues if not present/empty) but in the documenation (https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.htm and OpenApi spec https://api-gateway.beta.gipod.vlaanderen.be/swagger/v1/swagger.json?culture= ) they are not marked as required:

- RegisterGroundworkRequest
  - groundworkZone
  - contactOrganisation (ContactOrganisation)
    - email
    - organisationId

x-correlation-id: 3994cf32-6e5f-4a24-a655-56baa9c75739

**Comment by ireactsam** [comment]
Also where can I find the validations/requirements for ContactOrganisation, e.g. email must be 'valid' ? Cannot seem to find it in https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html ?

**Comment by vmateiaiv** [comment]
Hi @ireactsam,

- RegisterGroundworkRequest. **groundworkZone** you are right => I marked it as required. This will be visible in the documentation from the next release.

- RegisterGroundworkRequest.contactOrganisation.**email** you are right => I marked it as required. This will be visible in the documentation from the next release.

- RegisterGroundworkRequest.contactOrganisation.organisationId => this is changed in the previous release. Now you can specify contactOrganisation by **organisationId** or by **contactName**. So you need to specify at least one of the 2.

Kind regards,
Voicu Matei
AIV
