### ISSUE TITLE
systeem klok

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#55]
Is het mogelijk jullie systeemklok juist te zetten ?   Die loopt nu 2 uur achter.

Mvg,
Bert De Groote

**Comment by AIV-Bert** [comment]
> Is het mogelijk jullie systeemklok juist te zetten ? Die loopt nu 2 uur achter.

Dag Bert,

De Gipod api gebruikt UTC tijd om tijdsinformatie te specificeren. Als je in een andere tijdzone wil werken, is je eigen applicatie verantwoordelijk om deze om te zetten naar de tijdzone die je verkiest.

Met vriendelijke groeten,

Bert

**Translation:**

> Is it possible to set your system clock correctly? It is now 2 hours behind.

Hi Bert,

The Gipod api uses UTC time. If you want to work in local time, your application is responsible to convert the UTC time the the local time you prefer.

Kinds regards

Bert

**Comment by hij242** [comment]
Dit gaat dan ook het geval zijn in productie veronderstel ik ?

**Comment by AIV-Bert** [comment]
Dit is zo in elke omgeving, ook productie.
