### ISSUE TITLE
Grondwerk op uitgevoerd zetten geeft statusfout

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#56]
Hallo,

Ik heb een probleempje met de Modify Groundwork.   Omdat wij vertrekken van een oude, zelf geschreven applicatie, sturen we bij deze patch telkens alle velden door en niet enkel de velden die wijzigen.  Dit werkt goed tot op het moment wanneer we het grondwerk in uitvoering willen zetten.

Ik krijg volgende foutboodschap : 
Groundwork should be in GroundworkStatus: Voorontwerp, Niet-concreet gep
land, Concreet gepland or In uitvoering   Groundwork should be in Ground
workStatus: Voorontwerp, Niet-concreet gepland, Concreet gepland or In uitvoering

Ik heb dit dan nagespeeld in de Swagger en ben tot de conclusie gekomen dat wanneer we enkel de datum en de status uitgevoerd meegeven, dan werkt het.  Maar van zodra dat we extra velden meegeven (die niet wijzigen), dan krijgen we deze foutboodschap.  Dat lijkt me niet logisch.

Deze JSON werkt:

{
"items": [
{
"key": "Period",
"value": {
"start": "2020-07-23T00:00Z",
"end": "2020-07-24T23:59Z",
}
},
{
"key": "StatusId",
"value": "3603c0b5-778e-4407-ae57-7300e0694888"
},
]
}

En deze JSON geeft dus de fout:

{
"items": [
{
"key": "Description",
"value": "Elektriciteit 100 M Verplaatsing"
},
{
"key": "Reference",
"value": "P/027017"
},
{
"key": "Period",
"value": {
"start": "2020-07-24T00:00Z",
"end": "2020-07-24T23:59Z",
}
},
{
"key": "StatusId",
"value": "3603c0b5-778e-4407-ae57-7300e0694888"
},
{
"key": "PublicDomainOccupancyTypeIds",
"value": [
"a486a968-e498-4708-8820-901686f0712f"
]
},
{
"key": "CategoryId",
"value": "bb0b471a-7f4d-4eaa-b788-adae1aaf30f8"
},
{
"key": "GroundworkZone",
"value": "POLYGON((241955.2200 167598.5032,242202.2200   167663.5032,242259.4200 167464.6032,242046.2200 167390.5032,241955.2200   167598.5032))"
},
{
"key": "SpecificationIds",
"value": [
"bce64878-6cb7-43e7-896c-e01202a05e4c"
]
},
{
"key": "IsRelocationGroundwork",
"value": false
},
{
"key": "GrbImpactId",
"value": "25750cda-438f-40b5-bf43-10668bd9b40b"
},
]
}

Ik heb eens alles verwijderd na de statusID, ook dat gaf een probleem.   Kunnen jullie dit eens bekijken ?

Mvg,
Bert De Groote

**Comment by cobelapierre-kbvlaanderen** [comment]
Hi Bert,
This is indeed unexpected behaviour and a bug in our code.
We will solve this and get back to you.
Kind regards

**Comment by ireactsam** [comment]
I have noticed the same issue in `x-correlation-id: 705aa9bf-d234-4e19-b6f1-8af0b9a5f3ea` :
```
{"type":"https://httpstatuses.com/400","title":"One or more validation errors occurred.","status":400,"detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:InvalidGroundworkStatusException","title":"Groundwork should be in GroundworkStatus: Voorontwerp, Niet-concreet gepland, Concreet gepland or In uitvoering","detail":"Groundwork should be in GroundworkStatus: Voorontwerp, Niet-concreet gepland, Concreet gepland or In uitvoering"}]}
```

**Comment by vmateiaiv** [comment]
Hi @ireactsam, @hij242 

We will release a hotfix for this issue today.

Kind regards,
Voicu Matei
AIV

**Comment by hij242** [comment]
Ik heb het getest en het werkt nu, bedankt !
