### ISSUE TITLE
Modify trench synergy gives problem "User needs to be member of the pilot organisation"

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#57]
Hallo,

Ik probeer om een grondwerk toe te voegen aan een bestaande synergie.  Dit zou normaal moeten lukken via de patch "/api/v1/trench-synergies/{gipodId}".

Telkens krijg ik de boodschap "User needs to be member of the pilot organisation", ook wanneer ik geen aanpassing doe aan de lijst met grondwerken.  De piloot van de synergie is de suborganisatie Fluvius Hasselt maar we loggen steeds in met de hoofdorganisatie.    

Ik krijg ook dezelfde boodschap wanneer ik enkel de periode aanpas in de patch request.

Met vriendelijke groeten,
Bert De Groote

**Comment by vmateiaiv** [comment]
Beste @hij242 ,
Idd, de wijziging moet mogelijk zijn voor organisaties in de tree van Fluvius.
Wij hebben een fix klaar for deze issue. Komt naar BETA in de volgende release.

Mvg,
Voicu Matei
AIV

**Comment by hij242** [comment]
Laat je me weten wanneer de volgende release doorgaat ?

**Comment by AIV-Bert** [comment]
We zijn de release intern aan het testen. Je mag hem deze week verwachten
