### ISSUE TITLE
Updating a groundwork

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#58]
It looks like I can only update a groundwork (which first was created via POST /api/v1/groundworks) using:
- PATCH /api/v1/groundworks/{gipodId} 
- PUT /api​/v1​/groundworks​/{gipodId}​/contactorganisations​/{contactId}

The {gipodId} I get back from the (successful) POST, but I don't know the {contactId}s? Unless I GET /api/v1/groundworks/{gipodId} and try to match the the @ids of the contactOrganisation with the contactOrganisations I submitted in the POST? That makes it really hard, and would require me to store those Ids so I can later update them?

- Or what is your take on updating a groundwork (and it's contactorganisations)?
- Is there no PUT /api/v1/groundworks/{gipodId} where I can just submit the complete updated `RegisterGroundworkRequest` to ?
- it seems I cannot change the ownerId ?

**Comment by AIV-Bert** [comment]
Hi @ireactsam 

My take on updating a contactorganisations is

1. Request the groundwork to get a list of contactorganisations
2. Present the list to the user (and keep the id's locally)
3. Have the user change one or more contactorganisations
4. Submit the modified contactorganisations to the right endpoint using the saved id

Would this be possible for you? If not can you give a more detailed example?

There is no PUT endpoint for Groundwork (Work or Event). The updates need to be provided through the PATCH endpoint.

You cannot change the owner YET. It is on the roadmap to change the owner to another organisation from within the current organisation hierarchy. A specific release number or release date is not yet decided.

**Comment by ireactsam** [comment]
That is basically what I'm doing now. Our case is different in that we synchronise our Werf data with Gipod², meaning there is no 'present the list to the user and let him decide' but rather a 'get the list, compare it with what we have and make a diff to compute the POSTs(add)/DELETEs (we can't use PUT here since don't know what element was changed or happened to be added in a different role e.g.)

To make a good Diff, we need the get same info as the data we posted originally, therefor I opened #67.

**Comment by ireactsam** [comment]
With the above, I only have this open:

- it seems I cannot change the ownerId ?

**Comment by AIV-Bert** [comment]
Changing the owner for Groundwork, Work, Event or Mobility Hindrance is currently not supported. This feature already exists in our backlog and will be added in a later release.

**Comment by doomsju** [comment]
Modify the owner is available in release https://github.com/Informatievlaanderen/GIPOD/issues/150
