### ISSUE TITLE
Oranje/blauw/groen bijdragerBeta heeft geen toegang tot de noficaties

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#59]
Hallo,

Is het mogelijk om de testgebruikers ook toegang te geven tot de notificaties ?  De autorisatie scope gipod_notifications ontbreekt.  

Omdat we momenteel nog geen interessezones hebben per suborganisatie is dit de enige manier om de notificaties eens te kunnen bekijken.

Mvg,
Bert De Groote

**Comment by AIV-Bert** [comment]
Beste Bert,

De web applicatie vraag momenteel de scopes niet op voor de notificaties. De testgebruikers hebben echter al toegang. We gaan in een hotfix van de Gipod UI de nodige scopes toevoegen voor jou. Vanaf dan zal je de notificaties voor de testgebruikers kunnen opvragen, met de token die je uit de UI haalt.

Met vriendelijke groeten,

Bert Lerno

**Comment by AIV-Bert** [comment]
Beste Bert,

Als je nu **opnieuw** inlogged op https://new.beta.gipod.vlaanderen.be/ krijg je een token waarmee je dan in onze Swagger de notificaties kan bekijken.

Ik hoor graag of dit voldoende voor je was.

Met vriendelijke groeten,

Bert Lerno

**Comment by hij242** [comment]
Dit is voldoende, dank !
