### ISSUE TITLE
Delete a work or mobility-hindrance ?

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#60]
There is a DELETE ​/api​/v1​/groundworks​/{gipodId}, but there is no

- DELETE /api/v1/works/{gipodId}
- DELETE /api/v1/mobility-hindrances/{gipodId}

How can I remove works and mobility-hindrances? How will I be able to change a work to a groudwork or back to a work ?

**Comment by vmateiaiv** [comment]
Hello @ireactsam 

DELETE /api/v1/works/{gipodId} - is available:
![image](https://user-images.githubusercontent.com/55380575/88898198-ac66ff00-d24c-11ea-8453-a52d5127b56c.png)

DELETE /api/v1/mobility-hindrances/{gipodId}: indeed missing. We will discuss it internally and keep you posted.

For the moment, switching a work <=> groundwork is not possible. 
Could you, please, describe the use-case why you would need this functionality?

Kind regards,
Voicu Matei
AIV

**Comment by ireactsam** [comment]
Hi @vmateiaiv ,

I must be using an out-dated version? Can't find the DELETE works in:
- https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1244102849/Works
- https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#tag/Works

In our AWV Werf application, a werf can easily switch from type: 
![image](https://user-images.githubusercontent.com/29482028/88899995-0cf73b80-d24f-11ea-920b-b1a018728470.png)
Type (Her)aanleg, Herstelling map to Gipod² Groundwork
Type Onderhoud, Inspectie, Reiniging map to Gipod² Work

kr

**Comment by vmateiaiv** [comment]
Hi @ireactsam,

You are right. Sorry for this. That screenshot was taken from our test system. Not from BETA. 
The feature is there for works but not yet released. It will be in the next release.

Kind regards,
Voicu Matei
AIV

**Comment by AIV-Bert** [comment]
Hi @ireactsam 

Switching between the 3 main types **Groundwork**, **Work** and **Event** will not be supported in our api.

It might be helpful to know both **Groundwork** and **Work** have the option to add a "**Specification**". These _specifications_ can be 'Herstel/onderhoud' or '(her)aanleg'. Can this be of use for your implementation?

More info on:
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1234764302/Business+regels+Inname

Kind regards,

Bert Lerno

**Comment by AIV-Bert** [comment]
The delete 'work' endpoint is missing in our current swagger documentation. This will be added next release, later this week

**Comment by ireactsam** [comment]
The DELETE /api/v1/mobility-hindrances/{gipodId} is still missing though ?

**Comment by doomsju** [comment]
Delete mobility hindrance is on our backlog.
