### ISSUE TITLE
GET /api/v1/trench-synergy-requests-to-be-answered werkt niet voor suborganisaties

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#61]
Hallo,

Wij loggen aan vanuit ons backend systeem met 1 Fluvius account maar we werken per suborganisatie.  Ik heb een zone ingetekend voor Fluvius Hasselt en een SSA aangemaakt met de oranje testgebruiker (grondwerk 10207924, SSA 10207925).

Wanneer ik de GET /api/v1/trench-synergy-requests-to-be-answered dan krijg ik deze SSA niet te zien via de algemene Fluvius gebruiker.  Ik vermoed dat de GET /api/v1/trench-synergy-requests-with-groundworks-to-be-added op dezelfde manier werkt.

Kunt u deze endpoints ook voorzien op suborganisaties ?

Mvg,
Bert De Groote

**Comment by vmateiaiv** [comment]
Beste @hij242,

Wij zijn de mogelijkheden aan het bekijken.

Mvg,
Voicu Matei
AIV

**Comment by doomsju** [comment]
Dit is opgenomen in de backlog om aan te passen. Beiden lijsten zullen standaard alle SSA's teruggeven die een organisatie binnen uw organisatiestructuur heeft ontvangen. Er zal ook de mogelijkheid geboden worden om te filteren op één of meerdere sub-organisaties.

Mvg,
Jürgen.

**Comment by hij242** [comment]
Hallo Jurgen,

Dit wordt wel dringend voor mij.  Wanneer wordt dit op beta beschikbaar ?

Mvg,
Bert De Groote

**Comment by doomsju** [comment]
Resolved in https://github.com/Informatievlaanderen/GIPOD/issues/109

**Comment by JanDegroote** [comment]
Bedankt alvast!
