### ISSUE TITLE
Search for different organisation names in one call

### ISSUE THREAD

**Issue by hixfield** [Informatievlaanderen/GIPOD#62]
To optimise the number of requests made to the GIPOD API we would like to have the ability to execute 

`{{baseUrl}}/api/v1/organisations?organisationName=xx,xx,xx`

where `xx,xx,xx` can be a list of organisation names.

In short we would like to be able to retrieve the organisations for "org1", "org2" and "org3" in one call.
**I don't think this is currently already supported (could not find anything in the doc)?**
_I did try supplying comma separated list but that dit not work._

As alternative we can call the API multiple times with the different organisation names and combine this ourselves.

**Comment by vmateiaiv** [comment]
Hello @hixfield, 

We are analyzing this internally and will keep you posted about the result.

Kind regards,
Voicu Matei
AIV

**Comment by hixfield** [comment]
Thank you @vmateiaiv. If we are doing that, could we analyse to see if the same logic would be possible for the 
`{{baseUrl}}/api/v1/public-domain-occupancies`
meaning to specify multiple ownerId's?

**Comment by AIV-Bert** [comment]
Hi @hixfield,

It is already possible to specify multiple OwnerId's when submitting a search request to 
**​/api​/v1​/public-domain-occupancies**.
![image](https://user-images.githubusercontent.com/55388892/89121528-fa376d80-d4bf-11ea-9110-8efaf48d871e.png)

The feature request to support multiple organisation names on **/api/v1/organisations** is being reviewed.

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
Your request is added to our backlog, however given the current time constrains this is low priority.
