### ISSUE TITLE
zoneId contains a path prefix

### ISSUE THREAD

**Issue by hixfield** [Informatievlaanderen/GIPOD#63]
Referring to the output of:

`{{baseUrl}}/api/v1/public-domain-occupancies?ownerid={{organisationId}}`
`{{baseUrl}}/api/v1/groundworks/{{projectId}}`

The zone identifier is specified as a path:

```
          "zone": [
                {
   >>>>>>>"@id": "/api/v1/groundworks/2855465/zones/34a258d0-ec2f-4d75-b64c-a13fe8daad92",
                    "@type": "Zone",
                    "zoneType": {
                        "@id": "/api/v1/taxonomies/zonetypes/6ee12839-8002-4f51-b509-4000b4a29b44",
                        "prefLabel": "GrondwerkZone"
                    }
                }
            ],
```

This means the API consumer should strip the path away, before getting access to the "pure" zone id to be used in for example the `{{baseUrl}}/api/v1/groundworks/{{projectId}}/zones/{{zoneId}}`

Would it not make sense to include just the zone Id without any path in front?
Possibly a bug?

**Comment by vmateiaiv** [comment]
Hello @hixfield,

To get the zone detail you could follow the link in the response. Ofcourse the baseUrl must be added in front.
Someting like this: {{baseUrl}}/api/v1/groundworks/2855465/zones/34a258d0-ec2f-4d75-b64c-a13fe8daad92.

Is that a possibility?

Kind regards,
Voicu Matei
AIV

**Comment by hixfield** [comment]
In that case I prefer stripping out the pure id by removing everything until the last `/`.
Because I am not in favour of letting the returned web service date direct my app to a path to the be used for a subsequent web service call. It sound a bit to loosely coupled for me... Do you have another opinion or maybe a reason not to do it like that?

**Comment by hixfield** [comment]
Thanks for the reply. I do understand your point. However, I have never encountered this approach before. And it is difficult to for example also use this with postman (although not impossible). We should also also consider that the end points are also written up in documentation. So if the return uri would change it would break the contract for the API in my opinion, because that would mean that the end pont for getting a zone based on a zone id would have been changed...

**Comment by AIV-Bert** [comment]
You are correct a change in URI would break the contract of the API. However with these 'linked data' URI's you can arm code against these kind of changes. If you want to implement this, is entirely upto you. 

The current setup supports both ways.
