### ISSUE TITLE
Niet duidelijk hoe een zone op het grondwerk geupdate moet worden.

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#64]
Hallo,

Kleine vraag.  Voor het updaten van de zone op een grondwerk lijken er 2 mogelijkheden ;
* via de Modify Groundwork : hier kan je rechtstreeks de zone meegeven (input = gipodID)
* via de Modify Groundwork Zone : hier moet je op basis van het zoneID + GipodID een aangepaste zone meegeven.

Waarom deze 2 manieren van werken of zijn er nadelen verbonden aan één van de 2 manieren ?   Ons lijkt het makkelijkst om de eerste te gebruiken, de 2de lijkt dan niet echt zinvol.  Of mis iets ?

Kan je dit even verduidelijken ?

Mvg,
Bert De Groote

**Comment by AIV-Bert** [comment]
Dag Bert,

Beiden zijn mogelijk. Er zijn geen voor of nadelen verbonden aan een keuze. 

Ik zou inderdaad de eerste gebruiken. Dit is ook voor andere soorten resources in onze api de meest gebruikelijke.

Met vriendelijke groeten,

Bert
