### ISSUE TITLE
Upon Add/Delete contactorganisation to Groundwork: An unexpected error occurred. Please retry or contact the service administrator."

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#66]
Since there is no way to modify the contactOrganisation(s) of a Groundwork, I tried to:

1. GET /api/v1/groundworks/{gipodId}
2. for each {contactId} in {groundWork.contactOrganisation.id}: GET /api/v1/groundworks/{gipodId}/contactorganisations/{contactId}
3. compute DIFF of toAdd/toDelete contactorganisations
4. for each addition: POST /api/v1/groundworks/{gipodId}/contactorganisations
5. for each deletion: DELETE /api/v1/groundworks/{gipodId}/contactorganisations/{contactId}

Since my diff is not yet perfect, it will try to add the same contactorganisations and delete the (original) contactorganisations.
- adding succeeded: 
```
additions = List(CreatedResponseBody(201,Some(/api/v1/groundworks/10207908/contactorganisations/5c83d72b-7912-4501-9e94-a7683116eb25),Some(Groundwork contact organisation was added.)), CreatedResponseBody(201,Some(/api/v1/groundworks/10207908/contactorganisations/677cc30d-0a55-402f-b372-4fae72863293),Some(Groundwork contact organisation was added.)))
```
- but deletions gave: 
```
500 Internal Server Error - Some({"type":"https://httpstatuses.com/500","title":"Unexpected error.","status":500,"detail":"An unexpected error occurred. Please retry or contact the service administrator."}) - x-correlation-id: 9fca88f0-e288-4484-8279-e47ec1929843
```

In another case, I got the same 500 even during the addition:
```
500 Internal Server Error - Some({"type":"https://httpstatuses.com/500","title":"Unexpected error.","status":500,"detail":"An unexpected error occurred. Please retry or contact the service administrator."}) - x-correlation-id: cdeb5254-ccfb-4d4a-9fbc-9ec04e1fd8cd
```

Can you have a look at what went wrong?
- x-correlation-id: `9fca88f0-e288-4484-8279-e47ec1929843`
- x-correlation-id: `cdeb5254-ccfb-4d4a-9fbc-9ec04e1fd8cd`

**Comment by ireactsam** [comment]
It might be a concurrency thing, before I was doing all the adds or all the deletes in concurrent requests... Now I switched to sequential one-by-one add and delete, didn't saw the 500 Internal server error anymore

**Comment by AIV-Bert** [comment]
Hi Sam,

It is indeed a concurrency issue. We will investigate this further and improve our error message to be more clearly.

Kind regards,

Bert
