### ISSUE TITLE
Contactorganisaties bij synergie

### ISSUE THREAD

**Issue by hij242** [Informatievlaanderen/GIPOD#68]
Bij aanmaak van een contactorganisatie, zoals de veiligheidscoördinatoren, op een synergie moeten we ofwel een organisationID of organisationName meegeven.  Daarnaast ook nog alle contact gegevens.

Maar bij de api om de contactorganisatie om te wijzigen blijken alleen de contact gegevens wijzigbaar.   Kan hier ook de organisationID en OrganisationName worden aan toegevoegd ?   

Onze veiligheidscoördinator zijn ook gekoppeld aan crediteuren in ons systeem.   Indien de persoon wijzigt, dan wijzigt de crediteur (organisatie) mee.

Mvg,
Bert De Groote

**Comment by AIV-Bert** [comment]
Beste,

Met de huidige API zal je in geval van een organisatie wijziging de oude gegevens moeten verwijderen, en daarna een nieuw contact moeten aanmaken met de juiste organisatie. Ik tag even onze technische architect om verder te bespreken of dit de werkwijze blijft.

Met vriendelijke groeten,

Bert

**Comment by doomsju** [comment]
Dag Bert,

Indien de contactorganisatie wijzigt dien je inderdaad de oude te verwijderen en de nieuwe toe te voegen. Indien de contacpersoon wijzigt maar de organisatie blijft identiek dan kan je deze updaten.

mvg,
Jürgen.
