### ISSUE TITLE
Transactionality of API

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#69]
I'm trying to create a GroundWork and immediately followed a creation of a MobilityHindrance for that groundwork:

 - POST /api/v1/groundworks
  - req = {...}
  - resp = CreatedResponseBody(201,Some(/api/v1/groundworks/10208163),Some(Groundwork was registered.))
- POST /api/v1/mobilityhindrances
  - req = {..."isConsequenceOfId":[10208163]}
  - resp = 400 {"type":"https://httpstatuses.com/400","title":"One or more validation errors occurred.","status":400,"detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:InvalidPublicDomainOccupancyId","title":"The specified condition was not met for 'Is Consequence Of Id'.","detail":"IsConsequenceOfId"}]}
  - x-correlation-id: b36dc3e5-5241-4793-aa71-8a095b6e8d61

I would expect that when I get a 201, the resource is created and I can reference it in a subsequent call ? 

(If I add a delay, like sleep for 30 seconds, the second call succeeds).

**Comment by AIV-Bert** [comment]
Hi Sam,

Although you get the ID of the created resource immediately, the processing in the background may take a moment. We will discuss this performance issue next week with the technical architect. 

You shouldn't see delays that high. 3-5 seconds should be enough of a delay. For the new UI I work with a retry mechanism that retries for 3 seconds and this seems enough.

Kind regards,

Bert

**Comment by ireactsam** [comment]
We will build in a retry to avoid the issue.
