### ISSUE TITLE
Link to GIPOD UI through ID

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#7]
Currenly, the GIPOD UI uses URL's including the ID of the intake (e.g. https://beta.gipod.vlaanderen.be/Werkopdrachten/Detail/2893371). This makes it possible to directly open the details page of an intake. 

Will this be supported in the new GIPOD UI?

**Comment by berdienderoo** [comment]
Can I conclude from the demo in sprint review 39 that the URL's for the new GIPOD web application will contain the ID? Will the URL structure that was visible in the demo (....gipod.vlaanderen.be/innames/[ID]) be the final one for intakes?

**Comment by doomsju** [comment]
If we have no good reasons we will not modify this URL's in the Web Application anymore.

This is will be the convention:

- **Register:**

/innames/nieuw

- **View:**

 /innames/{gipodid}

- **Modify:**

/innames/{gipodid}/wijzig

**Comment by berdienderoo** [comment]
Thanks, is the base url for the UI already known? Will this be https://gipod.vlaanderen.be/ for production and https://beta.gipod.vlaanderen.be/ for testing?
Is their a testing environment available for the web application?

**Comment by doomsju** [comment]
Url for Beta:   https://new.beta.gipod.vlaanderen.be/
We try to release regullary so you can follow the progess on the UI development.

**Comment by berdienderoo** [comment]
Thanks
