### ISSUE TITLE
MobilityHindranceZone.mobilityHindranceConsequence is required

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#74]
upon
```
POST /api/v1/mobility-hindrances { ... ,"mobilityHindranceZone":[ {... ,"mobilityHindranceConsequence": null } ]
```
the `mobilityHindranceConsequence` is required. When left out or set to null explicitly you get the error:
```
{
  "type": "https://httpstatuses.com/500",
  "title": "Unexpected error.",
  "status": 500,
  "detail": "An unexpected error occurred. Please retry or contact the service administrator."
}
```
x-correlation-id: 03491d8d-bfee-4e43-8575-ae1205eacb5b 
x-correlation-id: 3997d092-c7d8-46b0-916f-3267cb96dc0c 

The empty list `[]` is allowed.
Can you update the documentation and the OpenApi spec?

**Comment by vmateiaiv** [comment]
Hi @ireactsam,

This is indeed a bug. We will deploy a fix today asap.

Kind regards,
Voicu Matei
AIV

**Comment by vmateiaiv** [comment]
Hi @ireactsam,

The fix is deployed on BETA.

Kind regards,
Voicu Matei
AIV

**Comment by ireactsam** [comment]
Will the openapi spec be updated accordingly ?
