### ISSUE TITLE
TrenchSynergyRequests to be answered fails

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#75]
The operation /api/v1/trench-synergy-requests-to-be-answered to retrieve a list of TSR to be answered fails with unexpected error (500).

I added a collaboration zone but no success afterwards.

**Comment by doomsju** [comment]
Dag Jeroen,

De query-string parameter limit in de request geeft de waarde = 0. Deze waarde moet een getal zijn groter dan 0.

We zullen onze validatie aanpassen zodat dit in de response duidelijk is.

Is het mogelijk steeds ook de CorrelationId mee te geven die je kan vinden in de response headers dan kunnen we makkelijker in onze logs zoeken.

mvg,
Jürgen.
