### ISSUE TITLE
get groundwork : zone geometry komt niet mee

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#76]
Beste,

We begrijpen dat het alle hens aan dek is om de release te halen. 
Echter zien we (nog) niet de toegevoegde waarde om de zone en eigenlijk ook het toevoegen of raadplegen van contactpersonen (toezichter, aannemer, VC’s) niet te voorzien in de hoofd endpoints. Deze lijken ons niet echt zwaar dat ze zouden kunnen leiden tot performantieverlies. Daarnaast is het wel zo dat er meerdere calls gegenereerd dienen te worden indien dit alles apart moet opgevraagd en/of aangepast of toegevoegd moet worden.

Het genereert in de ontwikkeling ook heel wat meerwerk om al deze endpoints te integreren en daarnaast in de correcte flows te krijgen.
En dit alles ook klaar te krijgen tegen de release.

De zone is wel reeds mee bij SAV en een SS?

**Comment by AIV-Bert** [comment]
Beste @JanDegroote ,

De zone is momenteel niet op een consequente manier uit de API op te vragen en gaan we zeker bekijken.

Ik zie dat je naast zone, ook andere informatie in 1 grote request wil. Dit zal voor sommigen, waaronder jullie, een gunstige invloed hebben op jullie implementatie. Echter anderen hebben veel minder interesse in specifieke properties op de request. 

De uiteindelijke beslissing, hoe we bepaalde payloads opsplitsen is een afweging tussen performance, caching, response size ...
Onze huidige setup laat toe om te gaan cachen op een laag niveau. Zo kan de call naar een grote zone gecached blijven ook al passen we de status van de inname aan. Info zoals bepaalde contactgegevens, zijn dan weer niet voor elk proces nodig, of voor elke implementatie interessant.

Indien jullie implementatiekost drastisch verhoogt per endpoint, kan je altijd eens kijken naar onze [openApi specificatie](https://api-gateway.beta.gipod.vlaanderen.be/swagger/v1/swagger.json). Rond deze specificatie zijn al vele tools gebouwd om client code te genereren. Na de eenmalige setup worden nieuwe endpoints en (in de verre toekomst) nieuwe versies automatisch gegenereerd. Zeker interessant om eens te bekijken. Onze interne API integratie, de Gipod UI, wordt ook op deze wijze gebouwd.

Hopelijk verduidelijkt dit al enkele van jou vragen. Je opmerking over de inconsistente manier van een zone op te vragen, bekijken we verder hoe we dit aanpakken.

Met vriendelijke groeten,

Bert

**Comment by doomsju** [comment]
Dag Jan,

We zullen de geometrie opnemen in de response van een inname. 

De reden waarom we dit zo gedaan hebben is dat oorspronkelijk in de business werkgroepen was bepaald dat aan een inname meerdere zones gingen gekoppeld kunnen worden (eventzone, grondwerkzone, werfzone, corridorzone). Heel laat in het proces is dat dan gewijzigd naar één zone per inname (grondwerk->grondwerkzone, evenement->eventzone, werk -> werfzone) en worden de overige zones aan de gekoppelde hinder toegevoegd. Het was op dat moment niet meer aangewezen om de hele API daarop nog te gaan wijzigen aangezien we afgesproken hadden om geen grote breaking changes meer uit te voeren. Aangezien een inname in de praktijk nu maar één zone zal hebben zullen we de geometrie opnemen in de detail response. We laten evenwel de mogelijkheid om deze ook apart opvraagbaar te maken.

mvg,
Jürgen.

**Comment by doomsju** [comment]
Resolved in https://github.com/Informatievlaanderen/GIPOD/issues/109

**Comment by JanDegroote** [comment]
Bedankt!
