### ISSUE TITLE
Cannot create Work with a contactOrganisation without organisationId

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#77]
During create of a Work (this issue doesn't occur for Groundworks nor MobilityHindrance), it seems the an `organizationId` is mandatory, while you can omit it (and just set the `organisationName`) when adding new ContactOrganisations.

```
POST /api/v1/works

...,
"contactOrganisation":[{"email":"unknown@nowhere.be","roleId":"a55eb0a5-84fb-49f8-83c5-de669e4ae48e","contactName":"Andreke","isPublic":false,"organisationName":"AUDENAERT BVBA","telephone":"+3211101010"},...]
```
results in
```
400 Bad Request - {"type":"https://httpstatuses.com/400","title":"One or more validation errors occurred.","status":400,"detail":"Please refer to the errors property for additional details.","errors":[{"type":"urn:be.vlaanderen.gipod.errors:OrganisationNotFoundException","title":"Organisation not found for id: ","detail":"Organisation not found for id: "}]} - x-correlation-id: 67e2e6a2-0fdf-4d2c-8ba0-0e523e4feb98
```

**Comment by AIV-Bert** [comment]
Hi @ireactsam,

I can confirm this is indeed a bug and is reproducible. We will investigate this further.

Kind regards,

Bert

**Comment by doomsju** [comment]
We hebben dit vandaag gefixt op de Beta omgeving: https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1885798749/Hotfixes+0.8.0.0

**Comment by ireactsam** [comment]
Yep, het werkt!
