### ISSUE TITLE
Oude gipod(1) data in gipod(2)beta?

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#78]
In https://new.beta.gipod.vlaanderen.be/innames kan ik wel nog Gipod1 data terugvinden, maar de meest recente heeft ID 3728279 (Ref AWV:Werf=WerfId(18537):Inname=84b400c0-261e-11e8-b9e0-0a26e026bd80). Dat lijkt me erg oude data, ik denk dat al die data bij ons in Werf applicatie reeds als Uitgevoerd staat.

Kan ik recentere data uit gipod1 (prod?) in gipod(2) beta krijgen zodat we updates op van origine gipod1 data kunnen testen met de gipod2 integratie?

**Comment by doomsju** [comment]
Dag Sam,

Productie data kunnen wij niet in Beta krijgen. We plannen wel een extra staging omgeving die zal gesynchroniseerd worden met de huidige productie omgeving. Deze zal normaal gezien eind augustus, begin september beschikbaar zijn.

Jürgen.

**Comment by hixfield** [comment]
Is er mogelijks al meer info ivm opleveringsdatum van de staging omgeving?
Op werkverslag van 17 aug staat dat we al kunnen toegang kunnen vragen, hoe doen we dit best?

**Comment by doomsju** [comment]
Staging omgeving is opgeleverd: https://github.com/Informatievlaanderen/GIPOD/issues/106
