### ISSUE TITLE
MobilityHindrance created for Gipod1 migrated data: min/max/duplicates

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#79]
While looking into the MH, it seems that for the Gipod1 data, a MH is also created for these Innames.

- will there always be 1? 
- can there be more than 1, if yes how am I able to differentiate my MH i need to update?
- it seems that for the old gipod1 data they are duplicated entries in the `hasConsequences`, e.g. `GET https://api-gateway.beta.gipod.vlaanderen.be/api/v1/groundworks/3729600` has:
```
  "hasConsequence": [
    {
      "@id": "/api/v1/mobility-hindrances/10208706",
      "@type": "MobilityHindrance",
      "gipodId": 10208706
    },
    {
      "@id": "/api/v1/mobility-hindrances/10208706",
      "@type": "MobilityHindrance",
      "gipodId": 10208706
    }
  ],
...
```

**Comment by doomsju** [comment]
Hi Sam,
Importing hindrance from GIPOD1 should result in 1 mobility-hindrance in the new system. In the current response the hindrance is duplicated. We will fix this in the next release.

**Comment by doomsju** [comment]
Resolved in https://github.com/Informatievlaanderen/GIPOD/issues/109
