### ISSUE TITLE
Feedback: List of intake types - type of works and events

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#8]
The current list of intake types for 'manifestations' is rather short, resulting in a lot of intakes of type 'Other'. 
Since the list is maintained, although split into works and events, we would like to suggest to extend it. Suggestions for extension are: 

- Werken: Hoogtewerker
- Werken: Voertuikg (voertuig, aanhangwagen, werfagen,...)
- Werken: Andere (e.g. wc-unit, ...)
- Evenementen: uitstalling/handel
- Evenementen: reclame

**Comment by olivermay** [comment]
Thanks for the feedback, Berdien. I forwarded the feedback to the business, we will discuss this in an upcoming workgroup.

**Comment by naomioste** [comment]
We've discussed this suggestion in the business workgroup, and following type are approved (see also https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1234764302/Business+regels+Inname) :

- werken > bouwwerken > hoogtewerker
- werken > andere (this was already available)
- evenementen > uitstalling
- evenementen > reclame
