### ISSUE TITLE
How to map phases to parent projects?

### ISSUE THREAD

**Issue by NickDaelemans** [Informatievlaanderen/GIPOD#80]
We are using 2 organisations to get both projects and their phases. One organisation is used for projects, the other is used to get the phases.

However, we can't seem to find a way to map those phases to their parent projects. In the previous GIPOD version a phase had a 'reference' property that contained the projectid of their parent.

How is this managed inside the new GIPOD?

**Comment by AIV-Bert** [comment]
Hi @NickDaelemans

It is not 100% clear what you are using the previous version of Gipod. Projects and phases are not implemented in that version. It sounds like you had your own way of handling this despite the limits of the system. 

Seems like you made one 'werkopdracht' with one organiation, and more 'werkopdrachten' for each phase with the second organisation. You then linked these together using the reference field.

This convention based way of working on your end is still possible. A more streamlined way to handle projects & phases is planned in a later version of the 'new' Gipod.

Kind regards,

Bert

**Comment by NickDaelemans** [comment]
Thanks for your answer. Do you have any idea when this version will be available?

**Comment by olivermay** [comment]
Hi Nick, 

for the first release (November 2020) only basic project will be available, basically this will be a container for multiple public domain occupancies. The API's will be available on Beta in September/October. 

For projects and phases, this is part of a later release, and will become available in 2021, the exact timing depends on the priorities defined by the stakeholders.

cheers, 

Oliver
