### ISSUE TITLE
Kan geen organisaties aanmaken: invalid_scope

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#81]
Beste,

Wanneer ik bij de login procedure de scope `gipod_org_write` aanvraag krijg ik de foutmelding:
```
400 Bad Request

{"error":"invalid_scope","error_description":"Scope does not exist or is not available."}
```
Hier is overigens ook de structuur van de reply verschillend als wanneer er een fout met bv het JWT token (invalid_client) zich voordoet (`description` vs `error_description`):
```
400 Bad Request

{"error":"invalid_client","description":"Could not authenticate client through JWT token, Could not authenticate client through the header. Headers do not contain clientcredentials"}
```

1. Hoe verkrijg ik `gipod_org_write`?
1. Wordt de `description` vs `error_description` niet beter gelijk getrokken ?

mvg,
Sam

**Comment by doomsju** [comment]
Dag Sam,

De scope is toegevoegd aan de oauth client.
