### ISSUE TITLE
Cannot create suborganisation, what to use for geoSecureContactId ?

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#82]
in POST /api/v1/organisations geoSecureContactId seems to be mandatory and must be > 0 
```
{
  "name": "AWV voor De Werkgenootschap",
  "parentId": "dd6e1b72-2a4a-0276-8ce5-f75cc5a5a82c"
}
```
x-correlation-id: 20caa2c2-44df-4b20-896d-0a2c8b0edda8 

according to Severien, the geoSecureContactId should not be visible to us and not mandatory. 

I managed to create one with `"geoSecureContactId": 1` but that is like a random number, no idea what it should point to.

**Comment by doomsju** [comment]
We will provide a fix so that the GeoSecureContactId is not mandatory if the parentId is available in the request. 
We use this method internally to sync the existing organisations available in GeoSecute to the new GIPOD-system.

**Comment by ireactsam** [comment]
So you will probably need to remove the geoSecureContactId = 1 that I used to create the new suborganisation /api/v1/organisations/31eff97a-e541-0914-9a75-c9db2ce08a15

**Comment by ireactsam** [comment]
There is no DELETE operation for suborganisations neither.

**Comment by doomsju** [comment]
You can create sub-organisations without adding a GeoSecureContactId.
