### ISSUE TITLE
Will GIPOD2 still support "geoselectie.gipod.vlaanderen.be"?

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#86]
Using the current GIPOD version eventually we get the branches (vestigingen) of the affected enterprises using a REST interface at https://geoselectie.gipod.vlaanderen.be that is able to convert a "gipodid" to enterprise branches (from the "KBO").

Does GIPOD2 still support this? Or put differently, is it still possible with GIPOD2 to get from gipodid (from "mobility hindrance") to a list of affected branches/enterprises? I don't see this mentioned anywhere in the documentation.

In beta.oath.vlaanderen.be/admin I assume the corresponding scope is "GeoSelOndernemingen"

**Comment by doomsju** [comment]
The API for geoselectie can still be used after production of the  GIPOD². 
We still have to connect the geoselectie API with the new GIPOD environment. That's an internal change that will not affect clients of the API.
