### ISSUE TITLE
notifications : hoe geraken we aan het groundworkid die aan de basis ligt van trenchsynergyrequest

### ISSUE THREAD

**Issue by JanDegroote** [Informatievlaanderen/GIPOD#87]
**Huidige situatie(gipod 1.x):**
Per infra en per type (geosyn.notificatie_alert) worden nieuwe items opgehaald. Dit wordt dan in een tabel gezet, die dan gemaild wordt. De tabel bevat volgende items: id, datum, referentie en beschrijving.

Nieuwe situatie(gipod²):
Ik kan nog steeds per infra en per type items ophalen. Maar ik krijg erg beperkte info terug.
Request
<MT_MyNotifications>
    <NotificationType>SynergieAanvraagTeBeantwoorden</NotificationType>
    <StartDate>2020-07-24T00:00:00</StartDate>
    <Vestiging>Hasselt</Vestiging>
</MT_MyNotifications>
Response
<MT_NotificationList>
  <Notifications>
    <NotificationItem>
       <Category>Waarschuwing</Category>
       <CreatedOn>2020-07-24T02:00:00+02:00</CreatedOn>
       <DataItems>
          <DataItem>
             <DataKey>TrenchSynergyRequest</DataKey>
             <DataValue>10207925</DataValue>
          </DataItem>
       </DataItems>
       <ExpiresOn>2020-07-29T20:35:55.136938+02:00</ExpiresOn>
       <Id>33ece0a6-b93c-433b-9a34-1bc8e87dcac3</Id>
       <Organisation>Fluvius Site Hasselt</Organisation>
       <Status>Nieuw</Status>
       <Type>Te beantwoorden sleufsynergie aanvraag voor deadline 1</Type>
       <Value>33ece0a6-b93c-433b-9a34-1bc8e87dcac3</Value>
    </NotificationItem>
  </Notifications>
  <UpdateDate>2020-07-24T00:00:00</UpdateDate>
 <Succeeded>true</Succeeded>
  <Message>1 notifications found</Message>
</MT_NotificationList>
(Dit zijn mijn omgevormde xml’s.)

Nu krijgen we dus per item niet veel meer terug dan een id en een datum. Ik zou voor de id’s wel de overeenkomstige details kunnen ophalen (groundwork, synergy of synergyRequest).
Maar ik heb een probleem voor een synergyRequest: ik heb zowel het gipodid van het groundwork als de synergyRequest nodig. De 2e krijg ik terug via de notifications (boven), aan de eerste kan ik niet geraken. Ook niet via searchTrenchSynergyRequest.
Hoe geraken we dus aan de referentie en beschrijving?
Zou dit niet dadelijk kunnen opgenomen worden in de notificatie?

**Comment by doomsju** [comment]
Dag Jan,

Het lancerende grondwerk van een sleufsynergie-aanvraag kan opgevraagd worden via een detail van een sleufsynergie-aanvraag (GET /api/v1/groundworks/10000009/trench-synergy-requests/10000010). We zullen wel de gipodId van het lancerend grondwerk extra toevoegen in data-keys van deze notificatie.

**Comment by AIV-Bert** [comment]
De URL naar de TrenchSynergyRequest is reeds in een vorige versie toegevoegd aan de data.
