### ISSUE TITLE
Add "gipodId" to results of "SearchMobilityHindrances"

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#88]
When I look at the returned results for "SearchMobilityHindrances" at [https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/SearchMobilityHindrances](https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/SearchMobilityHindrances) "gipodId" is not in there as a separate field (in each item of the member section).

The gipodId is part of the "@id" field, so I can either parse the "@id" to get the last part from it, or I can "call" @id as that endpoint [https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/GetMobilityHindrance](https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/GetMobilityHindrance) does have "gipodId" as a separate field.

It would save processing to have an extra field "gipodId" in the member section (per item) of SearchMobilityHindrances, and it would make sense as other endpoints do return both "@id" and "@gipodId".

**Comment by doomsju** [comment]
Correct, de gipodId zal worden toegevoegd in de member section van de response.

**Comment by doomsju** [comment]
Resolved in https://github.com/Informatievlaanderen/GIPOD/issues/109
