### ISSUE TITLE
Relatie tussen grondwerk en synergie

### ISSUE THREAD

**Issue by langens-jonathan** [Informatievlaanderen/GIPOD#89]
Hey

Het attribuut dat de relatie tussen een grondwerk en een synergie aanduidt is een array (isPartOfTrenchSynergy). Van daar de vraag: wat betekent het als een grondwerk deel van meerder synergien uitmaakt?

Dank je wel
Jonathan

**Comment by doomsju** [comment]
Het is toegelaten dat een grondwerk in meerdere synergieën wordt opgenomen. Vermoedelijk zal dit wel niet zoveel voorkomen in de praktijk?
