### ISSUE TITLE
differential import detecting deleted projects

### ISSUE THREAD

**Issue by hixfield** [Informatievlaanderen/GIPOD#90]
Using the `{{baseUrl}}/api/v1/public-domain-occupancies` with the parameter `lastmodified.start` we can setup a differential import system into our own private database (for visualization). Meaning this allows us to only request and process any changes after the previous import.

What would be the recommended way, to detect any deleted projects?

I see 2 options:

- for a period of time, the differential returned projects have some sort of status that indicate that they are deleted.
Does the e.g; "`status`" field have something link that?

- it cannot be done via differential import, and we are forced, from time to time, to have to fetch ALL projects to see which are no longer returned and if these still exist in our private database we have to delete them. This is much more intensive operation that I would like to avoid. In this case is there a way to limit the amount of returned info to e.g. only the project ids (references)?

Your insights are greatly appreciated!

**Comment by doomsju** [comment]
Via endpoint GET /api/v1/public-domain-occupancies it's not possible to find deletes works, groundworks, works. We will forsee an endpoint where you can check which resources (groundworks, works, events, trench-synergies, mobiliy-hindrance,...) were deleted. We let you know when this is available.

**Comment by SilPal** [comment]
Hi Jürgen, when will this new endpoint (get deleted resources) be available on beta2 ?
Thanks

**Comment by doomsju** [comment]
It's taken up in development. Normally next release.

**Comment by SilPal** [comment]
I saw that is is taken up in release0.10.0, but do you have a date for this release ?
Thanks

**Comment by doomsju** [comment]
Resolved in API Beta 0.10.0
https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1978598065/Release+notes+API+Beta+0.10.0

Use endpoint: GET api\v1\entitities
