### ISSUE TITLE
Where can we find latitude and longitude of a project?

### ISSUE THREAD

**Issue by NickDaelemans** [Informatievlaanderen/GIPOD#91]
I was wondering if there was any way where can get the latitude and longitude of a project? In the previous version this was a property on the project detail ('Latitude' and 'Longitude').

**Comment by olivermay** [comment]
Projects are not yet implemented in the new GIPOD. 

Perhaps you meant public domain occupancy? In that case, you can search for pdo's using following api: https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#operation/SearchPublicDomainOccupancies the result contains a pointOnSurface which contains the x/y coordinate in Lamber72 coordinates.

**Comment by svanrintel** [comment]
@olivermay, @doomsju, We expected that the coords in the pointOfSurface field weren't going to be in Lambert72 anymore but in 'normal' coordinate format WGS84 (ex: 51.1483611,4.3942473). Are you planning on changing this?
This is kind of urgent as we are implementing https://github.com/Informatievlaanderen/GIPOD/issues/141.

**Comment by doomsju** [comment]
@svanrintel We're not planning to change this. The supported CRS is 31370 in the API https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1243021446/Geometry+information

All our geometry information is in Lambert72. We will not change this for one property.
