### ISSUE TITLE
How should we map 'Locaties' en 'Gevolgen' in the 'Hindergevolgen'?

### ISSUE THREAD

**Issue by NickDaelemans** [Informatievlaanderen/GIPOD#92]
I had a look at the mapping table of 'Hinder': https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1637090283/Mapping+van+Hinder

But I can't seem to find where we are able to get the locations and 'gevolgen' which are removed in GIPOD2. Can you point me in the right direction?

![image](https://user-images.githubusercontent.com/5577308/91302248-76af2a80-e7a6-11ea-98d2-f1b88cf54fe4.png)

**Comment by NickDaelemans** [comment]
Did you have a chance to look at this?

**Comment by olivermay** [comment]
Hi Nick, 

This information is now available as mobility hindrance. There is a link between public domain occupancies (groundwork, work, event) or a synergy and hindrance. The hindrance defines, for one or more locations (zones) the types of hindrance within this zone, here is an example:

![image](https://user-images.githubusercontent.com/4815604/91947735-ede14300-ecff-11ea-86c4-25a996aaf557.png)


You can find the api documentation for hindrance here: https://api-gateway.beta.gipod.vlaanderen.be/api-documentation.html#tag/MobilityHindrances

Are you planning to use the public API or the secured environment?

**Comment by NickDaelemans** [comment]
Hi @olivermay,

Thanks for explaining. We will be using the secured environment. When I try to fetch such a mobility hindrance, I get a 403 error. Probably something with our authorization call (scope)?

**Comment by NickDaelemans** [comment]
We are looking for the 'location' and the 'Gevolgen' as we received the from the current GIPOD version.

Hinder -> LocatiesHinder (example: 'Rijbaan')
Hinder -> GevolgenHinder (example: 'Omleiding: beide richtingen')

I can't find those in the documentation.

**Comment by olivermay** [comment]
The locations and consequences are merged into a single property named consequences, and is defined on the level of a hindrance zone. The list of all possible consequences can be found [here](https://vlaamseoverheid.atlassian.net/wiki/spaces/NGC/pages/1637090283/Mapping+van+Hinder#Alle-beschikbare-waarden-voor-hindergevolgen-in-GIPOD%C2%B2) or in the taxonomy [here](https://api-gateway.beta.gipod.vlaanderen.be/api/v1/taxonomies/mobility-hindrance/consequencetypes).


**An example:**
The hindrance: https://api-gateway.beta.gipod.vlaanderen.be/api/v1/mobility-hindrances/10210570 has one mobility hindrance zone: https://api-gateway.beta.gipod.vlaanderen.be/api/v1/mobility-hindrances/10210570/zones/b79abb4e-cb37-495a-b326-bf854767332f with following data:

```json
{
    "@context": "https://api-gateway.beta.gipod.vlaanderen.be/api/v1/context/enriched/public-domain-occupancy.jsonld",
    "@id": "/api/v1/mobility-hindrances/10210570/zones/b79abb4e-cb37-495a-b326-bf854767332f",
    "@type": "MobilityHindranceZone",
    "zone": {
        "@type": "Geometry",
        "wkt": "POLYGON ((1691...370978084))"
    },
    "zoneType": {
        "@id": "/api/v1/taxonomies/zonetypes/0fb72ef7-6ac9-4a70-b295-a30ea215d250",
        "prefLabel": "HinderZone"
    },
    "consequence": [
        {
            "@id": "/api/v1/taxonomies/mobility-hindrance/consequencetypes/c53813ab-814f-4ff4-8a87-6934c72e175f",
            "prefLabel": "Geen doorgang"
        }
    ]
}
```

So the consequence of this zone is: "Geen doorgang", which is a child of consequence "Gemotoriseerd verkeer".

**Comment by NickDaelemans** [comment]
Thanks. Makes sense, but I'm wondering where I can find the 'location' of the hindrance. In the current version we can get 'Rijbaan' for example, which is the physical part of the road that the hindrance is on.

**Comment by olivermay** [comment]
The location is no longer saved in GIPOD, the business decided this was no longer necessary. The actual hindrance is more important. For example, pedestrians might be able to pass through a corridor, even when the sidewalk is completely occupied.

There are ways however to get the hindrance location from the data:
1. You can 'guess' it from the hindrance consequence, when road traffic is affected, the hindrance is probably on the road.
2, You can get the actual location of the hindrance by overlaying the hindrance zone with another map such as GRB.

Hope this helps. What are you planning to use the location for?

**Comment by NickDaelemans** [comment]
Many thanks for your quick reply. We use the location to show on the website of Aquafin. We'll have to discuss the importance of this. Thanks a lot!
