### ISSUE TITLE
ModifyGroundwork: AddressId null not allowed

### ISSUE THREAD

**Issue by wdfluv** [Informatievlaanderen/GIPOD#93]
**Describe the bug**
ModifyGroundwork: 
{"key":"AddressId","value":null} 
results in a validation error: Value for AddressId should be Integer. 

**Expected behavior**
null is allowed, as per the example provided in the API documentation

**Comment by AIV-Bert** [comment]
Null is allowed when registering, when you add a wkt.

During patch this is not allowed.
