### ISSUE TITLE
ModifyTrenchSynergy: single value not allowed for TrenchSynergyGroundworks

### ISSUE THREAD

**Issue by wdfluv** [Informatievlaanderen/GIPOD#94]
**Describe the bug**
ModifyTrenchSynergy:
{"key":"TrenchSynergyGroundworks","value":"10207618"}
results in validation error: {"type":"urn:be.vlaanderen.gipod.errors:InvalidValue","title":"Value for TrenchSynergyGroundworks should be of type 'Int64[]'.","detail":"Items[3].TrenchSynergyGroundworks"}

**Expected behavior**
Single value (no array), and string should be allowed, as specified in the following patch: https://github.com/Informatievlaanderen/GIPOD/issues/49

**Comment by doomsju** [comment]
Resolved in https://github.com/Informatievlaanderen/GIPOD/issues/109
