### ISSUE TITLE
gipopId's tussen GIPOD1 en GIPOD2

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#96]
Ik werk momenteel voor vlaio hinderpremie. Is er informatie over hoe gipodIds gemapt gaan worden tussen oude en nieuwe gipod?

De context: ik heb gipodIds van GIPOD1 die opgeladen zijn in hinderpremie en die worden gemapped op ondernemingensvestigingen via de geoselectie gipod service, latere synchronisatie gebeurt op gipodId. Voor zover alles ok. We schakelen over op GIPOD2, de gipodIds van GIPOD1 zitten nog in hinderpremie. Als ik de bestaande oude (GIPOD1) gipodIds ophaal via GIPOD2, wat ga ik juist terugkrijgen?

In GIPOD1 heb ik "hinder", in GIPOD2 is dat "gesplitst" in minstens 2 stukken: een soort hinder en een gevolg (mobile hindrance) met elk een eigen gipodId.

Of is het de bedoeling dat ik bij transitie alle GIPOD1 informatie verwijder, en de gevolgen van scratch ophaal via GIPOD2?

**Comment by doomsju** [comment]
De gipodId's blijven identiek tussen beide versies van GIPOD. Een inname aangemaakt in de oude omgeging zal dezelfde gipodId hebben in Gipod².
Voor geoselectie zal je in eerste fase nog steeds de gipodId van de inname (grondwerk, werk) moeten doorgeven. Enkel de manier waarop jullie de gipodId's selecteren die moeten doorgegeven worden aan de geoselectie-api zullen jullie moeten aanpassen. Eerst hinder opzoeken die voldoet aan jullie criteria om in aanmerking te komen voor een hinderpremie en op basis van de hinder kunnen jullie de gipodId van gerelateerde inname selecteren.
