### ISSUE TITLE
Aanbevolen setup testing + test data (groundworks)

### ISSUE THREAD

**Issue by hixfield** [Informatievlaanderen/GIPOD#97]
We ontwikkelen momenteel een viewer op de groundworks (gefilterd, kaartje enz...).
Hiervoor importeren we de groundworks in een achterliggend CMS systeem.

We hebben een **development**, **staging** en **productie** omgeving.

Wat is de aanbevolen setup voor end-2-end testing en introductie van test data:

- import in onze CMS: onze development koppelen met GIPOD/beta, staging met de upcomming GIPOD/staging omgeving (zoals vermeld hier https://github.com/Informatievlaanderen/GIPOD/issues/78) en productie met GIPOD/Productie?

- is het mogelijk dat we via de "gewone" UI test data kunnen inputten in (1) GIPOD/beta en (2) GIPOD/staging? Ik lees in vragenuurtje rapport van 17aug dat GIPOD/staging gesynced gaat worden met productie? Wordt inputted test data hier dan overschreven?

- andere gedachten (alternatief): een groundwork project bestempelen als een test (bvb met een flag, special status...). Dit is misschien een alternatief om test data te laten vloeien en te verhinderen dat deze tot bij de eindgebruiker komt. Maar mooi gesplitste omgevingen met input mogelijkheid van test data zijn zeker de voorkeur.

**Comment by doomsju** [comment]
Ik zou inderdaad de setup nemen zoals je beschrijft in de eerste bullet.Het zal mogelijk zijn om via de GUI test data in te geven. 
In de staging omgeving zal initieel data terecht komen van de huidige GIPOD productie omgeving. Nieuwe data die je rechtstreeks input via Api of GUI op de nieuwe staging omgeving zal binnen die omgeving blijven bestaan.
We gaan zeker een strikte scheiding blijven behouden tussen de omgevingen.

**Comment by hixfield** [comment]
Hartelijk dan voor snelle antwoord Doomsju.
Meer nieuws ivm staging oplevering en aanvraag toegang cfr #78 ?

**Comment by doomsju** [comment]
Toegangen kan je nu reeds aanvragen via de gebruikelijke weg. 
Momenteel zijn we de staging-omgeving aan het opzetten. We voorzien deze vrij te geven eind deze week of begin volgende week.
