### ISSUE TITLE
GIPOD1 - GIPOD2 side-by-side an switch over

### ISSUE THREAD

**Issue by hixfield** [Informatievlaanderen/GIPOD#99]
- Kunnen groundworks nog altijd ingegeven worden met de GIPOD1/GUI na 23 november?
- Indien ja, hoelang dan nog?
- Indien we tijdens de overgangsperiode tussen 23 nov en eind feb de oude GIPOD1/GUI gebruiken (voor groundworks) komt deze inputted data dan equivalent uit de web services zowel in GIPOD1 als GIPOD2?

**Comment by olivermay** [comment]
Na de release kan je nog steeds gegevens ingeven in het oude GIPOD (enkel via API). We voorzien een overgangsperiode tot ten laatste eind februari 2021. De nieuwe GUI vervangt op 23 november de bestaande, GUI gebruikers stappen dus automatisch over.

De ingevoerde data in GIPOD1 wordt gesynchroniseerd naar het nieuwe GIPOD. Dit is nu al het geval, en kan opgevraagd worden via de nieuwe productie API: https://api-gateway.gipod.vlaanderen.be/

Let wel op dat de gegevens die worden ingevoerd in het vernieuwde GIPOD, vanaf 23 november, *niet* terugvloeien naar GIPOD1. Dus als je na 23 november gaat lezen uit GIPOD1 heb je niet alle data.

We raden daarom aan om zo snel mogelijk over te stappen met integraties.

**Comment by hixfield** [comment]
@olivermay dus de GUI om gegevens in te vullen in GIPOD1 vervalt na 23 november. Het is te zeggen: de bestaande GUI (gaande naar GIPOD1) wordt automatisch vervangen door een update GUI (gaande naar GIPOD2). Dus het is niet meer mogelijk om via de GUI gegevens in de GIPOD1 te steken.

Correct?

**Comment by olivermay** [comment]
Correct
